// Auto-generated by cft from: cat.c
// May require manual edits.

///
 cat -- concatenate files and print on the standard output.
   Copyright (C) 1988-2026 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
///

///
 Differences from the Unix cat:
   * Always unbuffered, -u is ignored.
   * Usually much faster than other versions of cat, the difference
   is especially apparent when using the -v option.

   By tege@sics.se, Torbjörn Granlund, advised by rms, Richard Stallman.
///

byte* PROGRAM_NAME = "cat";
macro AUTHORS
{
    proper_name_lite ( "Torbjorn Granlund" , "Torbj\303\266rn Granlund" ) , proper_name ( "Richard M. Stallman" )
};

uint LINE_COUNTER_BUF_LEN = 20;
extern byte* infile;
extern int input_desc;
byte[20] line_buf = 20;
byte* line_num_print = line_buf + 20 - 8;
byte* line_num_start = line_buf + 20 - 3;
byte* line_num_end = line_buf + 20 - 3;
int newlines2 = 0;
extern int pending_cr;
cdecl usage(int status) -> void
{
    if (status != EXIT_SUCCESS)
        do
        {
            fprintf;
        }
        while (0);
    else
    {
        printf;
        fputs;
        emit_stdin_note();
        oputs_("cat", gettext("\
  -A, --show-all           equivalent to -vET\n\
"));
        oputs_("cat", gettext("\
  -b, --number-nonblank    number nonempty output lines, overrides -n\n\
"));
        oputs_("cat", gettext("\
  -e                       equivalent to -vE\n\
"));
        oputs_("cat", gettext("\
  -E, --show-ends          display $ or ^M$ at end of each line\n\
"));
        oputs_("cat", gettext("\
  -n, --number             number all output lines\n\
"));
        oputs_("cat", gettext("\
  -s, --squeeze-blank      suppress repeated empty output lines\n\
"));
        oputs_("cat", gettext("\
  -t                       equivalent to -vT\n\
"));
        oputs_("cat", gettext("\
  -T, --show-tabs          display TAB characters as ^I\n\
"));
        oputs_("cat", gettext("\
  -u                       (ignored)\n\
"));
        oputs_("cat", gettext("\
  -v, --show-nonprinting   use ^ and M- notation, except for LFD and TAB\n\
"));
        oputs_("cat", gettext("      --help\n         display this help and exit\n"));
        oputs_("cat", gettext("      --version\n         output version information and exit\n"));
        printf;
        emit_ancillary_info("cat");
    };
    exit(status);
};

cdecl next_line_num() -> void
{
    byte* endp = line_num_end;
    do
    {
        if ((*endp)++ < '9')
            return void;
        *endp-- = '0';
    }
    while (endp >= line_num_start);
    if (line_num_start > line_buf)
        *--line_num_start = '1';
    else
        *line_buf = '>';
    if (line_num_start < line_num_print)
        line_num_print--;
};

cdecl simple_cat(byte* buf, int bufsize) -> int
{
    while (true)
    {
        if (n_read < 0)
        {
            error;
        };
        if (full_write ( STDOUT_FILENO , buf , n_read ) != n_read)
            write_error();
    };
};

cdecl write_pending(byte* outbuf, byte** bpout) -> void
{
    if (0 < n_write)
    {
        if (full_write ( STDOUT_FILENO , outbuf , n_write ) != n_write)
            write_error();
        *bpout = outbuf;
    };
};

cdecl cat(byte* inbuf, int insize, byte* outbuf, int outsize, int show_nonprinting, int show_tabs, int number, int number_nonblank, int show_ends, int squeeze_blank) -> int
{
    byte ch;
    int newlines = newlines2;
    byte* eob = inbuf;
    byte* bpin = eob + 1;
    byte* bpout = outbuf;
    while (true)
    {
        do
        {
            if (outbuf + outsize <= bpout)
            {
                byte* wp = outbuf;
                do
                {
                    if (full_write != outsize)
                        write_error();
                    wp += outsize;
                }
                while (outsize <= remaining_bytes);
                memmove;
            };
            if (bpin > eob)
            {
                bool;
                if (! input_pending)
                    write_pending(outbuf, @bpout);
                if (n_read < 0)
                {
                    error;
                    write_pending(outbuf, @bpout);
                    newlines2 = newlines;
                };
                if (n_read == 0)
                {
                    write_pending(outbuf, @bpout);
                    newlines2 = newlines;
                };
                bpin = inbuf;
                *eob = '\n';
            }
            else
            {
                if (++newlines > 0)
                {
                    if (newlines >= 2)
                    {
                        newlines = 2;
                        if (squeeze_blank)
                        {
                            ch = *bpin++;
                            continue;
                        };
                    };
                    if (number & !number_nonblank)
                    {
                        next_line_num();
                        bpout = stpcpy(bpout, line_num_print);
                    };
                };
                if (show_ends)
                {
                    if (pending_cr)
                    {
                        *bpout++ = '^';
                        *bpout++ = 'M';
                    };
                    *bpout++ = '$';
                };
                *bpout++ = '\n';
            };
            ch = *bpin++;
        }
        while (ch == '\n');
        if (pending_cr)
        {
            *bpout++ = '\r';
        };
        if (newlines >= 0 & number)
        {
            next_line_num();
            bpout = stpcpy(bpout, line_num_print);
        };
        if (show_nonprinting)
        {
            while (true)
            {
                if (ch >= 32)
                {
                    if (ch < 127)
                        *bpout++ = ch;
                    elif (ch == 127)
                    {
                        *bpout++ = '^';
                        *bpout++ = '?';
                    };
                    else
                    {
                        *bpout++ = 'M';
                        *bpout++ = '-';
                        if (ch >= 128 + 32)
                        {
                            if (ch < 128 + 127)
                                *bpout++ = ch - 128;
                            else
                            {
                                *bpout++ = '^';
                                *bpout++ = '?';
                            };
                        }
                        else
                        {
                            *bpout++ = '^';
                            *bpout++ = ch - 128 + 64;
                        };
                    };
                }
                elif (ch == '\t' & !show_tabs)
                    *bpout++ = '\t';
                else
                    if (ch == '\n')
                    {
                        newlines = -1;
                        break;
                    }
                    else
                    {
                        *bpout++ = '^';
                        *bpout++ = ch + 64;
                    };
                ch = *bpin++;
            };
        }
        else
        {
            while (true)
            {
                if (ch == '\t' & show_tabs)
                {
                    *bpout++ = '^';
                    *bpout++ = ch + 64;
                }
                elif (ch != '\n')
                {
                    if (ch == '\r' & *bpin == '\n' & show_ends)
                    {
                        if (bpin == eob)
                        else
                        {
                            *bpout++ = '^';
                            *bpout++ = 'M';
                        };
                    }
                    else
                        *bpout++ = ch;
                };
                else
                {
                    newlines = -1;
                    break;
                };
                ch = *bpin++;
            };
        };
    };
};

cdecl copy_cat() -> int
{
};

cdecl splice_cat() -> int
{
    bool;
    bool;
    bool;
};

cdecl ensure_buf_size(byte* buf, int* buf_alloc, int alignment, int size) -> byte*
{
    affirm;
    if (*buf_alloc < size)
    {
        alignfree(buf);
        buf = xalignalloc(alignment, size);
        *buf_alloc = size;
    };
    return buf;
};

cdecl main(int argc, byte** argv) -> int
{
    bool;
    stat ostat_buf;
    bool;
    bool;
    bool;
    bool;
    bool;
    bool;
    int file_open_mode;
    int long_options;
    set_program_name(argv[0]);
    setlocale;
    atexit;
    int c;
    while ((c = getopt_long) != -1)
    {
        switch (c)
        {
            case ('b')
            {
                break switch;
            }
            case ('e')
            {
                break switch;
            }
            case ('n')
            {
                break switch;
            }
            case ('s')
            {
                break switch;
            }
            case ('t')
            {
                break switch;
            }
            case ('u')
            {
            }
            case ('v')
            {
                break switch;
            }
            case ('A')
            {
                break switch;
            }
            case ('E')
            {
                break switch;
            }
            case ('T')
            {
                break switch;
            }
            case (GETOPT_HELP_CHAR)
            {
                usage;
                break switch;
            }
            case (GETOPT_VERSION_CHAR)
            {
                version_etc;
                exit;
                break switch;
            }
            default
            {
            };
        };
    };
    if (fstat < 0)
        error;
    int out_flags = -2;
    bool;
    if (! ( number || show_ends || squeeze_blank ))
    {
        xset_binary_mode;
    };
    infile = "-";
    int argind;
    bool;
    byte* inbuf;
    byte* outbuf;
    do
    {
        if (argind < argc)
            infile = argv[argind];
        bool;
        if (reading_stdin)
        {
            if (file_open_mode & O_BINARY)
                xset_binary_mode;
        }
        else
        {
            input_desc = open(infile, file_open_mode);
            if (input_desc < 0)
            {
                error;
                continue;
            };
        };
        stat istat_buf;
        if (fstat(input_desc, @istat_buf) < 0)
        {
            error;
            goto contin;
        };
        fdadvise;
        if (!(S_ISFIFO(istat_buf.) | S_ISSOCK(istat_buf.) | S_TYPEISSHM(@istat_buf) | S_TYPEISTMO(@istat_buf)) & !(S_TYPEISSHM(@ostat_buf) | S_TYPEISTMO(@ostat_buf)) & SAME_INODE(istat_buf, ostat_buf))
        {
            if (0 <= in_pos)
            {
                if (out_flags < -1)
                    out_flags = fcntl;
                int whence;
                if (in_pos < lseek ( STDOUT_FILENO , 0 , whence ))
                {
                    error(0, 0, gettext("%s: input file is output file"), quotearg_n_style_colon);
                    goto contin;
                };
            };
        };
        if (! ( number || show_ends || show_nonprinting || show_tabs || squeeze_blank ))
        {
            int copy_cat_status;
            if (copy_cat_status != 0)
            else
            {
                int splice_cat_status = ((usable_st_size(@istat_buf) & istat_buf. <= 32768) ? 0 : splice_cat());
                if (splice_cat_status != 0)
                else
                {
                    inbuf = ensure_buf_size;
                };
            };
        }
        else
        {
            inbuf = ensure_buf_size;
            if (ckd_mul | ckd_add | ckd_add)
                xalloc_die();
            outbuf = ensure_buf_size;
        };
        label contin:
        if (! reading_stdin && close ( input_desc ) < 0)
        {
            error;
        };
    }
    while (++argind < argc);
    if (pending_cr)
    {
        if (full_write != 1)
            write_error();
    };
    if (have_read_stdin && close ( STDIN_FILENO ) < 0)
        error;
};
