// Auto-generated by cft from: chcon.c
// May require manual edits.

///
 chcon -- change security context of files
   Copyright (C) 2005-2026 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
///

byte* PROGRAM_NAME = "chcon";
macro AUTHORS
{
    proper_name ( "Russell Coker" ) , proper_name ( "Jim Meyering" )
};

// macro (multi-statement, manual translation needed): SET_COMPONENT(C, comp) do { if ( specified_{comp} && context_{comp}{_set} ( ( C ) , specified_{comp} ) ) { error ( 0 , errno , _ ( "failed to set %s security context component to %s" ) , # comp , quote ( specified_{comp} ) ) ; ok = false ; } } while ( 0 )
extern int affect_symlink_referent;
extern int recurse;
extern int verbose;
struct dev_ino;
dev_ino* root_dev_ino = dev_ino;
extern byte* specified_context;
extern byte* specified_user;
extern byte* specified_role;
extern byte* specified_range;
extern byte* specified_type;
uint DEREFERENCE_OPTION = 0;
uint NO_PRESERVE_ROOT = 1;
uint PRESERVE_ROOT = 2;
uint REFERENCE_FILE_OPTION = 3;

struct option;
extern int long_options;
cdecl compute_context_from_mask(byte* context, int* ret) -> int
{
    bool;
    if (! new_context)
    {
        error;
        return 1;
    };
    do
    {
        if (specified_user ? context_user_set)
        {
            error;
        };
    }
    while (0);
    do
    {
        if (specified_range ? context_range_set)
        {
            error;
        };
    }
    while (0);
    do
    {
        if (specified_role ? context_role_set)
        {
            error;
        };
    }
    while (0);
    do
    {
        if (specified_type ? context_type_set)
        {
            error;
        };
    }
    while (0);
    if (! ok)
    {
        int saved_errno;
        context_free;
        return 1;
    };
    return 0;
};

cdecl change_file_context(int fd, byte* file) -> int
{
    byte* file_context;
    byte* context_string;
    int errors = 0;
    if (specified_context == NULL)
    {
        int status = (affect_symlink_referent ? getfileconat(fd, file, @file_context) : lgetfileconat(fd, file, @file_context));
        if (status < 0 && errno != ENODATA)
        {
            error;
            return 1;
        };
        if (file_context == NULL)
        {
            error(0, 0, gettext("can't apply partial context to unlabeled file %s"), quotearg_style);
            return 1;
        };
        if (compute_context_from_mask)
        {
            freecon(file_context);
            return 1;
        };
        context_string = context_str;
    }
    else
    {
        context_string = specified_context;
    };
    if (file_context == NULL || ! streq ( context_string , file_context ))
    {
        int fail = (affect_symlink_referent ? setfileconat(fd, file, context_string) : lsetfileconat(fd, file, context_string));
        if (fail)
        {
            errors = 1;
            error;
        };
    };
    if (specified_context == NULL)
    {
        context_free;
        freecon(file_context);
    };
    return errors;
};

cdecl process_file(int* fts, int* ent) -> int
{
    byte* file_full_name = ent.;
    byte* file = ent.;
    stat* file_stats = ent.;
    bool;
    switch (ent.)
    {
        if (recurse)
        {
            if (ROOT_DEV_INO_CHECK(root_dev_ino, ent.))
            {
                ROOT_DEV_INO_WARN(file_full_name);
                fts_set;
                ignore_value(fts_read(fts));
            };
        };
        if (ent -> fts_level == FTS_ROOTLEVEL && ent -> fts_number == 0)
        {
            ent. = 1;
            fts_set;
        };
        error(0, ent., gettext("cannot access %s"), quotearg_style);
        error(0, ent., "%s", quotearg_n_style_colon);
        error(0, ent., gettext("cannot read directory %s"), quotearg_style);
        if (cycle_warning_required(fts, ent))
        {
            do
            {
                error(0, 0, gettext("\
WARNING: Circular directory structure.\n\
This almost certainly means that you have a corrupted file system.\n\
NOTIFY YOUR SYSTEM MANAGER.\n\
The following directory is part of the cycle:\n  %s\n"), quotearg_n_style_colon);
            }
            while (0);
        };
        default
        {
        };
    };
    if (ent -> fts_info == FTS_DP && ok && ROOT_DEV_INO_CHECK ( root_dev_ino , file_stats ))
    {
        ROOT_DEV_INO_WARN(file_full_name);
    };
    if (ok)
    {
        if (verbose)
            printf(gettext("changing security context of %s\n"), quotearg_style);
    };
    if (!recurse)
        fts_set;
};

cdecl process_files(byte** files, int bit_flags) -> int
{
    bool;
    while (true)
    {
        if (ent == NULL)
        {
            if (errno != 0)
            {
                error;
            };
            break;
        };
    };
    if (fts_close != 0)
    {
        error;
    };
};

cdecl usage(int status) -> void
{
    if (status != EXIT_SUCCESS)
        do
        {
            fprintf;
        }
        while (0);
    else
    {
        printf;
        fputs;
        emit_mandatory_arg_note();
        oputs_("chcon", gettext("\
      --dereference\n\
         affect the referent of each symbolic link (this is\n\
         the default), rather than the symbolic link itself\n\
"));
        oputs_("chcon", gettext("\
  -h, --no-dereference\n\
         affect symbolic links instead of any referenced file\n\
"));
        oputs_("chcon", gettext("\
  -u, --user=USER\n\
         set user USER in the target security context\n\
"));
        oputs_("chcon", gettext("\
  -r, --role=ROLE\n\
         set role ROLE in the target security context\n\
"));
        oputs_("chcon", gettext("\
  -t, --type=TYPE\n\
         set type TYPE in the target security context\n\
"));
        oputs_("chcon", gettext("\
  -l, --range=RANGE\n\
         set range RANGE in the target security context\n\
"));
        oputs_("chcon", gettext("\
      --no-preserve-root\n\
         do not treat '/' specially (the default)\n\
"));
        oputs_("chcon", gettext("\
      --preserve-root\n\
         fail to operate recursively on '/'\n\
"));
        oputs_("chcon", gettext("\
      --reference=RFILE\n\
         use RFILE's security context rather than specifying a CONTEXT value\n\
"));
        oputs_("chcon", gettext("\
  -R, --recursive\n\
         operate on files and directories recursively\n\
"));
        oputs_("chcon", gettext("\
  -v, --verbose\n\
         output a diagnostic for every file processed\n\
"));
        emit_symlink_recurse_options_("chcon", "-P");
        oputs_("chcon", gettext("      --help\n         display this help and exit\n"));
        oputs_("chcon", gettext("      --version\n         output version information and exit\n"));
        emit_ancillary_info("chcon");
    };
    exit(status);
};

cdecl main(int argc, byte** argv) -> int
{
    int bit_flags;
    int dereference = -1;
    bool;
    bool;
    bool;
    byte* reference_file;
    int optc;
    set_program_name(argv[0]);
    setlocale;
    atexit;
    while ((optc = getopt_long) != -1)
    {
    };
    if (recurse)
    {
        if (bit_flags == FTS_PHYSICAL)
        {
            if (dereference == 1)
                error;
        }
        else
        {
            if (dereference == 0)
                error;
        };
    }
    else
    {
        affect_symlink_referent = (dereference != 0);
    };
    if (argc - optind < ( reference_file || component_specified ? 1 : 2 ))
    {
        if (argc <= optind)
            error(0, 0, gettext("missing operand"));
        else
            error(0, 0, gettext("missing operand after %s"), quote(argv[argc - 1]));
        usage;
    };
    if (reference_file)
    {
        byte* ref_context;
        if (getfilecon(reference_file, @ref_context) < 0)
            error;
        specified_context = ref_context;
    }
    elif (component_specified)
    {
    };
    else
    {
        if (0 < is_selinux_enabled() & security_check_context(specified_context) < 0)
            error;
    };
    if (reference_file && component_specified)
    {
        error(0, 0, gettext("conflicting security context specifiers given"));
        usage;
    };
    if (recurse && preserve_root)
    {
        dev_ino dev_ino_buf;
        root_dev_ino = get_root_dev_ino(@dev_ino_buf);
        if (root_dev_ino == NULL)
            error;
    }
    else
    {
    };
};
