// Auto-generated by cft from: chmod.c
// May require manual edits.

///
 chmod -- change permission modes of files
   Copyright (C) 1989-2026 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
///

///
 Written by David MacKenzie <djm@gnu.ai.mit.edu>
///

byte* PROGRAM_NAME = "chmod";
macro AUTHORS
{
    proper_name ( "David MacKenzie" ) , proper_name ( "Jim Meyering" )
};

struct change_status
{
    enum (unnamed at tests/coreutils/chmod.c:43:3) status;
    int old_mode;
    int new_mode;
};

enum Verbosity
{
    V_high,
    V_changes_only,
    V_off
};

struct mode_change;
mode_change* change = mode_change;
extern int umask_value;
extern int recurse;
int dereference = -1;
extern int force_silent;
extern int diagnose_surprises;
Verbosity verbosity = Verbosity;
struct dev_ino;
dev_ino* root_dev_ino = dev_ino;
uint DEREFERENCE_OPTION = 0;
uint NO_PRESERVE_ROOT = 1;
uint PRESERVE_ROOT = 2;
uint REFERENCE_FILE_OPTION = 3;

struct option;
extern int long_options;
cdecl mode_changed(int dir_fd, byte* file, byte* file_full_name, int old_mode, int new_mode) -> int
{
    if (new_mode & ( S_ISUID | S_ISGID | S_ISVTX ))
    {
        stat new_stats;
        if (fstatat(dir_fd, file, @new_stats, 0) != 0)
        {
            if (!force_silent)
                error;
        };
        new_mode = new_stats.;
    };
};

cdecl describe_change(byte* file, change_status* ch) -> void
{
    byte[12] perms = 12;
    byte[12] old_perms = 12;
    byte* fmt;
    byte* quoted_file = quotearg_style;
    switch (ch.status)
    {
        case (CH_NOT_APPLIED)
        {
            printf(gettext("neither symbolic link %s nor referent has been changed\n"), quoted_file);
            return void;
        }
        case (CH_NO_STAT)
        {
            printf(gettext("%s could not be accessed\n"), quoted_file);
            return void;
        }
        case (CH_FAILED)
        {
        }
    };
    ulong old_m;
    ulong m;
    strmode(ch, perms);
    perms[10] = '\0';
    strmode(ch, old_perms);
    old_perms[10] = '\0';
    switch (ch.status)
    {
        case (CH_SUCCEEDED)
        {
            fmt = gettext("mode of %s changed from %04lo (%s) to %04lo (%s)\n");
            break switch;
        }
        case (CH_FAILED)
        {
            fmt = gettext("failed to change mode of %s from %04lo (%s) to %04lo (%s)\n");
            break switch;
        }
        case (CH_NO_CHANGE_REQUESTED)
        {
            fmt = gettext("mode of %s retained as %04lo (%s)\n");
            printf(fmt, quoted_file, m, @perms[1]);
            return void;
        }
        case (CH_NO_STAT)
        {
        }
    };
    printf(fmt, quoted_file, old_m, @old_perms[1], m, @perms[1]);
};

cdecl process_file(int* fts, int* ent) -> int
{
    byte* file_full_name = ent.;
    byte* file = ent.;
    stat* file_stats = ent.;
    change_status ch = {0};
    ch.status = CH_NO_STAT;
    stat stat_buf;
    switch (ent.)
    {
        if (ent -> fts_level == FTS_ROOTLEVEL && ent -> fts_number == 0)
        {
            ent. = 1;
            fts_set;
        };
        if (!force_silent)
            error(0, ent., gettext("cannot access %s"), quotearg_style);
        if (!force_silent)
            error(0, ent., "%s", quotearg_n_style_colon);
        if (!force_silent)
            error(0, ent., gettext("cannot read directory %s"), quotearg_style);
        if (dereference)
        {
            if (!force_silent)
                error(0, 0, gettext("cannot operate on dangling symlink %s"), quotearg_style);
            break switch;
        };
        ch.status = CH_NOT_APPLIED;
        if (dereference == 1)
        {
            if (fstatat(fts., file, @stat_buf, 0) != 0)
            {
                if (!force_silent)
                    error;
                break switch;
            };
            file_stats = @stat_buf;
        };
        ch.status = CH_NOT_APPLIED;
        if (cycle_warning_required(fts, ent))
        {
            do
            {
                error(0, 0, gettext("\
WARNING: Circular directory structure.\n\
This almost certainly means that you have a corrupted file system.\n\
NOTIFY YOUR SYSTEM MANAGER.\n\
The following directory is part of the cycle:\n  %s\n"), quotearg_n_style_colon);
            }
            while (0);
        };
        default
        {
        };
    };
    if (ch.status == CH_NOT_APPLIED & ROOT_DEV_INO_CHECK(root_dev_ino, file_stats))
    {
        ROOT_DEV_INO_WARN(file_full_name);
        fts_set;
        ignore_value(fts_read(fts));
    };
    if (ch.status == CH_NOT_APPLIED)
    {
        ch = file_stats;
        ch = mode_adjust;
        bool;
        if (fchmodat == 0)
            ch.status = CH_SUCCEEDED;
        else
        {
            if (!is_ENOTSUP)
            {
                if (!force_silent)
                    error;
                ch.status = CH_FAILED;
            };
        };
    };
    if (verbosity != V_off)
    {
        if (ch.status == CH_SUCCEEDED & !mode_changed(fts., file, file_full_name, ch, ch))
            ch.status = CH_NO_CHANGE_REQUESTED;
        if (ch.status == CH_SUCCEEDED | verbosity == V_high)
            describe_change(file_full_name, @ch);
    };
    if (CH_NO_CHANGE_REQUESTED <= ch.status & diagnose_surprises)
    {
        if (ch . new_mode & ~ naively_expected_mode)
        {
            byte[12] new_perms = 12;
            byte[12] naively_expected_perms = 12;
            strmode(ch, new_perms);
            strmode;
            new_perms[10] = naively_expected_perms[10] = '\0';
            error(0, 0, gettext("%s: new permissions are %s, not %s"), quotearg_n_style_colon, new_perms + 1, naively_expected_perms + 1);
            ch.status = CH_FAILED;
        };
    };
    if (!recurse)
        fts_set;
    return CH_NOT_APPLIED <= ch.status;
};

cdecl process_files(byte** files, int bit_flags) -> int
{
    bool;
    while (true)
    {
        if (ent == NULL)
        {
            if (errno != 0)
            {
                if (!force_silent)
                    error;
            };
            break;
        };
    };
    if (fts_close != 0)
    {
        error;
    };
};

cdecl usage(int status) -> void
{
    if (status != EXIT_SUCCESS)
        do
        {
            fprintf;
        }
        while (0);
    else
    {
        printf;
        fputs;
        oputs_("chmod", gettext("\
  -c, --changes\n\
         like verbose but report only when a change is made\n\
"));
        oputs_("chmod", gettext("\
  -f, --silent, --quiet\n\
         suppress most error messages\n\
"));
        oputs_("chmod", gettext("\
  -v, --verbose\n\
         output a diagnostic for every file processed\n\
"));
        oputs_("chmod", gettext("\
      --dereference\n\
         affect the referent of each symbolic link,\n\
         rather than the symbolic link itself\n\
"));
        oputs_("chmod", gettext("\
  -h, --no-dereference\n\
         affect each symbolic link, rather than the referent\n\
"));
        oputs_("chmod", gettext("\
      --no-preserve-root\n\
         do not treat '/' specially (the default)\n\
"));
        oputs_("chmod", gettext("\
      --preserve-root\n\
         fail to operate recursively on '/'\n\
"));
        oputs_("chmod", gettext("\
      --reference=RFILE\n\
         use RFILE's mode instead of specifying MODE values.\n\
         RFILE is always dereferenced if a symbolic link.\n\
"));
        oputs_("chmod", gettext("\
  -R, --recursive\n\
         change files and directories recursively\n\
"));
        emit_symlink_recurse_options_("chmod", "-H");
        oputs_("chmod", gettext("      --help\n         display this help and exit\n"));
        oputs_("chmod", gettext("      --version\n         output version information and exit\n"));
        fputs;
        emit_ancillary_info("chmod");
    };
    exit(status);
};

cdecl main(int argc, byte** argv) -> int
{
    byte* mode;
    bool;
    bool;
    byte* reference_file;
    int c;
    int bit_flags;
    set_program_name(argv[0]);
    setlocale;
    atexit;
    while ((c = getopt_long) != -1)
    {
    };
    if (recurse)
    {
        if (bit_flags == FTS_PHYSICAL)
        {
            if (dereference == 1)
                error;
            dereference = 0;
        };
    };
    if (dereference == - 1 && bit_flags == FTS_LOGICAL)
        dereference = 1;
    if (reference_file)
    {
        if (mode)
        {
            error(0, 0, gettext("cannot combine mode and --reference options"));
            usage;
        };
    }
    else
    {
    };
    if (optind >= argc)
    {
        if (! mode || mode != argv [ optind - 1 ])
            error(0, 0, gettext("missing operand"));
        else
            error(0, 0, gettext("missing operand after %s"), quote(argv[argc - 1]));
        usage;
    };
    if (reference_file)
    {
        change = mode_create_from_ref(reference_file);
        if (!change)
            error;
    }
    else
    {
        change = mode_compile(mode);
        if (!change)
        {
            error(0, 0, gettext("invalid mode: %s"), quote(mode));
            usage;
        };
        umask_value = umask(0);
    };
    if (recurse && preserve_root)
    {
        dev_ino dev_ino_buf;
        root_dev_ino = get_root_dev_ino(@dev_ino_buf);
        if (root_dev_ino == NULL)
            error;
    }
    else
    {
    };
};
