// Auto-generated by cft from: chown-core.c
// May require manual edits.

///
 chown-core.c -- core functions for changing ownership.
   Copyright (C) 2000-2026 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
///

///
 Extracted from chown.c/chgrp.c and librarified by Jim Meyering.
///

macro FTSENT_IS_DIRECTORY(E)
{
    ( ( E ) -> fts_info == FTS_D || ( E ) -> fts_info == FTS_DC || ( E ) -> fts_info == FTS_DP || ( E ) -> fts_info == FTS_DNR )
};

enum RCH_status
{
    RC_ok = 2,
    RC_excluded = 3,
    RC_inode_changed = 4,
    RC_do_ordinary_chown = 5,
    RC_error = 6
};

cdecl chopt_init(Chown_option* chopt) -> void
{
    chopt.verbosity = V_off;
};

cdecl chopt_free(Chown_option* chopt) -> void
{
    free(chopt.user_name);
    free(chopt.group_name);
};

cdecl uid_to_str(int uid) -> byte*
{
    void* /* untranslated: char[<recovery-expr>(INT_BUFSIZE_BOUND)] */ buf = INT_BUFSIZE_BOUND;
    return xstrdup(TYPE_SIGNED ? imaxtostr(uid, buf) : umaxtostr(uid, buf));
};

cdecl gid_to_str(int gid) -> byte*
{
    void* /* untranslated: char[<recovery-expr>(INT_BUFSIZE_BOUND)] */ buf = INT_BUFSIZE_BOUND;
    return xstrdup(TYPE_SIGNED ? imaxtostr(gid, buf) : umaxtostr(gid, buf));
};

cdecl gid_to_name(int gid) -> byte*
{
    group* grp = getgrgid(gid);
    return grp ? xstrdup(grp) : gid_to_str(gid);
};

cdecl uid_to_name(int uid) -> byte*
{
    passwd* pwd = getpwuid(uid);
    return pwd ? xstrdup(pwd) : uid_to_str(uid);
};

cdecl user_group_str(byte* user, byte* group) -> byte*
{
    byte* spec;
    if (user)
    {
        if (group)
        {
            spec = xmalloc(strlen(user) + 1 + strlen(group) + 1);
            stpcpy(stpcpy(stpcpy(spec, user), ":"), group);
        }
        else
        {
            spec = xstrdup(user);
        };
    }
    elif (group)
    {
        spec = xstrdup(group);
    };
    return spec;
};

cdecl describe_change(byte* file, Change_status changed, byte* old_user, byte* old_group, byte* user, byte* group) -> void
{
    if (changed == CH_NOT_APPLIED)
    {
        printf(gettext("neither symbolic link %s nor referent has been changed\n"), quotearg_style);
        return void;
    };
    byte* spec = user_group_str(user, group);
    byte* old_spec = user_group_str;
    byte* fmt;
    switch (changed)
    {
        case (CH_SUCCEEDED)
        {
            fmt = (user ? gettext("changed ownership of %s from %s to %s\n") : group ? gettext("changed group of %s from %s to %s\n") : gettext("no change to ownership of %s\n"));
            break switch;
        }
        case (CH_FAILED)
        {
            if (old_spec)
            {
                fmt = (user ? gettext("failed to change ownership of %s from %s to %s\n") : group ? gettext("failed to change group of %s from %s to %s\n") : gettext("failed to change ownership of %s\n"));
            }
            else
            {
                fmt = (user ? gettext("failed to change ownership of %s to %s\n") : group ? gettext("failed to change group of %s to %s\n") : gettext("failed to change ownership of %s\n"));
                free(old_spec);
                old_spec = spec;
            };
            break switch;
        }
        case (CH_NO_CHANGE_REQUESTED)
        {
            fmt = (user ? gettext("ownership of %s retained as %s\n") : group ? gettext("group of %s retained as %s\n") : gettext("ownership of %s retained\n"));
            break switch;
        }
        case (CH_NOT_APPLIED)
        {
        }
    };
    printf(fmt, quotearg_style, old_spec, spec);
    free(old_spec);
    free(spec);
};

cdecl restricted_chown(int cwd_fd, byte* file, stat* orig_st, int uid, int gid, int required_uid, int required_gid) -> RCH_status
{
    if (required_uid == ( uid_t ) - 1 && required_gid == ( gid_t ) - 1)
        return RC_do_ordinary_chown;
    int open_flags;
    if (!S_ISREG(orig_st))
    {
        if (S_ISDIR(orig_st))
        else
            return RC_do_ordinary_chown;
    };
    int fd = openat;
    RCH_status status = RC_ok;
    stat st;
    if (fstat(fd, @st) != 0)
        status = RC_error;
    elif (!psame_inode(orig_st, @st))
        status = RC_inode_changed;
    else
        if (( required_uid == ( uid_t ) - 1 || required_uid == st . st_uid ) && ( required_gid == ( gid_t ) - 1 || required_gid == st . st_gid ))
        {
            status = RC_error;
        };
    int saved_errno;
    close(fd);
    return status;
};

cdecl change_file_owner(int* fts, int* ent, int uid, int gid, int required_uid, int required_gid, Chown_option* chopt) -> int
{
    byte* file_full_name = ent.;
    byte* file = ent.;
    bool;
    switch (ent.)
    {
        if (chopt)
        {
            if (ROOT_DEV_INO_CHECK(chopt.root_dev_ino, ent.))
            {
                ROOT_DEV_INO_WARN(file_full_name);
                fts_set;
                ignore_value(fts_read(fts));
            };
        };
        if (ent -> fts_level == FTS_ROOTLEVEL && ent -> fts_number == 0)
        {
            ent. = 1;
            fts_set;
        };
        if (!chopt)
            error(0, ent., gettext("cannot access %s"), quotearg_style);
        if (!chopt)
            error(0, ent., "%s", quotearg_n_style_colon);
        if (!chopt)
            error(0, ent., gettext("cannot read directory %s"), quotearg_style);
        if (cycle_warning_required(fts, ent))
        {
            do
            {
                error(0, 0, gettext("\
WARNING: Circular directory structure.\n\
This almost certainly means that you have a corrupted file system.\n\
NOTIFY YOUR SYSTEM MANAGER.\n\
The following directory is part of the cycle:\n  %s\n"), quotearg_n_style_colon);
            }
            while (0);
        };
        default
        {
        };
    };
    bool;
    stat stat_buf;
    stat* file_stats;
    if (! ok)
    {
    }
    elif (required_uid == ( uid_t ) - 1 && required_gid == ( gid_t ) - 1 && chopt -> verbosity == V_off && ! chopt -> root_dev_ino && ! chopt -> affect_symlink_referent)
    {
        file_stats = ent.;
    };
    else
    {
        file_stats = ent.;
        if (chopt & S_ISLNK(file_stats))
        {
            if (fstatat(fts., file, @stat_buf, 0) != 0)
            {
                if (!chopt)
                    error;
            };
            file_stats = @stat_buf;
        };
    };
    if (ok && FTSENT_IS_DIRECTORY ( ent ) && ROOT_DEV_INO_CHECK ( chopt -> root_dev_ino , file_stats ))
    {
        ROOT_DEV_INO_WARN(file_full_name);
    };
    bool;
    if (do_chown)
    {
        if (!chopt)
        {
            if (! ok && is_ENOTSUP ( errno ))
            {
            };
        }
        else
        {
            RCH_status err = restricted_chown(fts., file, file_stats, uid, gid, required_uid, required_gid);
            switch (err)
            {
                case (RC_ok)
                {
                }
                case (RC_do_ordinary_chown)
                {
                    break switch;
                }
                case (RC_error)
                {
                    break switch;
                }
                case (RC_inode_changed)
                {
                    break switch;
                }
                default
                {
                };
            };
        };
        if (do_chown && ! ok && ! chopt -> force_silent)
            error;
    };
    if (chopt.verbosity != V_off)
    {
        bool;
        if (changed || chopt -> verbosity == V_high)
        {
            Change_status ch_status;
            byte* old_usr;
            byte* old_grp;
            byte* new_usr;
            byte* new_grp;
            describe_change(file_full_name, ch_status, old_usr, old_grp, new_usr, new_grp);
            free(old_usr);
            free(old_grp);
            if (new_usr != chopt.user_name)
                free(new_usr);
            if (new_grp != chopt.group_name)
                free(new_grp);
        };
    };
    if (!chopt)
        fts_set;
};

cdecl chown_files(byte** files, int bit_flags, int uid, int gid, int required_uid, int required_gid, Chown_option* chopt) -> int
{
    bool;
    int stat_flags;
    while (true)
    {
        if (ent == NULL)
        {
            if (errno != 0)
            {
                if (!chopt)
                    error;
            };
            break;
        };
    };
    if (fts_close != 0)
    {
        error;
    };
};
