// Auto-generated by cft from: cksum_pclmul.c
// May require manual edits.

///
 cksum_crc -- calculate and print POSIX checksums and sizes of files
   Copyright (C) 2021-2026 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
///

macro BUFLEN
{
    ( 1 << 16 )
};

cdecl cksum_pclmul(int* fp, int* crc_out, int* length_out) -> int
{
    ulong bytes_read;
    while ((bytes_read = fread) > 0)
    {
        if (ckd_add)
        {
        };
        if (bytes_read >= 16 * 8)
        {
            while (bytes_read >= 16 * 8)
            {
                bytes_read -= (16 * 4);
            };
            _mm_storeu_si128;
            _mm_storeu_si128;
            _mm_storeu_si128;
            _mm_storeu_si128;
        };
        if (bytes_read >= 32)
        {
            while (bytes_read >= 32)
            {
                bytes_read -= 16;
            };
            _mm_storeu_si128;
        };
        byte* cp;
        if (feof(fp))
            break;
    };
    return !ferror(fp);
};
