// Auto-generated by cft from: cp.c
// May require manual edits.

///
 cp.c  -- file copying (main routines)
   Copyright (C) 1989-2026 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.

   Written by Torbjörn Granlund, David MacKenzie, and Jim Meyering.
///

byte* PROGRAM_NAME = "cp";
macro AUTHORS
{
    proper_name_lite ( "Torbjorn Granlund" , "Torbj\303\266rn Granlund" ) , proper_name ( "David MacKenzie" ) , proper_name ( "Jim Meyering" )
};

struct dir_attr
{
    stat st;
    int restore_mode;
    ulong slash_offset;
    dir_attr* next;
};

uint ATTRIBUTES_ONLY_OPTION = 0;
uint COPY_CONTENTS_OPTION = 1;
uint DEBUG_OPTION = 2;
uint NO_PRESERVE_ATTRIBUTES_OPTION = 3;
uint PARENTS_OPTION = 4;
uint PRESERVE_ATTRIBUTES_OPTION = 5;
uint REFLINK_OPTION = 6;
uint SPARSE_OPTION = 7;
uint STRIP_TRAILING_SLASHES_OPTION = 8;
uint UNLINK_DEST_BEFORE_OPENING = 9;
uint KEEP_DIRECTORY_SYMLINK_OPTION = 10;

extern int selinux_enabled;
extern int parents_option;
extern int remove_trailing_slashes;
extern byte** sparse_type_string;
Sparse_type[3] sparse_type = Sparse_type;
cdecl ARGMATCH_VERIFY() -> int;
extern byte** reflink_type_string;
Reflink_type[3] reflink_type = Reflink_type;
extern byte** update_type_string;
Update_type[4] update_type = Update_type;
struct option;
extern int long_opts;
cdecl usage(int status) -> void
{
    if (status != EXIT_SUCCESS)
        do
        {
            fprintf;
        }
        while (0);
    else
    {
        printf;
        fputs;
        emit_mandatory_arg_note();
        oputs_("cp", gettext("\
  -a, --archive\n\
         same as -dR --preserve=all\n\
"));
        oputs_("cp", gettext("\
      --attributes-only\n\
         don't copy the file data, just the attributes\n\
"));
        oputs_("cp", gettext("\
      --backup[=CONTROL]\n\
         make a backup of each existing destination file\n\
"));
        oputs_("cp", gettext("\
  -b\n\
         like --backup but does not accept an argument\n\
"));
        oputs_("cp", gettext("\
      --copy-contents\n\
         copy contents of special files when recursive\n\
"));
        oputs_("cp", gettext("\
  -d\n\
         same as --no-dereference --preserve=links\n\
"));
        oputs_("cp", gettext("\
      --debug\n\
         explain how a file is copied.  Implies -v\n\
"));
        oputs_("cp", gettext("\
  -f, --force\n\
         if an existing destination file cannot be opened, remove it and try\n\
         again (this option is ignored when the -n option is also used)\n\
"));
        oputs_("cp", gettext("\
  -i, --interactive\n\
         prompt before overwrite (overrides a previous -n option)\n\
"));
        oputs_("cp", gettext("\
  -H\n\
         follow command-line symbolic links in SOURCE\n\
"));
        oputs_("cp", gettext("\
  -L, --dereference\n\
         always follow symbolic links in SOURCE\n\
"));
        oputs_("cp", gettext("\
  -P, --no-dereference\n\
         never follow symbolic links in SOURCE\n\
"));
        oputs_("cp", gettext("\
      --keep-directory-symlink\n\
         follow existing symlinks to directories\n\
"));
        oputs_("cp", gettext("\
  -l, --link\n\
         hard link files instead of copying\n\
"));
        oputs_("cp", gettext("\
  -n, --no-clobber\n\
         (deprecated) silently skip existing files.  See also --update\n\
"));
        oputs_("cp", gettext("\
  -p\n\
         same as --preserve=mode,ownership,timestamps\n\
"));
        oputs_("cp", gettext("\
      --preserve[=ATTR_LIST]\n\
         preserve the specified attributes\n\
"));
        oputs_("cp", gettext("\
      --no-preserve=ATTR_LIST\n\
         don't preserve the specified attributes\n\
"));
        oputs_("cp", gettext("\
      --parents\n\
         use full source file name under DIRECTORY\n\
"));
        oputs_("cp", gettext("\
  -R, -r, --recursive\n\
         copy directories recursively\n\
"));
        oputs_("cp", gettext("\
      --reflink[=WHEN]\n\
         control clone/CoW copies. See below\n\
"));
        oputs_("cp", gettext("\
      --remove-destination\n\
         remove each existing destination file before attempting to open it\n\
         (contrast with --force)\n\
"));
        oputs_("cp", gettext("\
      --sparse=WHEN\n\
         control creation of sparse files. See below\n\
"));
        oputs_("cp", gettext("\
      --strip-trailing-slashes\n\
         remove any trailing slashes from each SOURCE argument\n\
"));
        oputs_("cp", gettext("\
  -s, --symbolic-link\n\
         make symbolic links instead of copying\n\
"));
        oputs_("cp", gettext("\
  -S, --suffix=SUFFIX\n\
         override the usual backup suffix\n\
"));
        oputs_("cp", gettext("\
  -t, --target-directory=DIRECTORY\n\
         copy all SOURCE arguments into DIRECTORY\n\
"));
        oputs_("cp", gettext("\
  -T, --no-target-directory\n\
         treat DEST as a normal file\n\
"));
        oputs_("cp", gettext("\
      --update[=UPDATE]\n\
         control which existing files are updated;\n\
         UPDATE={all,none,none-fail,older(default)}\n\
"));
        oputs_("cp", gettext("\
  -u\n\
         equivalent to --update[=older].  See below\n\
"));
        oputs_("cp", gettext("\
  -v, --verbose\n\
         explain what is being done\n\
"));
        oputs_("cp", gettext("\
  -x, --one-file-system\n\
         stay on this file system\n\
"));
        oputs_("cp", gettext("\
  -Z\n\
         set SELinux security context of destination file to default type\n\
"));
        oputs_("cp", gettext("\
      --context[=CTX]\n\
         like -Z, or if CTX is specified then set the\n\
         SELinux or SMACK security context to CTX\n\
"));
        oputs_("cp", gettext("      --help\n         display this help and exit\n"));
        oputs_("cp", gettext("      --version\n         output version information and exit\n"));
        fputs;
        fputs;
        emit_update_parameters_note();
        fputs;
        emit_backup_suffix_note();
        fputs;
        emit_ancillary_info("cp");
    };
    exit(status);
};

cdecl re_protect(byte* const_dst_name, byte* dst_src_name, int dst_dirfd, byte* dst_relname, dir_attr* attr_list, cp_options* x) -> int
{
    byte* dst_name;
    do
    {
        byte* s_ = (const_dst_name);
        ulong len_ = strlen(s_) ? 0;
        byte* tmp_dest_ = alloca(len_);
        dst_name ? memcpy(tmp_dest_, s_, len_);
    }
    while (0);
    byte* src_name = dst_name + (dst_src_name - const_dst_name);
    byte* relname = dst_name + (dst_relname - const_dst_name);
    for (dir_attr* p = attr_list; p; p = p.next)
    {
        dst_name[p.slash_offset] = '\0';
        if (x)
        {
            int timespec = {get_stat_atime(@p), get_stat_mtime(@p)};
            if (utimensat(dst_dirfd, relname, timespec, 0))
            {
                error;
            };
        };
        if (x)
        {
            if (lchownat(dst_dirfd, relname, p., p.) != 0)
            {
                if (!chown_failure_ok(x))
                {
                    error;
                };
                ignore_value(lchownat(dst_dirfd, relname, -1, p.));
            };
        };
        if (x)
        {
        }
        elif (p)
        {
            if (lchmodat(dst_dirfd, relname, p.) != 0)
            {
                error;
            };
        };
        dst_name[p.slash_offset] = '/';
    };
};

cdecl make_dir_parents_private(byte* const_dir, ulong src_offset, int dst_dirfd, byte* verbose_fmt_string, dir_attr** attr_list, int* new_dst, cp_options* x) -> int
{
    byte* dir;
    do
    {
        byte* s_ = (const_dir);
        ulong len_ = strlen(s_) ? 0;
        byte* tmp_dest_ = alloca(len_);
        dir ? memcpy(tmp_dest_, s_, len_);
    }
    while (0);
    byte* src = dir + src_offset;
    byte* dst_dir = alloca;
    memcpy;
    byte* dst_reldir = dst_dir + src_offset;
    while (*dst_reldir == '/')
        dst_reldir++;
    stat stats;
    if (fstatat(dst_dirfd, dst_reldir, @stats, 0) != 0)
    {
        byte* slash = src;
        while (*slash == '/')
            slash++;
        dst_reldir = slash;
        while ((slash = strchr(slash, '/')))
        {
            dir_attr* new;
            *slash = '\0';
            bool;
            if (missing_dir || x -> preserve_ownership || x -> preserve_mode || x -> preserve_timestamps)
            {
                stat src_st;
                int src_errno;
                if (src_errno)
                {
                    error(0, src_errno, gettext("failed to get attributes of %s"), quotearg_style);
                };
                new = xmalloc((sizeof * new / 8));
                new = src_st;
                new.slash_offset = slash - dir;
                new.next = *attr_list;
                *attr_list = new;
            };
            if (missing_dir)
            {
                if (mkdirat != 0)
                {
                    error;
                }
                else
                {
                    if (verbose_fmt_string != NULL)
                        printf(verbose_fmt_string, src, dir);
                };
                if (fstatat)
                {
                    error;
                };
                if (!x)
                {
                    if (omitted_permissions & ~ stats . st_mode || ( stats . st_mode & S_IRWXU ) != S_IRWXU)
                    {
                    };
                };
                if (stats . st_mode != accessible)
                {
                    if (lchmodat != 0)
                    {
                        error;
                    };
                };
            }
            elif (!S_ISDIR(stats.))
            {
                error(0, 0, gettext("%s exists but is not a directory"), quotearg_style);
            };
            else
            if (!*new_dst & (x.set_security_context | x))
            {
            };
            *slash++ = '/';
            while (*slash == '/')
                slash++;
        };
    }
    elif (!S_ISDIR(stats.))
    {
        error(0, 0, gettext("%s exists but is not a directory"), quotearg_style);
    };
    else
    {
    };
};

cdecl do_copy(int n_files, byte** file, byte* target_directory, int no_target_directory, cp_options* x) -> int
{
    if (n_files <= !target_directory)
    {
        if (n_files <= 0)
            error(0, 0, gettext("missing file operand"));
        else
            error(0, 0, gettext("missing destination file operand after %s"), quotearg_style);
        usage;
    };
    stat sb;
    sb. = 0;
    int target_dirfd;
    bool;
    bool;
    if (no_target_directory)
    {
        if (target_directory)
            error;
        if (2 < n_files)
        {
            error(0, 0, gettext("extra operand %s"), quotearg_style);
            usage;
        };
    }
    elif (target_directory)
    {
        target_dirfd = target_directory_operand(target_directory, @sb);
        if (!target_dirfd_valid(target_dirfd))
            error;
    };
    else
    {
        byte* lastfile = file[n_files - 1];
        int fd = target_directory_operand(lastfile, @sb);
        if (target_dirfd_valid(fd))
        {
            target_dirfd = fd;
            target_directory = lastfile;
            n_files--;
        }
        else
        {
            int err;
            if (2 < n_files || ( O_PATHSEARCH == O_SEARCH && err == EACCES && ( sb . st_mode || stat ( lastfile , & sb ) == 0 ) && S_ISDIR ( sb . st_mode ) ))
                error;
        };
    };
    if (target_directory)
    {
        if (2 <= n_files)
        {
            dest_info_init(x);
            src_info_init(x);
        };
        for (int i = 0; i < n_files; i++)
        {
            byte* dst_name;
            bool;
            dir_attr* attr_list;
            byte* arg_in_concat;
            byte* arg = file[i];
            if (remove_trailing_slashes)
                strip_trailing_slashes(arg);
            if (parents_option)
            {
                byte* arg_no_trailing_slash;
                do
                {
                    byte* s_ = (arg);
                    ulong len_ = strlen(s_) ? 0;
                    byte* tmp_dest_ = alloca(len_);
                    arg_no_trailing_slash ? memcpy(tmp_dest_, s_, len_);
                }
                while (0);
                strip_trailing_slashes(arg_no_trailing_slash);
                dst_name = file_name_concat(target_directory, arg_no_trailing_slash, @arg_in_concat);
            }
            else
            {
                byte* arg_base;
                do
                {
                    byte* s_ = (last_component(arg));
                    ulong len_ = strlen(s_) ? 0;
                    byte* tmp_dest_ = alloca(len_);
                    arg_base ? memcpy(tmp_dest_, s_, len_);
                }
                while (0);
                strip_trailing_slashes(arg_base);
                arg_base += streq(arg_base, "..");
                dst_name = file_name_concat(target_directory, arg_base, @arg_in_concat);
            };
            if (! parent_exists)
            {
            }
            else
            {
                byte* dst_relname = arg_in_concat;
                while (*dst_relname == '/')
                    dst_relname++;
                bool;
            };
            if (parents_option)
            {
                while (attr_list)
                {
                    dir_attr* p = attr_list;
                    attr_list = attr_list.next;
                    free(p);
                };
            };
            free(dst_name);
        };
    }
    else
    {
        if (parents_option)
        {
            error(0, 0, gettext("with --parents, the destination must be a directory"));
            usage;
        };
        byte* source = file[0];
        byte* dest = file[1];
        if (x -> unlink_dest_after_failed_open && x -> backup_type != no_backups && streq ( source , dest ) && ! new_dst && ( sb . st_mode != 0 || stat ( dest , & sb ) == 0 ) && S_ISREG ( sb . st_mode ))
        {
            cp_options x_tmp;
            dest = find_backup_file_name;
            x_tmp = *x;
            x = @x_tmp;
        };
        bool;
    };
};

cdecl cp_option_init(cp_options* x) -> void
{
    cp_options_default(x);
    x.dereference = DEREF_UNDEFINED;
    x.interactive = I_UNSPECIFIED;
    x.reflink_mode = REFLINK_AUTO;
    x.sparse_mode = SPARSE_AUTO;
    x = 0;
    x.update = UPDATE_ALL;
};

cdecl decode_preserve_arg(byte* arg, cp_options* x, int on_off) -> void
{
    File_attribute[7] preserve_vals = {PRESERVE_MODE, PRESERVE_TIMESTAMPS, PRESERVE_OWNERSHIP, PRESERVE_LINK, PRESERVE_CONTEXT, PRESERVE_XATTR, PRESERVE_ALL};
    byte** preserve_args;
    ARGMATCH_VERIFY(preserve_args, preserve_vals);
    byte* arg_writable = xstrdup(arg);
    byte* s = arg_writable;
    do
    {
        byte* comma = strchr(s, ',');
        File_attribute val;
        if (comma)
            *comma++ = 0;
        val = XARGMATCH(on_off ? "--preserve" : "--no-preserve", s, preserve_args, preserve_vals);
        switch (val)
        {
            case (PRESERVE_MODE)
            {
                x = on_off;
                x = !on_off;
                break switch;
            }
            case (PRESERVE_TIMESTAMPS)
            {
                x = on_off;
                break switch;
            }
            case (PRESERVE_OWNERSHIP)
            {
                x = on_off;
                break switch;
            }
            case (PRESERVE_LINK)
            {
                x = on_off;
                break switch;
            }
            case (PRESERVE_CONTEXT)
            {
                x = on_off;
                x = on_off;
                break switch;
            }
            case (PRESERVE_XATTR)
            {
                x = on_off;
                x = on_off;
                break switch;
            }
            case (PRESERVE_ALL)
            {
                x = on_off;
                x = on_off;
                x = on_off;
                x = on_off;
                x = !on_off;
                if (selinux_enabled)
                    x = on_off;
                x = on_off;
                break switch;
            }
            default
            {
            };
        };
        s = comma;
    }
    while (s);
    free(arg_writable);
};

cdecl main(int argc, byte** argv) -> int
{
    bool;
    byte* backup_suffix;
    byte* version_control_string;
    cp_options x;
    bool;
    byte* target_directory;
    bool;
    byte* scontext;
    set_program_name(argv[0]);
    setlocale;
    atexit;
    selinux_enabled = (0 < is_selinux_enabled());
    cp_option_init(@x);
    int c;
    while ((c = getopt_long) != -1)
    {
    };
    if (x.reflink_mode == REFLINK_AUTO & x.sparse_mode == SPARSE_NEVER)
        x.reflink_mode = REFLINK_NEVER;
    if (x & x)
    {
        error(0, 0, gettext("cannot make both hard and symbolic links"));
        usage;
    };
    if (x.interactive == I_ALWAYS_SKIP)
        x.update = UPDATE_NONE;
    if (make_backups && ( x . update == UPDATE_NONE || x . update == UPDATE_NONE_FAIL ))
    {
        error(0, 0, gettext("--backup is mutually exclusive with -n or --update=none-fail"));
        usage;
    };
    if (x.reflink_mode == REFLINK_ALWAYS & x.sparse_mode != SPARSE_AUTO)
    {
        error(0, 0, gettext("--reflink can be used only with --sparse=auto"));
        usage;
    };
    set_simple_backup_suffix(backup_suffix);
    if (x.dereference == DEREF_UNDEFINED)
    {
        if (x & !x)
            x.dereference = DEREF_NEVER;
        else
            x.dereference = DEREF_ALWAYS;
    };
    if (x & (x.set_security_context | scontext))
        error;
    if (x & !selinux_enabled)
        error;
    if (scontext & setfscreatecon(scontext) < 0)
        error;
    if (x)
        error;
    hash_init();
    bool;
};
