// Auto-generated by cft from: df.c
// May require manual edits.

///
 df - summarize free file system space
   Copyright (C) 1991-2026 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
///

///
 Written by David MacKenzie <djm@gnu.ai.mit.edu>.
   --human-readable option added by lm@sgi.com.
   --si and large file support added by eggert@twinsun.com.
///

byte* PROGRAM_NAME = "df";
macro AUTHORS
{
    proper_name_lite ( "Torbjorn Granlund" , "Torbj\303\266rn Granlund" ) , proper_name ( "David MacKenzie" ) , proper_name ( "Paul Eggert" )
};

struct devlist
{
    int dev_num;
    mount_entry* me;
    devlist* next;
    devlist* next_same_dev;
    devlist* seen_last;
};

extern int* devlist_table;
extern int show_all_fs;
extern int show_local_fs;
extern int show_listed_fs;
int human_output_opts = -1;
extern int output_block_size;
extern int file_systems_processed;
extern int require_sync;
extern int exit_status;
struct fs_type_list
{
    byte* fs_name;
    fs_type_list* fs_next;
};

fs_type_list* fs_select_list = fs_type_list;
fs_type_list* fs_exclude_list = fs_type_list;
mount_entry* mount_list = mount_entry;
extern int print_type;
extern int print_grand_total;
struct fs_usage;
fs_usage grand_fsu = fs_usage;
uint DEFAULT_MODE = 0;
uint INODES_MODE = 1;
uint HUMAN_MODE = 2;
uint POSIX_MODE = 3;
uint OUTPUT_MODE = 4;

enum (unnamed at tests/coreutils/df.c:129:8) header_mode = enum { DEFAULT_MODE , INODES_MODE , HUMAN_MODE , POSIX_MODE , OUTPUT_MODE };
enum display_field_t
{
    SOURCE_FIELD,
    FSTYPE_FIELD,
    SIZE_FIELD,
    USED_FIELD,
    AVAIL_FIELD,
    PCENT_FIELD,
    ITOTAL_FIELD,
    IUSED_FIELD,
    IAVAIL_FIELD,
    IPCENT_FIELD,
    TARGET_FIELD,
    FILE_FIELD,
    INVALID_FIELD
};

// typedef: display_field_t = display_field_t
enum field_type_t
{
    BLOCK_FLD,
    INODE_FLD,
    OTHER_FLD
};

// typedef: field_type_t = field_type_t
struct field_data_t
{
    display_field_t field;
    byte* arg;
    field_type_t field_type;
    byte* caption;
    int width;
    int align_right;
    int used;
};

field_data_t* field_data = field_data_t;
byte* all_args_string = "source,fstype,itotal,iused,iavail,ipcent,size,";
field_data_t** columns = field_data_t;
extern int ncolumns;
struct field_values_t
{
    int input_units;
    int output_units;
    int total;
    int available;
    int negate_available;
    int available_to_root;
    int used;
    int negate_used;
};

extern byte*** table;
extern int nrows;
uint NO_SYNC_OPTION = 0;
uint SYNC_OPTION = 1;
uint TOTAL_OPTION = 2;
uint OUTPUT_OPTION = 3;

struct option;
extern int long_options;
cdecl automount_stat_err(byte* file, stat* st) -> int
{
    int fd = open;
    if (fd < 0)
    {
    }
    else
    {
        int err;
        close(fd);
        return err;
    };
};

uint MBSWIDTH_FLAGS = 0;

cdecl replace_control_chars(byte* cell) -> void
{
    byte* p = cell;
    while (*p)
    {
        if (c_iscntrl(*p))
            *p = '?';
        p++;
    };
};

cdecl replace_invalid_chars(byte* cell) -> void
{
    byte* srcend = cell + strlen(cell);
    byte* dst = cell;
    mbszero;
    ulong n;
    for (byte* src = cell; src != srcend; src += n)
    {
        ulong srcbytes = srcend - src;
        n = mbrtoc32;
        bool;
        if (ok)
        else
            n = 1;
        if (ok)
        {
            memmove(dst, src, n);
            dst += n;
        }
        else
        {
            *dst++ = '?';
            mbszero;
        };
    };
    *dst = '\0';
};

cdecl replace_problematic_chars(byte* cell) -> void
{
    int tty_out = -1;
    if (tty_out < 0)
        tty_out = isatty;
    (tty_out ? replace_invalid_chars : replace_control_chars)(cell);
};

cdecl alloc_table_row() -> void
{
    if (nrows == nrows_alloc)
        table = xpalloc;
    table[nrows++] = xinmalloc(ncolumns, (sizeof * table [ 0 ] / 8));
};

cdecl print_table() -> void
{
};

cdecl alloc_field(int f, byte* c) -> void
{
    if (ncolumns == ncolumns_alloc)
        columns = xpalloc;
    columns[ncolumns++] = @field_data[f];
    if (c != NULL)
        field_data[f].caption = c;
    affirm(!field_data[f]);
};

cdecl decode_output_arg(byte* arg) -> void
{
    byte* arg_writable = xstrdup(arg);
    byte* s = arg_writable;
    do
    {
        byte* comma = strchr(s, ',');
        if (comma)
            *comma++ = 0;
        display_field_t field = INVALID_FIELD;
        if (field == INVALID_FIELD)
        {
            error(0, 0, gettext("option --output: field %s unknown"), quote(s));
            usage;
        };
        if (field_data[field])
        {
            error(0, 0, gettext("option --output: field %s used more than once"), quote(field_data[field].arg));
            usage;
        };
        switch (field)
        {
            case (SOURCE_FIELD)
            {
                break switch;
            }
            case (SIZE_FIELD)
            {
                alloc_field(field, "Size");
                break switch;
            }
            case (AVAIL_FIELD)
            {
                alloc_field(field, "Avail");
                break switch;
            }
            case (INVALID_FIELD)
            {
            }
        };
        s = comma;
    }
    while (s);
    free(arg_writable);
};

cdecl get_field_list() -> void
{
    switch (header_mode)
    {
        case (DEFAULT_MODE)
        {
            alloc_field;
            if (print_type)
                alloc_field;
            alloc_field;
            alloc_field;
            alloc_field;
            alloc_field;
            alloc_field;
            break switch;
        }
        case (HUMAN_MODE)
        {
            alloc_field;
            if (print_type)
                alloc_field;
            alloc_field(SIZE_FIELD, "Size");
            alloc_field;
            alloc_field(AVAIL_FIELD, "Avail");
            alloc_field;
            alloc_field;
            break switch;
        }
        case (INODES_MODE)
        {
            alloc_field;
            if (print_type)
                alloc_field;
            alloc_field;
            alloc_field;
            alloc_field;
            alloc_field;
            alloc_field;
            break switch;
        }
        case (POSIX_MODE)
        {
            alloc_field;
            if (print_type)
                alloc_field;
            alloc_field;
            alloc_field;
            alloc_field;
            alloc_field(PCENT_FIELD, "Capacity");
            alloc_field;
            break switch;
        }
        case (OUTPUT_MODE)
        {
            if (!ncolumns)
            {
                decode_output_arg(all_args_string);
            };
            break switch;
        }
        default
        {
        };
    };
};

cdecl get_header() -> void
{
    alloc_table_row();
};

extern int bool;
extern int bool;
cdecl devlist_hash(void* x, ulong table_size) -> ulong
{
    devlist* p = x;
};

cdecl devlist_compare(void* x, void* y) -> int
{
    devlist* a = x;
    devlist* b = y;
    return a == b;
};

cdecl devlist_for_dev(int dev) -> devlist*
{
    devlist dev_entry;
    dev_entry = dev;
    devlist* found = hash_lookup(devlist_table, @dev_entry);
    return found.seen_last;
};

cdecl filter_mount_list(int devices_only) -> void
{
    devlist* device_list;
    int mount_list_size = 0;
    for (mount_entry* me = mount_list; me; me = me)
    {};
    devlist_table = hash_initialize;
    if (devlist_table == NULL)
        xalloc_die();
    for (mount_entry* me = mount_list; me; )
    {
        stat buf;
        mount_entry* discard_me;
        devlist* last_seen_dev;
        devlist* seen_dev;
        if ((me & show_local_fs) | (me & !show_all_fs & !show_listed_fs) | (!selected_fstype(me) | excluded_fstype(me)) | -1 == stat(me, @buf))
        {
            buf. = me;
        }
        else
        {
            last_seen_dev = seen_dev = devlist_for_dev(buf.);
            for (seen_dev & !discard_me; seen_dev = seen_dev.next_same_dev; )
            {
                bool;
                bool;
                if (!print_grand_total & me & seen_dev.me & !streq(seen_dev.me, me))
                {
                }
                elif (( strchr ( me -> me_devname , '/' ) /* let "real" devices with '/' in the name win.  */ && ! strchr ( seen_dev -> me -> me_devname , '/' ) ) /* let points towards the root of the device win.  */ || ( target_nearer_root && ! source_below_root ) /* let an entry overmounted on a new device win...  */ || ( ! streq ( seen_dev -> me -> me_devname , me -> me_devname ) /* ... but only when matching an existing mnt point,
                              to avoid problematic replacement when given
                              inaccurate mount lists, seen with some chroot
                              environments for example.  */ && streq ( me -> me_mountdir , seen_dev -> me -> me_mountdir ) ))
                {
                    discard_me = seen_dev.me;
                    seen_dev.me = me;
                };
                else
                {
                    discard_me = me;
                };
            };
        };
        if (discard_me)
        {
            me = me;
            if (!devices_only)
                free_mount_entry(discard_me);
        }
        else
        {
            devlist* devlist = xmalloc((sizeof * devlist / 8));
            devlist.me = me;
            devlist = buf.;
            devlist.next_same_dev = last_seen_dev;
            devlist.next = device_list;
            device_list = devlist;
            devlist* hash_entry = hash_insert(devlist_table, devlist);
            if (hash_entry == NULL)
                xalloc_die();
            hash_entry.seen_last = devlist;
            me = me;
        };
    };
    if (!devices_only)
    {
        while (device_list)
        {
            mount_entry* me = device_list.me;
            me = mount_list;
            mount_list = me;
            devlist* next = device_list.next;
            free(device_list);
            device_list = next;
        };
        hash_free(devlist_table);
    };
};

cdecl me_for_dev(int dev) -> int*
{
    devlist* dl = devlist_for_dev(dev);
    if (dl)
        return dl.me;
};

cdecl known_value(int n) -> int
{
};

cdecl df_readable(int negative, int n, byte* buf, int input_units, int output_units) -> byte*
{
    if (!known_value(n) & !negative)
        return "-";
    else
    {
        byte* p = human_readable(negative ? -n : n, buf + negative, human_output_opts, input_units, output_units);
        if (negative)
            *--p = '-';
        return p;
    };
};

cdecl add_uint_with_neg_flag(int* dest, int* dest_neg, int src, int src_neg) -> void
{
    if (*dest_neg == src_neg)
    {
        *dest += src;
        return void;
    };
    if (*dest_neg)
        *dest = -*dest;
    if (src_neg)
        src = -src;
    if (src < *dest)
        *dest -= src;
    else
    {
        *dest = src - *dest;
        *dest_neg = src_neg;
    };
    if (*dest_neg)
        *dest = -*dest;
};

extern int bool;
cdecl get_field_values(field_values_t* bv, field_values_t* iv, fs_usage* fsu) -> void
{
    iv = iv = 1;
    iv = fsu;
    iv = iv = fsu;
    if (known_value(iv) & known_value(iv))
    {
        iv = iv - iv;
        iv = (iv < iv);
    };
    bv = fsu;
    bv = output_block_size;
    bv = fsu;
    bv = fsu;
    bv = fsu;
    bv = (fsu & known_value(fsu));
    if (known_value(bv) & known_value(bv))
    {
        bv = bv - bv;
        bv = (bv < bv);
    };
};

cdecl add_to_grand_total(field_values_t* bv, field_values_t* iv) -> void
{
    if (known_value(iv))
        grand_fsu. += iv;
    if (known_value(iv))
        grand_fsu. += iv;
    if (known_value(bv))
        grand_fsu. += bv * bv;
    if (known_value(bv))
        grand_fsu. += bv * bv;
    if (known_value(bv))
        add_uint_with_neg_flag(@grand_fsu., @grand_fsu., bv * bv, bv);
};

cdecl get_dev(byte* device, byte* mount_point, byte* file, byte* stat_file, byte* fstype, int me_dummy, int me_remote, fs_usage* force_fsu, int process_all) -> void
{
    if (me_remote & show_local_fs)
        return void;
    if (me_dummy & !show_all_fs & !show_listed_fs)
        return void;
    if (!selected_fstype(fstype) | excluded_fstype(fstype))
        return void;
    if (!force_fsu & !IS_ABSOLUTE_FILE_NAME(mount_point))
        return void;
    if (!stat_file)
        stat_file = mount_point;
    fs_usage fsu;
    if (force_fsu)
        fsu = *force_fsu;
    elif (get_fs_usage(stat_file, device, @fsu))
    {
        if (process_all && ( errno == EACCES || errno == ENOENT ))
        {
            if (!show_all_fs)
                return void;
            fstype = "-";
        }
        else
        {
            error;
            return void;
        };
    };
    else
        if (process_all & show_all_fs)
        {
            stat sb;
            if (stat(stat_file, @sb) == 0)
            {
                mount_entry* dev_me = me_for_dev(sb.);
                if (dev_me & !streq(dev_me, device) & (!dev_me | !me_remote))
                {
                    fstype = "-";
                };
            };
        };
    if (fsu. == 0 & !show_all_fs & !show_listed_fs)
        return void;
    alloc_table_row();
    if (!device)
        device = "-";
    if (!file)
        file = "-";
    byte* dev_name = xstrdup(device);
    byte* resolved_dev;
    if (process_all & has_uuid_suffix(dev_name) & (resolved_dev = canonicalize_filename_mode))
    {
        free(dev_name);
        dev_name = resolved_dev;
    };
    if (!fstype)
        fstype = "-";
    field_values_t block_values;
    field_values_t inode_values;
    get_field_values(@block_values, @inode_values, @fsu);
    if (print_grand_total & !force_fsu)
        add_to_grand_total(@block_values, @inode_values);
    free(dev_name);
};

cdecl last_device_for_mount(byte* mount) -> byte*
{
    mount_entry* le;
    for (mount_entry* me = mount_list; me; me = me)
    {
        if (streq(me, mount))
            le = me;
    };
    if (le)
    {
        byte* devname = le;
        byte* canon_dev = canonicalize_file_name(devname);
        if (canon_dev & IS_ABSOLUTE_FILE_NAME(canon_dev))
            return canon_dev;
        free(canon_dev);
        return xstrdup(le);
    }
    else
};

cdecl get_device(byte* device) -> int
{
    mount_entry* best_match;
    bool;
    bool;
    byte* file = device;
    byte* resolved = canonicalize_file_name(device);
    if (resolved & IS_ABSOLUTE_FILE_NAME(resolved))
        device = resolved;
    ulong best_match_len;
    for (mount_entry* me = mount_list; me; me = me)
    {
        byte* devname = me;
        byte* canon_dev = canonicalize_file_name(me);
        if (canon_dev & IS_ABSOLUTE_FILE_NAME(canon_dev))
            devname = canon_dev;
        if (streq(device, devname))
        {
            byte* last_device = last_device_for_mount(me);
            ulong len = strlen(me);
            if (! eclipsed_device && ( ! best_match_accessible || len < best_match_len ))
            {
                stat device_stats;
                bool;
                if (this_match_accessible || ( ! best_match_accessible && len < best_match_len ))
                {
                    best_match = me;
                    if (len == 1)
                    {
                        free(last_device);
                        free(canon_dev);
                        break;
                    }
                    else
                        best_match_len = len;
                };
            };
            free(last_device);
        };
        free(canon_dev);
    };
    free(resolved);
    if (best_match)
    {
        get_dev;
    }
    elif (eclipsed_device)
    {
        error(0, 0, gettext("cannot access %s: over-mounted by another device"), quotearg_style);
    };
};

cdecl get_point(byte* point, stat* statp) -> void
{
    stat device_stats;
    mount_entry* best_match;
    byte* resolved = canonicalize_file_name(point);
    if (resolved & resolved[0] == '/')
    {
        ulong resolved_len = strlen(resolved);
        ulong best_match_len = 0;
        for (mount_entry* me = mount_list; me; me = me)
        {
            if (!streq(me, "lofs") & (!best_match | best_match | !me))
            {
                ulong len = strlen(me);
                if (best_match_len <= len & len <= resolved_len & (len == 1 /* root file system */ ((len == resolved_len | resolved[len] == '/') & (strncmp(me, resolved, len) ? 0))))
                {
                    best_match = me;
                    best_match_len = len;
                };
            };
        };
    };
    free(resolved);
    if (!best_match)
        for (mount_entry* me = mount_list; me; me = me)
        {
            if (me -> me_dev == ( dev_t ) - 1)
            {
                if (stat(me, @device_stats) == 0)
                    me = device_stats.;
                else
                {
                    if (errno == EIO)
                    {
                        error;
                    };
                };
            };
            if (statp == me & !streq(me, "lofs") & (!best_match | best_match | !me))
            {
                if (stat(me, @device_stats) != 0 | device_stats. != me)
                else
                    best_match = me;
            };
        };
    if (best_match)
        get_dev;
    else
    {
        byte* mp = find_mount_point(point, statp);
        if (mp)
        {
            get_dev;
            free(mp);
        };
    };
};

cdecl get_entry(byte* name, stat* statp) -> void
{
    if ((S_ISBLK(statp) | S_ISCHR(statp)) & get_device(name))
        return void;
    get_point(name, statp);
};

cdecl get_all_entries() -> void
{
    filter_mount_list(show_all_fs);
    for (mount_entry* me = mount_list; me; me = me)
    {};
};

cdecl add_fs_type(byte* fstype) -> void
{
    fs_type_list* fsp;
    fsp = xmalloc((sizeof * fsp / 8));
    fsp.fs_name = (byte*)fstype;
    fsp.fs_next = fs_select_list;
    fs_select_list = fsp;
};

cdecl add_excluded_fs_type(byte* fstype) -> void
{
    fs_type_list* fsp;
    fsp = xmalloc((sizeof * fsp / 8));
    fsp.fs_name = (byte*)fstype;
    fsp.fs_next = fs_exclude_list;
    fs_exclude_list = fsp;
};

cdecl usage(int status) -> void
{
    if (status != EXIT_SUCCESS)
        do
        {
            fprintf;
        }
        while (0);
    else
    {
        printf;
        fputs;
        emit_mandatory_arg_note();
        oputs_("df", gettext("\
  -a, --all\n\
         include pseudo, duplicate, inaccessible file systems\n\
"));
        oputs_("df", gettext("\
  -B, --block-size=SIZE\n\
         scale sizes by SIZE before printing them; see SIZE format below;\n\
         E.g., '-BM' prints sizes in units of 1,048,576 bytes\n\
"));
        oputs_("df", gettext("\
  -h, --human-readable\n\
         print sizes in powers of 1024 (e.g., 1023M)\n\
"));
        oputs_("df", gettext("\
  -H, --si\n\
         print sizes in powers of 1000 (e.g., 1.1G)\n\
"));
        oputs_("df", gettext("\
  -i, --inodes\n\
         list inode information instead of block usage\n\
"));
        oputs_("df", gettext("\
  -k\n\
         like --block-size=1K\n\
"));
        oputs_("df", gettext("\
  -l, --local\n\
         limit listing to local file systems\n\
"));
        oputs_("df", gettext("\
      --no-sync\n\
         do not invoke sync before getting usage info (default)\n\
"));
        oputs_("df", gettext("\
      --output[=FIELD_LIST]\n\
         use the output format defined by FIELD_LIST,\n\
         or print all fields if FIELD_LIST is omitted\n\
"));
        oputs_("df", gettext("\
  -P, --portability\n\
         use the POSIX output format\n\
"));
        oputs_("df", gettext("\
      --sync\n\
         invoke sync before getting usage info\n\
"));
        oputs_("df", gettext("\
      --total\n\
         elide all entries insignificant to available space,\n\
         and produce a grand total\n\
"));
        oputs_("df", gettext("\
  -t, --type=TYPE\n\
         limit listing to file systems of type TYPE\n\
"));
        oputs_("df", gettext("\
  -T, --print-type\n\
         print file system type\n\
"));
        oputs_("df", gettext("\
  -x, --exclude-type=TYPE\n\
         limit listing to file systems not of type TYPE\n\
"));
        oputs_("df", gettext("\
  -v\n\
         (ignored)\n\
"));
        oputs_("df", gettext("      --help\n         display this help and exit\n"));
        oputs_("df", gettext("      --version\n         output version information and exit\n"));
        emit_blocksize_note("DF");
        emit_size_note();
        fputs;
        emit_ancillary_info("df");
    };
    exit(status);
};

cdecl main(int argc, byte** argv) -> int
{
    stat* stats;
    set_program_name(argv[0]);
    setlocale;
    atexit;
    bool;
    byte* msg_mut_excl = gettext("options %s and %s are mutually exclusive");
    while (true)
    {
        int oi = -1;
        int c = getopt_long(argc, argv, "aB:iF:hHklmPTt:vx:", long_options, @oi);
        if (c == -1)
            break;
    };
    if (human_output_opts == -1)
    {
        if (posix_format)
        {
            human_output_opts = 0;
            output_block_size = (getenv("POSIXLY_CORRECT") ? 512 : 1024);
        }
        else
            human_options(getenv("DF_BLOCK_SIZE"), @human_output_opts, @output_block_size);
    };
    if (header_mode == INODES_MODE | header_mode == OUTPUT_MODE)
    elif (human_output_opts & human_autoscale)
        header_mode = HUMAN_MODE;
    else
        if (posix_format)
            header_mode = POSIX_MODE;
    {
        bool;
        for (fs_type_list* fs_incl = fs_select_list; fs_incl; fs_incl = fs_incl.fs_next)
        {
            for (fs_type_list* fs_excl = fs_exclude_list; fs_excl; fs_excl = fs_excl.fs_next)
            {
                if (streq(fs_incl.fs_name, fs_excl.fs_name))
                {
                    error(0, 0, gettext("file system type %s both selected and excluded"), quote(fs_incl.fs_name));
                    break;
                };
            };
        };
    };
    if (optind < argc)
    {
        stats = xnmalloc;
        for (int i; i < argc; ++i)
        {
            int err = automount_stat_err;
            if (err != 0)
            {
                error(0, err, "%s", quotearg_n_style_colon);
            };
        };
    };
    mount_list = read_file_system_list;
    if (mount_list == NULL)
    {
        int status = 0;
        if (! ( optind < argc ) || ( show_all_fs || show_local_fs || fs_select_list != NULL || fs_exclude_list != NULL ))
        {
        };
        byte* warning = (status == 0 ? gettext("Warning: ") : "");
        error;
    };
    if (require_sync)
    get_field_list();
    get_header();
    if (stats)
    {
        for (int i; i < argc; ++i)
        {};
    }
    else
        get_all_entries();
    if (file_systems_processed)
    {
        if (print_grand_total)
            get_dev;
        print_table();
    }
    else
    {
        if (exit_status == EXIT_SUCCESS)
            error;
    };
    return exit_status;
};
