// Auto-generated by cft from: dirname.c
// May require manual edits.

///
 dirname -- strip suffix from file name

   Copyright (C) 1990-2026 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
///

///
 Written by David MacKenzie and Jim Meyering.
///

byte* PROGRAM_NAME = "dirname";
macro AUTHORS
{
    proper_name ( "David MacKenzie" ) , proper_name ( "Jim Meyering" )
};

option[4] longopts = option;
cdecl usage(int status) -> void
{
    if (status != 0)
        do
        {
        }
        while (0);
    else
    {
        fputs(gettext("\
Output each NAME with its last non-slash component and trailing slashes\n\
removed; if NAME contains no /'s, output '.' (meaning the current directory).\n\
\n\
"), stdout);
        oputs_("dirname", gettext("\
  -z, --zero\n\
         end each output line with NUL, not newline\n\
"));
        oputs_("dirname", gettext("      --help\n         display this help and exit\n"));
        oputs_("dirname", gettext("      --version\n         output version information and exit\n"));
        emit_ancillary_info("dirname");
    };
    exit(status);
};

cdecl main(int argc, byte** argv) -> int
{
    bool;
    set_program_name(argv[0]);
    setlocale(0, "");
    while (?)
    {
        int c = getopt_long(argc, argv, "z", longopts, ((void*)0));
        if (c == -1)
            break;
        switch (c)
        {
            case ('z')
            {
            }
            goto _switch_end_139188883854928;
            case (GETOPT_HELP_CHAR)
            {
                usage(0);
            }
            goto _switch_end_139188883854928;
            case (GETOPT_VERSION_CHAR)
            {
            }
            exit(0);
            goto _switch_end_139188883854928;
            default
            {
                usage(0);
            };
        };
        label _switch_end_139188883854928:
    };
    if (argc < optind + 1)
    {
        error(0, 0, gettext("missing operand"));
        usage(0);
    };
    for (optind < argc; optind++; )
    {
        byte* result = argv[optind];
        if (?)
        {
            byte dot = '.';
            result = @dot;
        };
    };
    return 0;
};
