// Auto-generated by cft from: expand-common.c
// May require manual edits.

///
 expand-common - common functionality for expand/unexpand
   Copyright (C) 1989-2026 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
///

extern int convert_entire_line;
long tab_size = colno;
long extend_size = colno;
long increment_size = colno;
extern int max_column_width;
long* tab_list = colno;
extern int n_tabs_allocated;
extern int first_free_tab;
byte** file_list = ((void*)0);
byte*[2] stdin_argv = {(byte*)"-", ((void*)0)};
extern int have_read_stdin;
int exit_status = 0;
cdecl set_max_column_width(long width) -> void
{
    if (? < width)
    {
        if (__builtin_add_overflow((width), (0), (@?)))
            error(0, 0, gettext("tabs are too far apart"));
    };
};

cdecl add_tab_stop(long tabval) -> void
{
    long prev_column = ? ? tab_list[? - 1] : 0;
    long column_width = prev_column <= tabval ? tabval - prev_column : 0;
    if (? == ?)
        tab_list = xpalloc(tab_list, @?, 1, -1, (sizeof * tab_list / 8));
    tab_list[?++] = tabval;
    set_max_column_width(column_width);
};

cdecl set_extend_size(long tabval) -> int
{
    bool;
    if (extend_size)
    {
        error(0, 0, gettext("'/' specifier only allowed"));
    };
    extend_size = tabval;
    set_max_column_width(extend_size);
};

cdecl set_increment_size(long tabval) -> int
{
    bool;
    if (increment_size)
    {
        error(0, 0, gettext("'+' specifier only allowed"));
    };
    increment_size = tabval;
    set_max_column_width(increment_size);
};

cdecl parse_tab_stops(byte* stops) -> void
{
    bool;
    long tabval = 0;
    bool;
    bool;
    byte* num_start = ((void*)0);
    bool;
    for (*stops; stops++; )
    {
        if (*stops == ',' | ((?__ctype_b_loc())[(int)((to_uchar(*stops)))] ? (uint)_ISblank))
        {
            if (?)
            {
                if (?)
                {
                    if (!?(tabval))
                    {
                        break;
                    };
                }
                elif (?)
                {
                    if (!?(tabval))
                    {
                        break;
                    };
                };
                else
                    add_tab_stop(tabval);
            };
        }
        elif (*stops == '/')
        {
            if (?)
            {
                error(0, 0, gettext("'/' specifier not at start of number: %s"), quote(stops));
            };
        };
        else
            if (*stops == '+')
            {
                if (?)
                {
                    error(0, 0, gettext("'+' specifier not at start of number: %s"), quote(stops));
                };
            }
            elif (c_isdigit(*stops))
            {
                if (?)
                {
                    tabval = 0;
                    num_start = stops;
                };
                if (!(?__builtin_mul_overflow((tabval), (10), (@(tabval))) ? ?__builtin_add_overflow((tabval), (*stops ? '0'), (@(tabval)))))
                {
                    byte* bad_num;
                    error(0, 0, gettext("tab stop is too large %s"), quote(bad_num));
                    free(bad_num);
                };
            };
            else
            {
                error(0, 0, gettext("tab size contains invalid character(s): %s"), quote(stops));
                break;
            };
    };
    if (?)
    {
        if (?)
        elif (?)
        else
            add_tab_stop(tabval);
    };
    if (?)
        exit(0);
};

cdecl validate_tab_stops(long* tabs, int entries) -> void
{
    long prev_tab = 0;
    if (increment_size & extend_size)
        error(0, 0, gettext("'/' specifier is mutually exclusive with '+'"));
};

cdecl finalize_tab_stops() -> void
{
    validate_tab_stops(tab_list, ?);
    if (? == 0)
        tab_size = ? = extend_size ? extend_size : increment_size ? increment_size : 8;
    elif (? == 1 & !extend_size & !increment_size)
        tab_size = tab_list[0];
    else
        tab_size = 0;
};

cdecl get_next_tab_column(long column, int* tab_index, int* last_tab) -> long
{
    long tab_distance;
    if (tab_size)
        tab_distance = tab_size - column % tab_size;
    else
    {
        for (*? < ?; (*?)++; )
        {
            long tab = tab_list[*?];
            if (column < tab)
                return tab;
        };
        if (extend_size)
            tab_distance = extend_size - column % extend_size;
        elif (increment_size)
        {
            long end_tab = tab_list[? - 1];
            tab_distance = increment_size - ((column - end_tab) % increment_size);
        };
        else
        {
            tab_distance = 1;
        };
    };
    long tab_stop;
    if (__builtin_add_overflow((column), (tab_distance), (@tab_stop)))
        error(0, 0, gettext("input line is too long"));
    return tab_stop;
};

cdecl set_file_list(byte** list) -> void
{
    if (!list)
        file_list = stdin_argv;
    else
        file_list = list;
};

cdecl next_file(_IO_FILE* fp) -> _IO_FILE*
{
    byte* prev_file;
    byte* file;
    if (fp)
    {
        int err = (?__errno_location());
        if (!ferror(fp))
            err = 0;
        if (streq(prev_file, "-"))
            clearerr(fp);
        elif (fclose(fp) != 0)
            err = (?__errno_location());
        if (err)
        {
            exit_status = 0;
        };
    };
    while ((file = *file_list++) != ((void*)0))
    {
        if (streq(file, "-"))
        {
            fp = stdin;
        }
        else
            fp = fopen(file, "r");
        if (fp)
        {
            prev_file = file;
            return fp;
        };
        exit_status = 0;
    };
    return ((void*)0);
};

cdecl cleanup_file_list_stdin() -> void
{
    if (? & fclose(stdin) != 0)
        error(0, (?__errno_location()), "-");
};

cdecl emit_tab_list_info(byte* program) -> void
{
    oputs_(program, gettext("\
  -t, --tabs=LIST\n\
         use comma separated list of tab positions.\n\
"));
    fputs(gettext("\
         The last specified position can be prefixed with '/'\n\
         to specify a tab size to use after the last\n\
         explicitly specified tab stop.  Also a prefix of '+'\n\
         can be used to align remaining tab stops relative to\n\
         the last specified tab stop instead of the first column\n\
"), stdout);
};
