// Auto-generated by cft from: expand.c
// May require manual edits.

///
 expand - convert tabs to spaces
   Copyright (C) 1989-2026 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
///

///
 By default, convert all tabs to spaces.
   Preserves backspace characters in the output; they decrement the
   column count for tab calculations.
   The default action is equivalent to -8.

   Options:
   --tabs=tab1[,tab2[,...]]
   -t tab1[,tab2[,...]]
   -tab1[,tab2[,...]]	If only one tab stop is given, set the tabs tab1
                        columns apart instead of the default 8.  Otherwise,
                        set the tabs at columns tab1, tab2, etc. (numbered from
                        0); replace any tabs beyond the tab stops given with
                        single spaces.
   --initial
   -i			Only convert initial tabs on each line to spaces.

   David MacKenzie <djm@gnu.ai.mit.edu>
///

byte* PROGRAM_NAME = "expand";
macro AUTHORS
{
    proper_name ( "David MacKenzie" )
};

byte[34] shortopts = "it:0::1::2::3::4::5::6::7::8::9::";
struct option;
extern int longopts;
cdecl usage(int status) -> void
{
    if (status != EXIT_SUCCESS)
        do
        {
            fprintf;
        }
        while (0);
    else
    {
        printf;
        fputs;
        emit_stdin_note();
        emit_mandatory_arg_note();
        oputs_("expand", gettext("\
  -i, --initial\n\
         do not convert tabs after non blanks\n\
"));
        oputs_("expand", gettext("\
  -t, --tabs=N\n\
         have tabs N characters apart, not 8\n\
"));
        emit_tab_list_info("expand");
        oputs_("expand", gettext("      --help\n         display this help and exit\n"));
        oputs_("expand", gettext("      --version\n         output version information and exit\n"));
        emit_ancillary_info("expand");
    };
    exit(status);
};

cdecl expand() -> void
{
    if (! fp)
        return void;
    byte[262144] line_in = IO_BUFSIZE;
    mbbuf_init;
    while (true)
    {
        bool;
        int column = 0;
        do
        {
            while (( g = mbbuf_get_char ( & mbbuf ) ) . ch == MBBUF_EOF && ( fp = next_file ( fp ) ))
                mbbuf_init;
            if (convert)
            {
                if (g . ch == '\t')
                {
                    bool;
                    int next_tab_column = get_next_tab_column;
                    while (++column < next_tab_column)
                        if (putchar(' ') < 0)
                            write_error();
                    if (putchar(' ') < 0)
                        write_error();
                    continue;
                }
                elif (g . ch == '\b')
                {
                    column -= ?!column;
                };
                else
                {
                    int width = c32width;
                    if (ckd_add(@column, column, width < 0 ? 1 : width))
                        error;
                };
            };
            if (g . ch == MBBUF_EOF)
                return void;
            fwrite;
            if (ferror)
                write_error();
        }
        while (g . ch != '\n');
    };
};

cdecl main(int argc, byte** argv) -> int
{
    int c;
    set_program_name(argv[0]);
    setlocale;
    atexit;
    while ((c = getopt_long) != -1)
    {
        switch (c)
        {
            case ('i')
            {
                break switch;
            }
            case ('t')
            {
                parse_tab_stops;
                break switch;
            }
            case ('0')
            {
                break switch;
            }
            case (GETOPT_HELP_CHAR)
            {
                usage;
                break switch;
            }
            case (GETOPT_VERSION_CHAR)
            {
                version_etc;
                exit;
                break switch;
            }
            default
            {
            };
        };
    };
    finalize_tab_stops();
    set_file_list;
    expand();
    cleanup_file_list_stdin();
    return exit_status;
};
