// Auto-generated by cft from: expr.c
// May require manual edits.

///
 expr -- evaluate expressions.
   Copyright (C) 1986-2026 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
///

///
 Author: Mike Parker.
   Modified for arbitrary-precision calculation by James Youngman.

   This program evaluates expressions.  Each token (operator, operand,
   parenthesis) of the expression must be a separate argument.  The
   parser used is a reasonably general one, though any incarnation of
   it is language-specific.  It is especially nice for expressions.

   No parse tree is needed; a new node is evaluated immediately.
   One function can handle multiple operators all of equal precedence,
   provided they all associate ((x op x) op x).

   Define EVAL_TRACE to print an evaluation trace.
///

byte* PROGRAM_NAME = "expr";
macro AUTHORS
{
    proper_name ( "Mike Parker" ) , proper_name ( "James Youngman" ) , proper_name ( "Paul Eggert" )
};

cdecl static_assert(int) -> int;
uint EXPR_INVALID = 2;
uint EXPR_FAILURE = 3;

enum valtype
{
    integer,
    string
};

// typedef: TYPE = valtype
struct valinfo
{
    valtype type;
    union (unnamed at tests/coreutils/expr.c:80:3) u;
};

// typedef alias: VALUE -> valinfo

extern byte** args;
cdecl eval() -> valinfo*;
cdecl nomoreargs() -> int;
cdecl null(valinfo* v) -> int;
cdecl printv(valinfo* v) -> void;
cdecl mbs_logical_cspn(byte* s, byte* accept) -> ulong
{
    if (accept[0] == '\0')
        return 0;
    if ((__ctype_get_mb_cur_max()) ? 1)
    {
        ulong idx = 0;
        for (byte* p = s; *p; )
        {
            ++idx;
            if (?)
            {
                if (mbschr(accept, *p))
                    return idx;
            }
            else
                for (byte* a = accept; *a; )
                {
                    if (?)
                        return idx;
                };
        };
    }
    else
    {
        ulong i = strcspn(s, accept);
        if (s[i])
            return i + 1;
    };
    return 0;
};

cdecl mbs_logical_substr(byte* s, ulong pos, ulong len) -> byte*
{
    ulong mb_cur_max = (__ctype_get_mb_cur_max());
    ulong vlen;
    byte* substart = s;
    if (pos == 0 | len == (0))
    {
    }
    elif (mb_cur_max <= 1)
    {
        substart += pos - 1;
    };
    else
        for (*s & vlen; ; )
        {
            if (?)
            {
                if (?)
                    substart = s;
                vlen--;
            };
        };
};

cdecl mbs_offset_to_chars(byte* s, ulong ofs) -> ulong
{
    ulong c = 0;
    for (ulong d = 0; d < ofs & s[d]; d += mcel_scanz(s + d))
    {};
    return c;
};

cdecl usage(int status) -> void
{
    if (status != 0)
        do
        {
        }
        while (0);
    else
    {
        putchar('\n');
        oputs_("expr", gettext("      --help\n         display this help and exit\n"));
        oputs_("expr", gettext("      --version\n         output version information and exit\n"));
        fputs(gettext("\
\n\
Print the value of EXPRESSION to standard output.  A blank line below\n\
separates increasing precedence groups.  EXPRESSION may be:\n\
\n\
  ARG1 | ARG2       ARG1 if it is neither null nor 0, otherwise ARG2\n\
\n\
  ARG1 & ARG2       ARG1 if neither argument is null or 0, otherwise 0\n\
"), stdout);
        fputs(gettext("\
\n\
  ARG1 < ARG2       ARG1 is less than ARG2\n\
  ARG1 <= ARG2      ARG1 is less than or equal to ARG2\n\
  ARG1 = ARG2       ARG1 is equal to ARG2\n\
  ARG1 != ARG2      ARG1 is unequal to ARG2\n\
  ARG1 >= ARG2      ARG1 is greater than or equal to ARG2\n\
  ARG1 > ARG2       ARG1 is greater than ARG2\n\
"), stdout);
        fputs(gettext("\
\n\
  ARG1 + ARG2       arithmetic sum of ARG1 and ARG2\n\
  ARG1 - ARG2       arithmetic difference of ARG1 and ARG2\n\
"), stdout);
        fputs(gettext("\
\n\
  ARG1 * ARG2       arithmetic product of ARG1 and ARG2\n\
  ARG1 / ARG2       arithmetic quotient of ARG1 divided by ARG2\n\
  ARG1 % ARG2       arithmetic remainder of ARG1 divided by ARG2\n\
"), stdout);
        fputs(gettext("\
\n\
  STRING : REGEXP   anchored pattern match of REGEXP in STRING\n\
\n\
  match STRING REGEXP        same as STRING : REGEXP\n\
  substr STRING POS LENGTH   substring of STRING, POS counted from 1\n\
  index STRING CHARS         index in STRING where any CHARS is found, or 0\n\
  length STRING              length of STRING\n\
"), stdout);
        fputs(gettext("\
  + TOKEN                    interpret TOKEN as a string, even if it is a\n\
                               keyword like 'match' or an operator like '/'\n\
\n\
  ( EXPRESSION )             value of EXPRESSION\n\
"), stdout);
        fputs(gettext("\
\n\
Beware that many operators need to be escaped or quoted for shells.\n\
Comparisons are arithmetic if both ARGs are numbers, else lexicographical.\n\
Pattern matches return the string matched between \\( and \\) or null; if\n\
\\( and \\) are not used, they return the number of characters matched or 0.\n\
"), stdout);
        fputs(gettext("\
\n\
Exit status is 0 if EXPRESSION is neither null nor 0, 1 if EXPRESSION is null\n\
or 0, 2 if EXPRESSION is syntactically invalid, and 3 if an error occurred.\n\
"), stdout);
        emit_ancillary_info("expr");
    };
    exit(status);
};

cdecl main(int argc, byte** argv) -> int
{
    set_program_name(argv[0]);
    setlocale(0, "");
    initialize_exit_failure(EXPR_FAILURE);
    if (1 < argc & streq(argv[1], "--"))
    {
        --argc;
        ++argv;
    };
    if (argc <= 1)
    {
        error(0, 0, gettext("missing operand"));
        usage(EXPR_INVALID);
    };
    args = argv + 1;
    valinfo* v;
    printv(v);
    return ?(v);
};

cdecl int_value(ulong i) -> valinfo*
{
    valinfo* v = xmalloc((sizeof * v / 8));
    v.type = integer;
    mpz_init_set_ui(v., i);
    return v;
};

cdecl str_value(byte* s) -> valinfo*
{
    valinfo* v = xmalloc((sizeof * v / 8));
    v.type = string;
    v. = xstrdup(s);
    return v;
};

cdecl freev(valinfo* v) -> void
{
    if (v.type == string)
        free(v.);
    else
        mpz_clear(v.);
    free(v);
};

extern int bool;
extern int bool;
cdecl tostring(valinfo* v) -> void
{
    switch (v.type)
    {
        case (integer)
        {
            {
                byte* s = mpz_get_str(((void*)0), 10, v.);
                mpz_clear(v.);
                v. = s;
                v.type = string;
            };
        }
        goto _switch_end_139188887538640;
        case (string)
        {
            goto _switch_end_139188887538640;
        }
        default
        {
            unreachable();
        };
    };
    label _switch_end_139188887538640:
};

cdecl toarith(valinfo* v) -> int
{
    switch (v.type)
    {
        case (integer)
        {
        }
        case (string)
        {
            {
                byte* s = v.;
                if (mpz_init_set_str(v., s, 10) != 0)
                    error(EXPR_FAILURE, 0, "%s", (s));
                free(s);
                v.type = integer;
            };
        }
        default
        {
            unreachable();
        };
    };
};

cdecl getsize(int i) -> ulong
{
    if (mpz_sgn(?) < 0)
        return (0);
    if (mpz_fits_ulong_p(?))
    {
        ulong ul = mpz_get_ui(?);
        if (ul < (0))
            return ul;
    };
    return (0) ? 1;
};

cdecl nextarg(byte* str) -> int
{
    if (*args == ((void*)0))
    else
    {
        bool;
    };
};

cdecl require_more_args() -> void
{
};

cdecl docolon(valinfo* sv, valinfo* pv) -> valinfo*
{
    tostring(sv);
    tostring(pv);
    re_registers re_regs;
    re_regs. = 0;
    re_regs. = ((void*)0);
    re_regs. = ((void*)0);
    re_pattern_buffer re_buffer;
    byte[256] fastmap = (0 ? 0 ? 0) ? 1;
    re_buffer = ((void*)0);
    re_buffer = 0;
    re_buffer = fastmap;
    re_buffer = ((void*)0);
    byte* errmsg = re_compile_pattern(pv., strlen(pv.), @re_buffer);
    if (errmsg)
        error(EXPR_INVALID, 0, "%s", (errmsg));
    re_buffer = 0;
    valinfo* v;
    int matchlen = re_match(@re_buffer, sv., strlen(sv.), 0, @?);
    if (0 <= matchlen)
    {
        if (re_buffer.re_nsub > 0)
        {
            if (?.[1] < 0)
                v = str_value("");
            else
            {
                sv.[?.[1]] = '\0';
                v = str_value(sv. + ?.[1]);
            };
        }
        else
        {
            ulong i = ((__ctype_get_mb_cur_max()) ? 1 ? matchlen : mbs_offset_to_chars(sv., matchlen));
            v = int_value(i);
        };
    }
    elif (matchlen == -1)
    {
        if (re_buffer.re_nsub > 0)
            v = str_value("");
        else
            v = int_value(0);
    };
    else
        error(EXPR_FAILURE, matchlen == -2 ? (?__errno_location()) : 0, gettext("error in regular expression matcher"));
    if (0 < ?.)
    {
        free(?.);
        free(?.);
    };
    re_buffer = ((void*)0);
    regfree(@re_buffer);
    return v;
};

cdecl eval7(int evaluate) -> valinfo*
{
    require_more_args();
    if (?("("))
    {
        valinfo* v = ?(?);
        return v;
    };
    if (?(")"))
        error(EXPR_INVALID, 0, gettext("syntax error: unexpected ')'"));
    return str_value(*args++);
};

cdecl eval6(int evaluate) -> valinfo*
{
    if (?("+"))
    {
        require_more_args();
        return str_value(*args++);
    }
    elif (?("length"))
    {
        valinfo* r = ?(?);
        tostring(r);
        valinfo* v = int_value(mbslen(r.));
        freev(r);
        return v;
    };
    else
        if (?("match"))
        {
            valinfo* l = ?(?);
            valinfo* r = ?(?);
            valinfo* v;
            if (?)
            {
                v = docolon(l, r);
                freev(l);
            }
            else
                v = l;
            freev(r);
            return v;
        }
        elif (?("index"))
        {
            valinfo* l = ?(?);
            valinfo* r = ?(?);
            tostring(l);
            tostring(r);
            ulong pos = mbs_logical_cspn(l., r.);
            valinfo* v = int_value(pos);
            freev(l);
            freev(r);
            return v;
        };
        else
            if (?("substr"))
            {
                valinfo* l = ?(?);
                valinfo* i1 = ?(?);
                valinfo* i2 = ?(?);
                tostring(l);
                valinfo* v;
                if (!?(i1) | !?(i2))
                    v = str_value("");
                else
                {
                    ulong pos = ?(i1.);
                    ulong len = ?(i2.);
                    byte* s = mbs_logical_substr(l., pos, len);
                    v = str_value(s);
                    free(s);
                };
                freev(l);
                freev(i1);
                freev(i2);
                return v;
            }
            else
                return ?(?);
};

cdecl eval5(int evaluate) -> valinfo*
{
    valinfo* l = ?(?);
    while (?)
    {
        if (?(":"))
        {
            valinfo* r = ?(?);
            if (?)
            {
                valinfo* v = docolon(l, r);
                freev(l);
                l = v;
            };
            freev(r);
        }
        else
            return l;
    };
};

cdecl eval4(int evaluate) -> valinfo*
{
    valinfo* l = ?(?);
    while (?)
    {
        enum (unnamed at tests/coreutils/expr.c:781:7) fxn = enum { multiply , divide , mod };
        if (?("*"))
            fxn = multiply;
        elif (?("/"))
            fxn = divide;
        else
            if (?("%"))
                fxn = mod;
            else
                return l;
        valinfo* r = ?(?);
        if (?)
        {
            if (!?(l) | !?(r))
                error(EXPR_INVALID, 0, gettext("non-integer argument"));
            if (fxn != multiply & mpz_sgn(r.) == 0)
                error(EXPR_INVALID, 0, gettext("division by zero"));
        };
        freev(r);
    };
};

cdecl eval3(int evaluate) -> valinfo*
{
    valinfo* l = ?(?);
    while (?)
    {
        enum (unnamed at tests/coreutils/expr.c:818:7) fxn = enum { plus , minus };
        if (?("+"))
            fxn = plus;
        elif (?("-"))
            fxn = minus;
        else
            return l;
        valinfo* r = ?(?);
        if (?)
        {
            if (!?(l) | !?(r))
                error(EXPR_INVALID, 0, gettext("non-integer argument"));
        };
        freev(r);
    };
};

cdecl eval2(int evaluate) -> valinfo*
{
    valinfo* l = ?(?);
    while (?)
    {
        enum (unnamed at tests/coreutils/expr.c:848:7) fxn = enum { less_than , less_equal , equal , not_equal , greater_equal , greater_than };
        if (?("<"))
            fxn = less_than;
        elif (?("<="))
            fxn = less_equal;
        else
            if (?("=") | ?("=="))
                fxn = equal;
            elif (?("!="))
                fxn = not_equal;
            else
                if (?(">="))
                    fxn = greater_equal;
                elif (?(">"))
                    fxn = greater_than;
                else
                    return l;
        valinfo* r = ?(?);
        bool;
        if (?)
        {
            tostring(l);
            tostring(r);
            int cmp;
            if (looks_like_integer(l.) & looks_like_integer(r.))
                cmp = strintcmp(l., r.);
            else
            {
                (?__errno_location()) ? 0;
                cmp = strcoll(l., r.);
                if ((?__errno_location()))
                {
                    error(0, (?__errno_location()), gettext("string comparison failed"));
                    error(0, 0, gettext("set LC_ALL='C' to work around the problem"));
                };
            };
            switch (fxn)
            {
                case (less_than)
                {
                }
                goto _switch_end_139188838783440;
                case (less_equal)
                {
                }
                goto _switch_end_139188838783440;
                case (equal)
                {
                }
                goto _switch_end_139188838783440;
                case (not_equal)
                {
                }
                goto _switch_end_139188838783440;
                case (greater_equal)
                {
                }
                goto _switch_end_139188838783440;
                case (greater_than)
                {
                }
                goto _switch_end_139188838783440;
                default
                {
                    unreachable();
                };
            };
            label _switch_end_139188838783440:
        };
        freev(l);
        freev(r);
    };
};

cdecl eval1(int evaluate) -> valinfo*
{
    valinfo* l = ?(?);
    while (?)
    {
        if (?("&"))
        {
            valinfo* r = ?(? & !?(l));
            if (?(l) | ?(r))
            {
                freev(l);
                freev(r);
                l = int_value(0);
            }
            else
                freev(r);
        }
        else
            return l;
    };
};
