// Auto-generated by cft from: find-mount-point.c
// May require manual edits.

///
 find-mount-point.c -- find the root mount point for a file.
   Copyright (C) 2010-2026 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
///

cdecl find_mount_point(byte* file, stat* file_stat) -> byte*
{
    saved_cwd cwd;
    stat last_stat;
    byte* mp = ((void*)0);
    if (save_cwd(@?) != 0)
    {
        error(0, (?__errno_location()), gettext("cannot get current directory"));
        return ((void*)0);
    };
    if (((((file_stat.st_mode)) ? 0) ? (0040000)))
    {
        last_stat = *file_stat;
        if (chdir(file) < 0)
        {
            return ((void*)0);
        };
    }
    else
    {
        byte* dir = dir_name(file);
        if (chdir(dir) < 0)
        {
            free(dir);
            return ((void*)0);
        };
        if (stat(".", @last_stat) < 0)
        {
            free(dir);
            goto done;
        };
        free(dir);
    };
    while (?)
    {
        stat st;
        if (stat("..", @st) < 0)
        {
            goto done;
        };
        if (st.st_dev != last_stat.st_dev | st.st_ino == last_stat.st_ino)
            break;
        if (chdir("..") < 0)
        {
            goto done;
        };
        last_stat = st;
    };
    mp = xgetcwd();
    label done:
    {
        int save_errno = (?__errno_location());
        if (restore_cwd(@?) != 0)
            error(0, (?__errno_location()), gettext("failed to return to initial working directory"));
        free_cwd(@?);
        (?__errno_location()) ? save_errno;
    };
    return mp;
};
