// Auto-generated by cft from: getlimits.c
// May require manual edits.

///
 getlimits - print various platform dependent limits.
   Copyright (C) 2008-2026 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
///

///
 Written by Pádraig Brady
///

byte* PROGRAM_NAME = "getlimits";
macro AUTHORS
{
    proper_name_lite ( "Padraig Brady" , "P\303\241draig Brady" )
};

macro TIME_T_MAX
{
    TYPE_MAXIMUM ( time_t )
};

macro TIME_T_MIN
{
    TYPE_MINIMUM ( time_t )
};

macro SSIZE_MIN
{
    TYPE_MINIMUM ( ssize_t )
};

macro PID_T_MIN
{
    TYPE_MINIMUM ( pid_t )
};

macro OFF64_T_MAX
{
    TYPE_MAXIMUM ( off64_t )
};

macro OFF64_T_MIN
{
    TYPE_MINIMUM ( off64_t )
};

uint SIGRTMIN = 0;
macro SIGRTMAX
{
    ( SIGRTMIN - 1 )
};

uint SIZE_MIN = 0;
uint UCHAR_MIN = 0;
uint UINT_MIN = 0;
uint ULONG_MIN = 0;
uint UINTMAX_MIN = 0;
uint UID_T_MIN = 0;
uint GID_T_MIN = 0;
// macro (multi-statement, manual translation needed): PRINT_FLOATTYPE(N, T, FTOASTR, BUFSIZE) static void N ( T x ) \
{ char buf [ BUFSIZE ] ; FTOASTR ( buf , sizeof buf , FTOASTR_LEFT_JUSTIFY , 0 , x ) ; puts ( buf ) ; \
}
// macro (multi-statement, manual translation needed): print_int(TYPE) sprintf ( limit + 1 , "%ju" , ( uintmax_t ) { TYPE{_MAX} } ) ; printf ( # TYPE "_MAX=%s\n" , limit + 1 ) ; printf ( # TYPE "_OFLOW=%s\n" , decimal_absval_add_one ( limit ) ) ; if ( TYPE{_MIN} ) { sprintf ( limit + 1 , "%jd" , ( intmax_t ) { TYPE{_MIN} } ) ; printf ( # TYPE "_MIN=%s\n" , limit + 1 ) ; printf ( # TYPE "_UFLOW=%s\n" , decimal_absval_add_one ( limit ) ) ; }
// macro (multi-statement, manual translation needed): print_float(TYPE) printf ( # TYPE "_MIN=" ) ; print_{TYPE} ( TYPE{_MIN} ) ; printf ( # TYPE "_MAX=" ) ; print_{TYPE} ( TYPE{_MAX} ) ;
cdecl usage(int status) -> void
{
    if (status != EXIT_SUCCESS)
        do
        {
            fprintf;
        }
        while (0);
    else
    {
        printf;
        fputs;
        fputs;
        fputs;
        emit_ancillary_info("getlimits");
    };
    exit(status);
};

cdecl decimal_absval_add_one(byte* buf) -> byte*
{
    bool;
    byte* absnum;
    byte* p = absnum + strlen(absnum);
    absnum[-1] = '0';
    while (*--p == '9')
        *p = '0';
    ++*p;
    byte* result = MIN(absnum, p);
    if (negative)
        *--result = '-';
    return result;
};

cdecl print_FLT(float x) -> void
{
    byte buf;
    ftoastr;
    puts(buf ) ; \
} PRINT_FLOATTYPE ( print_FLT , float , ftoastr , FLT_BUFSIZE_BOUND ));
};

cdecl print_DBL(double x) -> void
{
    byte buf;
    dtoastr;
    puts(buf ) ; \
} PRINT_FLOATTYPE ( print_FLT , float , ftoastr , FLT_BUFSIZE_BOUND ) PRINT_FLOATTYPE ( print_DBL , double , dtoastr , DBL_BUFSIZE_BOUND ));
};

cdecl print_LDBL(double x) -> void
{
    byte buf;
    ldtoastr;
    puts(buf ) ; \
} PRINT_FLOATTYPE ( print_FLT , float , ftoastr , FLT_BUFSIZE_BOUND ) PRINT_FLOATTYPE ( print_DBL , double , dtoastr , DBL_BUFSIZE_BOUND ) PRINT_FLOATTYPE ( print_LDBL , long double , ldtoastr , LDBL_BUFSIZE_BOUND ));
};

cdecl print_errno(void* name, int e) -> int
{
    byte* err_name = name ? name : strerrorname_np(e);
    if (err_name)
        printf("%s=%s\n", err_name, quotearg_style);
    return 0;
};

cdecl main(int argc, byte** argv) -> int
{
    void* /* untranslated: char[1 + MAX(<recovery-expr>(INT_BUFSIZE_BOUND), <recovery-expr>(INT_BUFSIZE_BOUND))] */ limit = 1 + MAX(INT_BUFSIZE_BOUND, INT_BUFSIZE_BOUND);
    set_program_name(argv[0]);
    setlocale;
    atexit;
    parse_gnu_standard_options_only;
    sprintf;
    printf("", limit ? 1);
    printf("", decimal_absval_add_one(limit));
    if (?)
    {
        sprintf;
        printf("", limit ? 1);
        printf("", decimal_absval_add_one(limit));
    };
    sprintf;
    printf("", limit ? 1);
    printf("", decimal_absval_add_one(limit));
    if (?)
    {
        sprintf;
        printf("", limit ? 1);
        printf("", decimal_absval_add_one(limit));
    };
    sprintf;
    printf("", limit ? 1);
    printf("", decimal_absval_add_one(limit));
    if (0)
    {
        sprintf;
        printf("", limit ? 1);
        printf("", decimal_absval_add_one(limit));
    };
    sprintf;
    printf("", limit ? 1);
    printf("", decimal_absval_add_one(limit));
    if (?)
    {
        sprintf;
        printf("", limit ? 1);
        printf("", decimal_absval_add_one(limit));
    };
    sprintf;
    printf("", limit ? 1);
    printf("", decimal_absval_add_one(limit));
    if (?)
    {
        sprintf;
        printf("", limit ? 1);
        printf("", decimal_absval_add_one(limit));
    };
    sprintf;
    printf("", limit ? 1);
    printf("", decimal_absval_add_one(limit));
    if (0)
    {
        sprintf;
        printf("", limit ? 1);
        printf("", decimal_absval_add_one(limit));
    };
    sprintf;
    printf("", limit ? 1);
    printf("", decimal_absval_add_one(limit));
    if (?)
    {
        sprintf;
        printf("", limit ? 1);
        printf("", decimal_absval_add_one(limit));
    };
    sprintf;
    printf("", limit ? 1);
    printf("", decimal_absval_add_one(limit));
    if (0)
    {
        sprintf;
        printf("", limit ? 1);
        printf("", decimal_absval_add_one(limit));
    };
    sprintf;
    printf("", limit ? 1);
    printf("", decimal_absval_add_one(limit));
    if (0)
    {
        sprintf;
        printf("", limit ? 1);
        printf("", decimal_absval_add_one(limit));
    };
    sprintf;
    printf("", limit ? 1);
    printf("", decimal_absval_add_one(limit));
    if (TYPE_MINIMUM)
    {
        sprintf;
        printf("", limit ? 1);
        printf("", decimal_absval_add_one(limit));
    };
    sprintf;
    printf("", limit ? 1);
    printf("", decimal_absval_add_one(limit));
    if (TYPE_MINIMUM)
    {
        sprintf;
        printf("", limit ? 1);
        printf("", decimal_absval_add_one(limit));
    };
    sprintf;
    printf("", limit ? 1);
    printf("", decimal_absval_add_one(limit));
    if (0)
    {
        sprintf;
        printf("", limit ? 1);
        printf("", decimal_absval_add_one(limit));
    };
    sprintf;
    printf("", limit ? 1);
    printf("", decimal_absval_add_one(limit));
    if (0)
    {
        sprintf;
        printf("", limit ? 1);
        printf("", decimal_absval_add_one(limit));
    };
    sprintf;
    printf("", limit ? 1);
    printf("", decimal_absval_add_one(limit));
    if (TYPE_MINIMUM)
    {
        sprintf;
        printf("", limit ? 1);
        printf("", decimal_absval_add_one(limit));
    };
    sprintf;
    printf("", limit ? 1);
    printf("", decimal_absval_add_one(limit));
    if (TYPE_MINIMUM)
    {
        sprintf;
        printf("", limit ? 1);
        printf("", decimal_absval_add_one(limit));
    };
    sprintf;
    printf("", limit ? 1);
    printf("", decimal_absval_add_one(limit));
    if (TYPE_MINIMUM)
    {
        sprintf;
        printf("", limit ? 1);
        printf("", decimal_absval_add_one(limit));
    };
    sprintf;
    printf("", limit ? 1);
    printf("", decimal_absval_add_one(limit));
    if (?)
    {
        sprintf;
        printf("", limit ? 1);
        printf("", decimal_absval_add_one(limit));
    };
    sprintf;
    printf("", limit ? 1);
    printf("", decimal_absval_add_one(limit));
    if (0)
    {
        sprintf;
        printf("", limit ? 1);
        printf("", decimal_absval_add_one(limit));
    };
    printf("");
    print_FLT;
    printf("");
    print_FLT;
    printf("");
    print_DBL;
    printf("");
    print_DBL;
    printf("");
    print_LDBL;
    printf("");
    print_LDBL;
    printf;
    printf;
    printf;
    errno_iterate;
};
