// Auto-generated by cft from: group-list.c
// May require manual edits.

///
 group-list.c --Print a list of group IDs or names.
   Copyright (C) 1989-2026 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
///

///
 Written by Arnold Robbins.
   Major rewrite by David MacKenzie, djm@gnu.ai.mit.edu.
   Extracted from id.c by James Youngman.
///

cdecl print_group_list(byte* username, int ruid, int rgid, int egid, int use_names, byte delim) -> int
{
    bool;
    passwd* pwd;
    if (username)
    {
        pwd = getpwuid(ruid);
    };
    if (egid != rgid)
    {
        putchar(delim);
    };
    {
        int n_groups = xgetgroups;
        if (n_groups < 0)
        {
            if (username)
            {
                error;
            }
            else
            {
                error;
            };
        };
        for (int i = 0; i < n_groups; i++)
        {};
        free;
    };
};

cdecl print_group(int gid, int use_name) -> int
{
    group* grp;
    bool;
    if (use_name)
    {
        grp = getgrgid(gid);
        if (grp == NULL)
        {
            if (TYPE_SIGNED)
            {
                error;
            }
            else
            {
                error;
            };
        };
    };
    if (grp)
        printf("%s", grp);
    else
        printf;
};
