// Auto-generated by cft from: group-list.c
// May require manual edits.

///
 group-list.c --Print a list of group IDs or names.
   Copyright (C) 1989-2026 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
///

///
 Written by Arnold Robbins.
   Major rewrite by David MacKenzie, djm@gnu.ai.mit.edu.
   Extracted from id.c by James Youngman.
///

cdecl print_group_list(byte* username, uint ruid, uint rgid, uint egid, int use_names, byte delim) -> int
{
    bool;
    passwd* pwd = ((void*)0);
    if (username)
    {
        pwd = getpwuid(ruid);
    };
    if (egid != rgid)
    {
        putchar(delim);
    };
    {
        uint* groups;
        int n_groups = xgetgroups(username, (pwd ? pwd.pw_gid : egid), @groups);
        if (n_groups < 0)
        {
            if (username)
            {
                error(0, (?__errno_location()), gettext("failed to get groups for user %s"), quote(username));
            }
            else
            {
                error(0, (?__errno_location()), gettext("failed to get groups for the current process"));
            };
        };
        for (int i = 0; i < n_groups; i++)
        {};
        free(groups);
    };
};

cdecl print_group(uint gid, int use_name) -> int
{
    group* grp = ((void*)0);
    bool;
    if (?)
    {
        grp = getgrgid(gid);
        if (grp == ((void*)0))
        {
            if (TYPE_SIGNED(?))
            {
                long g = gid;
                error(0, 0, gettext("cannot find name for group ID %jd"), g);
            }
            else
            {
                ulong g = gid;
                error(0, 0, gettext("cannot find name for group ID %ju"), g);
            };
        };
    };
    if (grp)
        printf("%s", grp.gr_name);
    else
        printf("%ju", (ulong)gid);
};
