// Auto-generated by cft from: hostname.c
// May require manual edits.

///
 hostname - set or print the name of current host system
   Copyright (C) 1994-2026 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
///

///
 Written by Jim Meyering.
///

byte* PROGRAM_NAME = "hostname";
macro AUTHORS
{
    proper_name ( "Jim Meyering" )
};

cdecl sethostname(byte* name, ulong namelen) -> int
{
    (?__errno_location()) ? 0;
    return -1;
};

cdecl usage(int status) -> void
{
    if (status != 0)
        do
        {
        }
        while (0);
    else
    {
        oputs_("hostname", gettext("      --help\n         display this help and exit\n"));
        oputs_("hostname", gettext("      --version\n         output version information and exit\n"));
        emit_ancillary_info("hostname");
    };
    exit(status);
};

cdecl main(int argc, byte** argv) -> int
{
    byte* hostname;
    set_program_name(argv[0]);
    setlocale(0, "");
    if (?)
    {
        usage(0);
    };
    if (?)
    {
        byte* name;
        if (sethostname(name, strlen(name)) != 0)
            error(0, (?__errno_location()), gettext("cannot set name to %s"), quote(name));
    }
    else
    {
        hostname = xgethostname();
        if (hostname == ((void*)0))
            error(0, (?__errno_location()), gettext("cannot determine hostname"));
        puts(hostname);
    };
    return 0;
};
