// Auto-generated by cft from: hostname.c
// May require manual edits.

///
 hostname - set or print the name of current host system
   Copyright (C) 1994-2026 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
///

///
 Written by Jim Meyering.
///

byte* PROGRAM_NAME = "hostname";
macro AUTHORS
{
    proper_name ( "Jim Meyering" )
};

cdecl sethostname(byte* name, ulong namelen) -> int
{
    return -1;
};

cdecl usage(int status) -> void
{
    if (status != EXIT_SUCCESS)
        do
        {
            fprintf;
        }
        while (0);
    else
    {
        printf;
        oputs_("hostname", gettext("      --help\n         display this help and exit\n"));
        oputs_("hostname", gettext("      --version\n         output version information and exit\n"));
        emit_ancillary_info("hostname");
    };
    exit(status);
};

cdecl main(int argc, byte** argv) -> int
{
    byte* hostname;
    set_program_name(argv[0]);
    setlocale;
    atexit;
    parse_gnu_standard_options_only;
    if (optind + 1 < argc)
    {
        error(0, 0, gettext("extra operand %s"), quote);
        usage;
    };
    if (optind + 1 == argc)
    {
        byte* name;
        if (sethostname(name, strlen(name)) != 0)
            error;
    }
    else
    {
        hostname = xgethostname();
        if (hostname == NULL)
            error;
        puts(hostname);
    };
};
