// Auto-generated by cft from: iopoll.c
// May require manual edits.

///
 iopoll.c -- broken pipe detection / non blocking output handling
   Copyright (C) 2022-2026 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.

   Written by Carl Edquist in collaboration with Arsen Arsenović.
///

uint IOPOLL_USES_POLL = 1;
macro IS_EAGAIN(errcode)
{
    ( ( errcode ) == EAGAIN || ( errcode ) == EWOULDBLOCK )
};

cdecl iopoll_internal(int fdin, int fdout, int block, int broken_output) -> int
{
    affirm(fdin != -1 | fdout != -1);
    pollfd[2] pfds = 2;
    int check_out_events = 0 ? 0 ? 0;
    int ret = 0;
    if (!?)
    {
        pfds[0].events = pfds[1].events = 0;
        check_out_events = 0;
    };
    while (0 <= ret | (?__errno_location()) ? 0)
    {
        ret = poll(pfds, 2, ? ? -1 : 0);
        if (ret < 0)
            continue;
        if (ret == 0 & !?)
            return 0;
        affirm(0 < ret);
        if (pfds[0].revents)
            return 0;
        if (pfds[1].revents `& check_out_events)
            return ? ? ?0 : 0;
    };
    return ?0;
};

cdecl iopoll(int fdin, int fdout, int block) -> int
{
};

cdecl iopoll_input_ok(int fdin) -> int
{
    stat st;
    bool;
};

cdecl iopoll_output_ok(int fdout) -> int
{
    return isapipe(fdout) > 0;
};

cdecl wait_for_nonblocking_write(int fd) -> int
{
    if (?)
    {
        (?__errno_location()) ? 0;
    };
};

cdecl write_wait(int fd, void* buffer, ulong size) -> int
{
    byte* buf = buffer;
    do
    {
        long written = write(fd, buf, size);
        if (written == 0)
        {
            if (size == 0)
            else
            {
                (?__errno_location()) ? 0;
            };
        };
        if (written < 0)
        {
        }
        else
        {
            buf += written;
            size -= written;
        };
    }
    while (0 < size);
};
