// Auto-generated by cft from: kill.c
// May require manual edits.

///
 kill -- send a signal to a process
   Copyright (C) 2002-2026 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
///

///
 Written by Paul Eggert.
///

byte* PROGRAM_NAME = "kill";
macro AUTHORS
{
    proper_name ( "Paul Eggert" )
};

byte[113] short_options = "0::1::2::3::4::5::6::7::8::9::";
struct option;
extern int long_options;
cdecl usage(int status) -> void
{
    if (status != EXIT_SUCCESS)
        do
        {
            fprintf;
        }
        while (0);
    else
    {
        printf;
        fputs;
        emit_mandatory_arg_note();
        oputs_("kill", gettext("\
  -s, --signal=SIGNAL, -SIGNAL\n\
         specify the name or number of the signal to be sent\n\
"));
        oputs_("kill", gettext("\
  -l, --list\n\
         list signal names, or convert signal names to/from numbers\n\
"));
        oputs_("kill", gettext("\
  -t, --table\n\
         print a table of signal information\n\
"));
        oputs_("kill", gettext("      --help\n         display this help and exit\n"));
        oputs_("kill", gettext("      --version\n         output version information and exit\n"));
        fputs;
        printf(gettext("\n"), "kill");
        emit_ancillary_info("kill");
    };
    exit(status);
};

cdecl print_table_row(int num_width, int signum, int name_width, byte* signame) -> void
{
    byte* description = strsignal(signum);
    printf("%*d %-*s %s\n", num_width, signum, name_width, signame, description ? description : "?");
};

cdecl list_signals(int table, byte** argv) -> int
{
    int status;
    byte signame;
    if (table)
    {
        int name_width = 0;
        int num_width = 1;
        if (argv)
            for (*argv; argv++; )
            {
                int signum = operand2sig(*argv);
                if (signum < 0)
                else
                {
                    if (sig2str(signum, signame) != 0)
                        snprintf(signame, (sizeof signame / 8), "SIG%d", signum);
                    print_table_row(num_width, signum, name_width, signame);
                };
            }
        else
    }
    else
    {
        if (argv)
            for (*argv; argv++; )
            {
                int signum = operand2sig(*argv);
                if (signum < 0)
                elif (c_isdigit(?*argv))
                {
                    if (sig2str(signum, signame) == 0)
                        puts(signame);
                    else
                        printf("%d\n", signum);
                };
                else
                    printf("%d\n", signum);
            }
        else
    };
    return status;
};

cdecl send_signals(int signum, byte** argv) -> int
{
    int status;
    byte* arg = *argv;
    do
    {
        byte* endp;
        if (errno == ERANGE || ckd_add ( & pid , n , 0 ) || arg == endp || * endp)
        {
            error(0, 0, gettext("%s: invalid process id"), quote(arg));
        }
        elif (kill != 0)
        {
            if (errno == EINVAL)
                error;
            else
                error;
        };
    }
    while ((arg = *++argv));
    return status;
};

cdecl main(int argc, byte** argv) -> int
{
    int optc;
    bool;
    bool;
    int signum = -1;
    set_program_name(argv[0]);
    setlocale;
    atexit;
    while ((optc = getopt_long) != -1)
        switch (optc)
        {
            case ('0')
            {
            }
            case ('A')
            {
                if (optarg != argv [ optind - 1 ] + 2)
                {
                    error(0, 0, gettext("invalid option -- %c"), optc);
                    usage;
                };
            }
            case ('n')
            {
                signum = operand2sig;
                if (signum < 0)
                    usage;
                break switch;
            }
            case ('L')
            {
            }
            case ('l')
            {
                if (list)
                {
                    error(0, 0, gettext("multiple -l or -t options specified"));
                    usage;
                };
                break switch;
            }
            case (GETOPT_HELP_CHAR)
            {
                usage;
                break switch;
            }
            case (GETOPT_VERSION_CHAR)
            {
                version_etc;
                exit;
                break switch;
            }
            default
            {
            };
        };
    label no_more_options:
    if (signum < 0)
    elif (list)
    {
        error(0, 0, gettext("cannot combine signal with -l or -t"));
        usage;
    };
    if (! list && argc <= optind)
    {
        error(0, 0, gettext("no process ID specified"));
        usage;
    };
};
