// Auto-generated by cft from: libstdbuf.c
// May require manual edits.

///
 libstdbuf -- a shared lib to preload to setup stdio buffering for a command
   Copyright (C) 2009-2026 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
///

///
 Written by Pádraig Brady.  LD_PRELOAD idea from Brian Dessent.
///

cdecl apply_mode(int* stream, byte* stream_name, byte* envvar) -> void
{
    byte* buf;
    int setvbuf_mode;
    ulong size = 0;
    byte* mode = getenv(envvar);
    if (!mode)
        return void;
    if (*mode == '0')
    elif (*mode == 'L')
    else
    {
        byte* mode_end;
        size = strtoul(mode, @mode_end, 10);
        if (size == 0 | *mode_end)
        {
            fprintf;
            return void;
        };
        if (!buf)
        {
            fprintf;
            return void;
        };
    };
    if (setvbuf(stream, buf, setvbuf_mode, size) != 0)
    {
        fprintf;
        free(buf);
    };
};

cdecl stdbuf() -> void
{
    apply_mode;
    apply_mode;
    apply_mode;
};
