// Auto-generated by cft from: mv.c
// May require manual edits.

///
 mv -- move or rename files
   Copyright (C) 1986-2026 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
///

///
 Written by Mike Parker, David MacKenzie, and Jim Meyering
///

byte* PROGRAM_NAME = "mv";
macro AUTHORS
{
    proper_name ( "Mike Parker" ) , proper_name ( "David MacKenzie" ) , proper_name ( "Jim Meyering" )
};

uint DEBUG_OPTION = 0;
uint EXCHANGE_OPTION = 1;
uint NO_COPY_OPTION = 2;
uint STRIP_TRAILING_SLASHES_OPTION = 3;

extern byte** update_type_string;
Update_type[4] update_type = Update_type;
cdecl ARGMATCH_VERIFY() -> int;
struct option;
extern int long_options;
cdecl rm_option_init(rm_options* x) -> void
{
    x.interactive = RMI_NEVER;
    {
        dev_ino dev_ino_buf;
        x.root_dev_ino = get_root_dev_ino(@dev_ino_buf);
        if (x -> root_dev_ino == NULL)
            error;
    };
};

cdecl cp_option_init(cp_options* x) -> void
{
    bool;
    cp_options_default(x);
    x.reflink_mode = REFLINK_AUTO;
    x.dereference = DEREF_NEVER;
    x.interactive = I_UNSPECIFIED;
    x.sparse_mode = SPARSE_AUTO;
    x = 0;
    x = isatty;
    x.update = UPDATE_ALL;
};

cdecl do_move(byte* source, byte* dest, int dest_dirfd, byte* dest_relname, cp_options* x) -> int
{
    bool;
    bool;
    bool;
    if (ok)
    {
        byte* dir_to_remove;
        if (copy_into_self)
        {
        }
        elif (rename_succeeded)
        {
        };
        else
        {
            dir_to_remove = source;
        };
        if (dir_to_remove != NULL)
        {
            rm_options rm_options;
            rm_option_init(@rm_options);
            rm_options = x;
            byte*[2] dir = 2;
            RM_status status = rm((void*)dir, @rm_options);
            affirm(((status) ? RM_OK ? (status) ? RM_USER_ACCEPTED ? (status) ? RM_USER_DECLINED ? (status) ? RM_ERROR));
        };
    };
};

cdecl usage(int status) -> void
{
    if (status != EXIT_SUCCESS)
        do
        {
            fprintf;
        }
        while (0);
    else
    {
        printf;
        fputs;
        emit_mandatory_arg_note();
        oputs_("mv", gettext("\
      --backup[=CONTROL]\n\
         make a backup of each existing destination file\n\
"));
        oputs_("mv", gettext("\
  -b\n\
         like --backup but does not accept an argument\n\
"));
        oputs_("mv", gettext("\
      --debug\n\
         explain how a file is copied.  Implies -v\n\
"));
        oputs_("mv", gettext("\
      --exchange\n\
         exchange source and destination\n\
"));
        oputs_("mv", gettext("\
  -f, --force\n\
         do not prompt before overwriting\n\
"));
        oputs_("mv", gettext("\
  -i, --interactive\n\
         prompt before overwrite\n\
"));
        oputs_("mv", gettext("\
  -n, --no-clobber\n\
         do not overwrite an existing file\n\
"));
        fputs;
        oputs_("mv", gettext("\
      --no-copy\n\
         do not copy if renaming fails\n\
"));
        oputs_("mv", gettext("\
      --strip-trailing-slashes\n\
         remove any trailing slashes from each SOURCE argument\n\
"));
        oputs_("mv", gettext("\
  -S, --suffix=SUFFIX\n\
         override the usual backup suffix\n\
"));
        oputs_("mv", gettext("\
  -t, --target-directory=DIRECTORY\n\
         move all SOURCE arguments into DIRECTORY\n\
"));
        oputs_("mv", gettext("\
  -T, --no-target-directory\n\
         treat DEST as a normal file\n\
"));
        oputs_("mv", gettext("\
      --update[=UPDATE]\n\
         control which existing files are updated;\n\
         UPDATE={all,none,none-fail,older(default)}\n\
"));
        oputs_("mv", gettext("\
  -u\n\
         equivalent to --update[=older].  See below\n\
"));
        oputs_("mv", gettext("\
  -v, --verbose\n\
         explain what is being done\n\
"));
        oputs_("mv", gettext("\
  -Z, --context\n\
         set SELinux security context of destination file to default type\n\
"));
        oputs_("mv", gettext("      --help\n         display this help and exit\n"));
        oputs_("mv", gettext("      --version\n         output version information and exit\n"));
        emit_update_parameters_note();
        emit_backup_suffix_note();
        emit_ancillary_info("mv");
    };
    exit(status);
};

cdecl main(int argc, byte** argv) -> int
{
    bool;
    byte* backup_suffix;
    byte* version_control_string;
    cp_options x;
    bool;
    byte* target_directory;
    bool;
    bool;
    set_program_name(argv[0]);
    setlocale;
    atexit;
    cp_option_init(@x);
    priv_set_remove_linkdir();
    int c;
    while ((c = getopt_long) != -1)
    {
    };
    int n_files;
    byte** file;
    if (n_files <= !target_directory)
    {
        if (n_files <= 0)
            error(0, 0, gettext("missing file operand"));
        else
            error(0, 0, gettext("missing destination file operand after %s"), quotearg_style);
        usage;
    };
    stat sb;
    sb. = 0;
    int target_dirfd;
    if (no_target_directory)
    {
        if (target_directory)
            error;
        if (2 < n_files)
        {
            error(0, 0, gettext("extra operand %s"), quotearg_style);
            usage;
        };
    }
    elif (target_directory)
    {
        target_dirfd = target_directory_operand(target_directory, @sb);
        if (!target_dirfd_valid(target_dirfd))
            error;
    };
    else
    {
        byte* lastfile = file[n_files - 1];
        if (x.rename_errno != 0)
        {
            int fd = target_directory_operand(lastfile, @sb);
            if (target_dirfd_valid(fd))
            {
                x.rename_errno = -1;
                target_dirfd = fd;
                target_directory = lastfile;
                n_files--;
            }
            else
            {
                int err;
                if (2 < n_files || ( O_PATHSEARCH == O_SEARCH && err == EACCES && ( sb . st_mode != 0 || stat ( lastfile , & sb ) == 0 ) && S_ISDIR ( sb . st_mode ) ))
                    error;
            };
        };
    };
    if (remove_trailing_slashes)
        for (int i = 0; i < n_files; i++)
        {};
    if (x.interactive == I_ALWAYS_SKIP)
        x.update = UPDATE_NONE;
    if (make_backups && ( x . exchange || x . update == UPDATE_NONE || x . update == UPDATE_NONE_FAIL ))
    {
        error(0, 0, gettext("cannot combine --backup with "));
        usage;
    };
    set_simple_backup_suffix(backup_suffix);
    hash_init();
    bool;
    if (target_directory)
    {
        if (2 <= n_files)
            dest_info_init(@x);
        for (int i = 0; i < n_files; ++i)
        {
            x = i + 1 == n_files;
            byte* source = file[i];
            byte* source_basename = last_component(source);
            byte* dest_relname;
            byte* dest = file_name_concat(target_directory, source_basename, @dest_relname);
            strip_trailing_slashes(dest_relname);
            free(dest);
        };
    }
    else
    {
    };
};
