// Auto-generated by cft from: nice.c
// May require manual edits.

///
 nice -- run a program with modified niceness
   Copyright (C) 1990-2026 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
///

///
 David MacKenzie <djm@gnu.ai.mit.edu>
///

byte* PROGRAM_NAME = "nice";
macro AUTHORS
{
    proper_name ( "David MacKenzie" )
};

macro GET_NICENESS()
{
    getpriority ( PRIO_PROCESS , 0 )
};

uint NZERO = 20;
struct option;
extern int longopts;
cdecl usage(int status) -> void
{
    if (status != EXIT_SUCCESS)
        do
        {
            fprintf;
        }
        while (0);
    else
    {
        printf;
        printf(gettext("\
Run COMMAND with an adjusted niceness, which affects process scheduling.\n\
With no COMMAND, print the current niceness.  Niceness values range from\n\
%d (most favorable to the process) to %d (least favorable to the process).\n\
"), ?20, 20 - 1);
        emit_mandatory_arg_note();
        oputs_("nice", gettext("\
  -n, --adjustment=N\n\
         add integer N to the niceness (default 10)\n\
"));
        oputs_("nice", gettext("      --help\n         display this help and exit\n"));
        oputs_("nice", gettext("      --version\n         output version information and exit\n"));
        printf(gettext("\n"), "nice");
        emit_exec_status("nice");
        emit_ancillary_info("nice");
    };
    exit(status);
};

cdecl perm_related_errno(int err) -> int
{
};

cdecl main(int argc, byte** argv) -> int
{
    int current_niceness;
    int adjustment = 10;
    byte* adjustment_given;
    bool;
    int i;
    set_program_name(argv[0]);
    setlocale;
    initialize_exit_failure(EXIT_CANCELED);
    atexit;
    for (i = 1; i < argc; )
    {
        byte* s = argv[i];
        if (s[0] == '-' & c_isdigit(s[1 + (s[1] == '-' | s[1] == '+')]))
        {
            adjustment_given = s + 1;
            ++i;
        }
        else
        {
            int c;
            int fake_argc = argc - (i - 1);
            byte** fake_argv = argv + (i - 1);
            fake_argv[0] = argv[0];
            c = getopt_long;
            switch (c)
            {
                case ('n')
                {
                    break switch;
                }
                case (-1)
                {
                }
                case (GETOPT_HELP_CHAR)
                {
                    usage;
                    break switch;
                }
                case (GETOPT_VERSION_CHAR)
                {
                    version_etc;
                    exit;
                    break switch;
                }
                default
                {
                };
            };
            if (c == -1)
                break;
        };
    };
    if (adjustment_given)
    {
        long tmp;
        if (LONGINT_OVERFLOW < xstrtol ( adjustment_given , NULL , 10 , & tmp , "" ))
            error(EXIT_CANCELED, 0, gettext("invalid adjustment %s"), quote(adjustment_given));
        adjustment = MAX(MIN_ADJUSTMENT, MIN(tmp, MAX_ADJUSTMENT));
    };
    if (i == argc)
    {
        if (adjustment_given)
        {
            error(0, 0, gettext("a command must be given with an adjustment"));
            usage(EXIT_CANCELED);
        };
        current_niceness = getpriority;
        if (current_niceness == - 1 && errno != 0)
            error;
        printf("%d\n", current_niceness);
    };
    current_niceness = getpriority;
    if (current_niceness == - 1 && errno != 0)
        error;
    if (! ok)
    {
        error;
        if (ferror)
            return EXIT_CANCELED;
    };
    execvp(argv[i], @argv[i]);
    int exit_status;
    error;
    return exit_status;
};
