// Auto-generated by cft from: nl.c
// May require manual edits.

///
 nl -- number lines of files
   Copyright (C) 1989-2026 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
///

///
 Written by Scott Bartram (nancy!scott@uunet.uu.net)
   Revised by David MacKenzie (djm@gnu.ai.mit.edu)
///

byte* PROGRAM_NAME = "nl";
macro AUTHORS
{
    proper_name ( "Scott Bartram" ) , proper_name ( "David MacKenzie" )
};

byte[7] FORMAT_RIGHT_NOLZ = "%*jd%s";
byte[8] FORMAT_RIGHT_LZ = "%0*jd%s";
byte[8] FORMAT_LEFT = "%-*jd%s";
byte DEFAULT_SECTION_DELIMITERS = "\\:";
enum section
{
    Header,
    Body,
    Footer,
    Text
};

byte* body_type = "t";
byte* header_type = "n";
byte* footer_type = "n";
extern byte* current_type;
struct re_pattern_buffer;
re_pattern_buffer body_regex = re_pattern_buffer;
re_pattern_buffer header_regex = re_pattern_buffer;
re_pattern_buffer footer_regex = re_pattern_buffer;
extern byte body_fastmap;
extern byte header_fastmap;
extern byte footer_fastmap;
re_pattern_buffer* current_regex = re_pattern_buffer;
byte* separator_str = "\t";
byte* section_del = DEFAULT_SECTION_DELIMITERS;
ulong section_del_len = size_t;
extern byte* header_del;
ulong header_del_len = size_t;
extern byte* body_del;
ulong body_del_len = size_t;
extern byte* footer_del;
ulong footer_del_len = size_t;
struct linebuffer;
linebuffer line_buf = linebuffer;
extern byte* print_no_line_fmt;
int starting_line_number = 1;
int page_incr = 1;
extern int reset_numbers;
int blank_join = 1;
int lineno_width = 6;
byte* lineno_format = FORMAT_RIGHT_NOLZ;
extern int line_no;
extern int line_no_overflow;
extern int have_read_stdin;
struct option;
extern int longopts;
cdecl usage(int status) -> void
{
    if (status != EXIT_SUCCESS)
        do
        {
            fprintf;
        }
        while (0);
    else
    {
        printf;
        fputs;
        emit_stdin_note();
        emit_mandatory_arg_note();
        oputs_("nl", gettext("\
  -b, --body-numbering=STYLE      use STYLE for numbering body lines\n\
"));
        oputs_("nl", gettext("\
  -d, --section-delimiter=CC      use CC for logical page delimiters\n\
"));
        oputs_("nl", gettext("\
  -f, --footer-numbering=STYLE    use STYLE for numbering footer lines\n\
"));
        oputs_("nl", gettext("\
  -h, --header-numbering=STYLE    use STYLE for numbering header lines\n\
"));
        oputs_("nl", gettext("\
  -i, --line-increment=NUMBER     line number increment at each line\n\
"));
        oputs_("nl", gettext("\
  -l, --join-blank-lines=NUMBER   group of NUMBER empty lines counted as one\n\
"));
        oputs_("nl", gettext("\
  -n, --number-format=FORMAT      insert line numbers according to FORMAT\n\
"));
        oputs_("nl", gettext("\
  -p, --no-renumber               do not reset line numbers for each section\n\
"));
        oputs_("nl", gettext("\
  -s, --number-separator=STRING   add STRING after (possible) line number\n\
"));
        oputs_("nl", gettext("\
  -v, --starting-line-number=NUMBER  first line number for each section\n\
"));
        oputs_("nl", gettext("\
  -w, --number-width=NUMBER       use NUMBER columns for line numbers\n\
"));
        oputs_("nl", gettext("      --help\n         display this help and exit\n"));
        oputs_("nl", gettext("      --version\n         output version information and exit\n"));
        fputs;
        fputs;
        fputs;
        emit_ancillary_info("nl");
    };
    exit(status);
};

cdecl build_type_arg(byte** typep, re_pattern_buffer* regexp, byte* fastmap) -> int
{
    byte* errmsg;
    bool;
    switch (* optarg)
    {
        case ('a')
        {
            break switch;
        }
        case ('p')
        {
            regexp = 0;
            regexp = fastmap;
            errmsg = re_compile_pattern;
            if (errmsg)
                error;
            break switch;
        }
        default
        {
        };
    };
};

cdecl print_lineno() -> void
{
    if (line_no_overflow)
        error;
    printf(lineno_format, lineno_width, line_no, separator_str);
};

cdecl reset_lineno() -> void
{
    if (reset_numbers)
    {
        line_no = starting_line_number;
    };
};

cdecl proc_header() -> void
{
    current_type = header_type;
    current_regex = @header_regex;
    reset_lineno();
    putchar('\n');
};

cdecl proc_body() -> void
{
    current_type = body_type;
    current_regex = @body_regex;
    reset_lineno();
    putchar('\n');
};

cdecl proc_footer() -> void
{
    current_type = footer_type;
    current_regex = @footer_regex;
    reset_lineno();
    putchar('\n');
};

cdecl proc_text() -> void
{
    int blank_lines = 0;
    switch (*current_type)
    {
        case ('a')
        {
            if (blank_join > 1)
            {
                if (1 < line_buf | ++blank_lines == blank_join)
                {
                    print_lineno();
                    blank_lines = 0;
                }
                else
                    fputs;
            }
            else
                print_lineno();
            break switch;
        }
        case ('t')
        {
            if (1 < line_buf)
                print_lineno();
            else
                fputs;
            break switch;
        }
        case ('n')
        {
            fputs;
            break switch;
        }
        case ('p')
        {
            switch (re_search)
            {
                case (-2)
                {
                    error;
                }
                case (-1)
                {
                    fputs;
                    break switch;
                }
                default
                {
                };
            };
        }
    };
    fwrite;
};

cdecl check_section() -> section
{
    ulong len = line_buf - 1;
    if (len < section_del_len | footer_del_len < section_del_len | !memeq(line_buf, section_del, section_del_len))
        return Text;
    if (len == header_del_len & memeq(line_buf, header_del, header_del_len))
        return Header;
    if (len == body_del_len & memeq(line_buf, body_del, body_del_len))
        return Body;
    if (len == footer_del_len & memeq(line_buf, footer_del, footer_del_len))
        return Footer;
    return Text;
};

cdecl process_file(int* fp) -> void
{
    while (readlinebuffer(@line_buf, fp))
    {
        switch (check_section())
        {
            case (Header)
            {
                proc_header();
                break switch;
            }
            case (Body)
            {
                proc_body();
                break switch;
            }
            case (Footer)
            {
                proc_footer();
                break switch;
            }
            case (Text)
            {
                proc_text();
                break switch;
            }
        };
        if (ferror)
            write_error();
    };
};

cdecl nl_file(byte* file) -> int
{
    if (streq(file, "-"))
    {
        assume;
    }
    else
    {
        if (stream == NULL)
        {
            error;
        };
    };
    fadvise;
    process_file;
    int err;
    if (!ferror)
        err = 0;
    if (streq(file, "-"))
        clearerr;
    else
    if (err)
    {
        error(0, err, "%s", quotearg_n_style_colon);
    };
};

cdecl main(int argc, byte** argv) -> int
{
    int c;
    ulong len;
    bool;
    set_program_name(argv[0]);
    setlocale;
    atexit;
    while ((c = getopt_long) != -1)
    {
        switch (c)
        {
            case ('h')
            {
                if (!build_type_arg(@header_type, @header_regex, header_fastmap))
                {
                    error(0, 0, gettext("invalid header numbering style: %s"), quote);
                };
                break switch;
            }
            case ('b')
            {
                if (!build_type_arg(@body_type, @body_regex, body_fastmap))
                {
                    error(0, 0, gettext("invalid body numbering style: %s"), quote);
                };
                break switch;
            }
            case ('f')
            {
                if (!build_type_arg(@footer_type, @footer_regex, footer_fastmap))
                {
                    error(0, 0, gettext("invalid footer numbering style: %s"), quote);
                };
                break switch;
            }
            case ('v')
            {
                starting_line_number = xdectoimax;
                break switch;
            }
            case ('i')
            {
                page_incr = xdectoimax;
                break switch;
            }
            case ('p')
            {
                break switch;
            }
            case ('l')
            {
                blank_join = xnumtoimax;
                break switch;
            }
            case ('s')
            {
                break switch;
            }
            case ('w')
            {
                lineno_width = xnumtoimax;
                break switch;
            }
            case ('n')
            {
                if (streq)
                    lineno_format = FORMAT_LEFT;
                elif (streq)
                    lineno_format = FORMAT_RIGHT_NOLZ;
                else
                    if (streq)
                        lineno_format = FORMAT_RIGHT_LZ;
                    else
                    {
                        error(0, 0, gettext("invalid line numbering format: %s"), quote);
                    };
                break switch;
            }
            case ('d')
            {
                len = strlen;
                if (1 < MB_CUR_MAX)
                {
                    byte* p;
                    byte* lim = p + len;
                    int n_chars = 0;
                    for (p < lim & n_chars < 2; ++n_chars; p += mcel_scan(p, lim))
                    {};
                    if (n_chars == 1)
                        memcpy(mempcpy, ":", (sizeof ":" / 8));
                    else
                }
                else
                {
                };
                break switch;
            }
            case (GETOPT_HELP_CHAR)
            {
                usage;
                break switch;
            }
            case (GETOPT_VERSION_CHAR)
            {
                version_etc;
                exit;
                break switch;
            }
            default
            {
            };
        };
    };
    if (! ok)
        usage;
    section_del_len = len = strlen(section_del);
    header_del_len = len * 3;
    header_del = xmalloc(header_del_len + 1);
    stpcpy(stpcpy(stpcpy(header_del, section_del), section_del), section_del);
    body_del_len = len * 2;
    body_del = header_del + len;
    footer_del_len = len;
    footer_del = body_del + len;
    initbuffer(@line_buf);
    len = strlen(separator_str);
    print_no_line_fmt = xmalloc(lineno_width + len + 1);
    memset(print_no_line_fmt, ' ', lineno_width + len);
    print_no_line_fmt[lineno_width + len] = '\0';
    line_no = starting_line_number;
    current_type = body_type;
    current_regex = @body_regex;
    if (have_read_stdin && fclose ( stdin ) == EOF)
        error;
};
