// Auto-generated by cft from: od.c
// May require manual edits.

///
 od -- dump files in octal and other formats
   Copyright (C) 1992-2026 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
///

///
 Written by Jim Meyering.
///

byte* PROGRAM_NAME = "od";
macro AUTHORS
{
    proper_name ( "Jim Meyering" )
};

uint DEFAULT_BYTES_PER_BLOCK = 16;
uint FLOAT16_SUPPORTED = 0;
uint BF16_SUPPORTED = 0;
// macro (multi-statement, manual translation needed): PRINT_FIELDS(N, T, FMT_STRING_DECL, ACTION) static void N ( idx_t fields , idx_t blank , void const * block , FMT_STRING_DECL , int width , idx_t pad ) \
{ T const * p = block ; idx_t pad_remaining = pad ; for ( idx_t i = fields ; blank < i ; i -- ) { idx_t next_pad = pad_at ( fields , i - 1 , pad ) ; int adjusted_width = pad_remaining - next_pad + width ; T x ; if ( input_swap && sizeof ( T ) > 1 ) { union { T x ; char b [ sizeof ( T ) ] ; } u ; for ( idx_t j = 0 ; j < sizeof ( T ) ; j ++ ) u . b [ j ] = ( ( char const * ) p ) [ sizeof ( T ) - 1 - j ] ; x = u . x ; } else x = * p ; p ++ ; ACTION ; pad_remaining = next_pad ; } \
}
macro PRINT_TYPE(N, T)
{
    PRINT_FIELDS ( N , T , char const * fmt_string , xprintf ( fmt_string , adjusted_width , x ) )
};

// macro (multi-statement, manual translation needed): PRINT_FLOATTYPE(N, T, FTOASTR, BUFSIZE) PRINT_FIELDS ( N , T , MAYBE_UNUSED char const * fmt_string , char buf [ BUFSIZE ] ; FTOASTR ( buf , sizeof buf , 0 , 0 , x ) ; xprintf ( "%*s" , adjusted_width , buf ) )
// macro (multi-statement, manual translation needed): CASE_OLD_ARG(old_char, new_string) case old_char : ok &= decode_format_string ( new_string ) ; break
// typedef: float16 = float
// typedef: bfloat16 = float
enum size_spec
{
    NO_SIZE = 0,
    CHAR = 1,
    SHORT = 2,
    INT = 3,
    LONG = 4,
    LONG_LONG = 4,
    INTMAX = 4,
    FLOAT_HALF = 5,
    FLOAT_SINGLE = 5,
    FLOAT_DOUBLE = 6,
    FLOAT_LONG_DOUBLE = 7,
    N_SIZE_SPECS = 8
};

enum output_format
{
    SIGNED_DECIMAL,
    UNSIGNED_DECIMAL,
    OCTAL,
    HEXADECIMAL,
    FLOATING_POINT,
    HFLOATING_POINT,
    BFLOATING_POINT,
    NAMED_CHARACTER,
    CHARACTER
};

uint MAX_INTEGRAL_TYPE_WIDTH = 0;

uint FMT_BYTES_ALLOCATED = 0;

cdecl static_assert(int) -> int;
cdecl{}* print_function_type(int fields, int blank, void* dat, byte* fmt, int width, int pad) -> void;

struct tspec
{
    output_format fmt;
    size_spec size;
    def{}*(int, int, void*, byte*, int, int) -> void print_function;
    byte[0] fmt_string;
    int hexl_mode_trailer;
    int field_width;
    int pad_width;
};

int[8] width_bytes = {-1, (sizeof ( unsigned char ) / 8), (sizeof ( unsigned short int ) / 8), (sizeof ( unsigned int ) / 8), (sizeof ( unsigned long int ) / 8), (sizeof ( float ) / 8), (sizeof ( double ) / 8), (sizeof ( long double ) / 8)};
byte[4][33] charname = 4;
int address_base = 8;
uint MAX_ADDRESS_LENGTH = 0;

int address_pad_len = 7;
extern int string_min;
extern int flag_dump_strings;
extern int traditional;
extern int flag_pseudo_start;
long pseudo_offset = intmax_t;
cdecl format_address_std(long, byte) -> void;
def{}*(long, byte) -> void format_address = intmax_t;
long n_bytes_to_skip = intmax_t;
long end_offset = intmax_t;
extern int abbreviate_duplicate_blocks;
tspec* spec = tspec;
extern int n_specs;
extern int n_specs_allocated;
extern int bytes_per_block;
extern byte* input_filename;
extern byte** file_list;
byte*[2] default_file_list = {"-", ((void*)0)};
_IO_FILE* in_stream = FILE;
extern int have_read_stdin;
size_spec[9] integral_type_size = size_spec;
size_spec[17] fp_type_size = size_spec;
extern int input_swap;
byte[35] short_options = "A:aBbcDdeFfHhIij:LlN:OoS:st:vw::Xx";
uint TRADITIONAL_OPTION = 128;
uint ENDIAN_OPTION = 129;

enum endian_type
{
    endian_little,
    endian_big
};

byte*[3] endian_args = {"little", "big", ((void*)0)};
endian_type[2] endian_types = endian_type;
option[12] long_options = option;
cdecl usage(int status) -> void
{
    if (status != 0)
        do
        {
        }
        while (0);
    else
    {
        fputs(gettext("\n\
Write an unambiguous representation, octal bytes by default,\n\
of FILE to standard output.  With more than one FILE argument,\n\
concatenate them in the listed order to form the input.\n\
"), stdout);
        emit_stdin_note();
        fputs(gettext("\
\n\
If first and second call formats both apply, the second format is assumed\n\
if the last operand begins with + or (if there are 2 operands) a digit.\n\
An OFFSET operand means -j OFFSET.  LABEL is the pseudo-address\n\
at first byte printed, incremented when dump is progressing.\n\
For OFFSET and LABEL, a 0x or 0X prefix indicates hexadecimal;\n\
suffixes may be . for octal and b for multiply by 512.\n\
"), stdout);
        emit_mandatory_arg_note();
        oputs_("od", gettext("\
  -A, --address-radix=RADIX\n\
         output format for file offsets;\n\
         RADIX is one of [doxn], for Decimal, Octal, Hex or None\n\
"));
        oputs_("od", gettext("\
      --endian={big|little}\n\
         swap input bytes according the specified order\n\
"));
        oputs_("od", gettext("\
  -j, --skip-bytes=BYTES\n\
         skip BYTES input bytes first\n\
"));
        oputs_("od", gettext("\
  -N, --read-bytes=BYTES\n\
         limit dump to BYTES input bytes\n\
"));
        oputs_("od", gettext("\
  -S BYTES, --strings[=BYTES]\n\
         show only NUL terminated strings\n\
         of at least BYTES (default 3) printable characters\n\
"));
        oputs_("od", gettext("\
  -t, --format=TYPE\n\
         select output format or formats\n\
"));
        oputs_("od", gettext("\
  -v, --output-duplicates\n\
         do not use * to mark line suppression\n\
"));
        oputs_("od", gettext("\
  -w[BYTES], --width[=BYTES]\n\
         output BYTES bytes per output line;\n\
         32 is implied when BYTES is not specified\n\
"));
        oputs_("od", gettext("\
      --traditional\n\
         accept arguments in third form above\n\
"));
        oputs_("od", gettext("      --help\n         display this help and exit\n"));
        oputs_("od", gettext("      --version\n         output version information and exit\n"));
        fputs(gettext("\
\n\
\n\
Traditional format specifications may be intermixed; they accumulate:\n\
"), stdout);
        oputs_("od", gettext("\
  -a   same as -t a,  select named characters, ignoring high-order bit\n\
"));
        oputs_("od", gettext("\
  -b   same as -t o1, select octal bytes\n\
"));
        oputs_("od", gettext("\
  -c   same as -t c,  select printable characters or backslash escapes\n\
"));
        oputs_("od", gettext("\
  -d   same as -t u2, select unsigned decimal 2-byte units\n\
"));
        oputs_("od", gettext("\
  -f   same as -t fF, select floats\n\
"));
        oputs_("od", gettext("\
  -i   same as -t dI, select decimal ints\n\
"));
        oputs_("od", gettext("\
  -l   same as -t dL, select decimal longs\n\
"));
        oputs_("od", gettext("\
  -o   same as -t o2, select octal 2-byte units\n\
"));
        oputs_("od", gettext("\
  -s   same as -t d2, select decimal 2-byte units\n\
"));
        oputs_("od", gettext("\
  -x   same as -t x2, select hexadecimal 2-byte units\n\
"));
        fputs(gettext("\
\n\
\n\
TYPE is made up of one or more of these specifications:\n\
  a          named character, ignoring high-order bit\n\
  c          printable character or backslash escape\n\
"), stdout);
        fputs(gettext("\
  d[SIZE]    signed decimal, SIZE bytes per integer\n\
  f[SIZE]    floating point, SIZE bytes per float\n\
  o[SIZE]    octal, SIZE bytes per integer\n\
  u[SIZE]    unsigned decimal, SIZE bytes per integer\n\
  x[SIZE]    hexadecimal, SIZE bytes per integer\n\
"), stdout);
        fputs(gettext("\
\n\
SIZE is a number.  For TYPE in [doux], SIZE may also be C for\n\
sizeof(char), S for sizeof(short), I for sizeof(int) or L for\n\
sizeof(long).  If TYPE is f, SIZE may also be B for Brain 16 bit,\n\
H for Half precision float, F for sizeof(float), D for sizeof(double),\n\
or L for sizeof(long double).\n\
"), stdout);
        fputs(gettext("\
\n\
Adding a z suffix to any type displays printable characters at the end of\n\
each output line.\n\
"), stdout);
        fputs(gettext("\
\n\
\n\
BYTES is hex with 0x or 0X prefix, and may have a multiplier suffix:\n\
  b    512\n\
  KB   1000\n\
  K    1024\n\
  MB   1000*1000\n\
  M    1024*1024\n\
and so on for G, T, P, E, Z, Y, R, Q.\n\
Binary prefixes can be used, too: KiB=K, MiB=M, and so on.\n\
"), stdout);
        emit_ancillary_info("od");
    };
    exit(status);
};

cdecl print_n_spaces(long n) -> void
{
    for (0 < n; n--; putchar(' '))
    {};
};

cdecl pad_at(int fields, int i, int pad) -> int
{
    long m = ? % ?;
    return ? / ? * ? + m * ? / ?;
};

cdecl pad_at_overflow(int fields) -> int
{
    long product;
    return __builtin_mul_overflow((? ? 1), (? ? 1), (@product));
};

cdecl print_s_char(int fields, int blank, void* block, byte* fmt_string, int width, int pad) -> void
{
    byte* p = block;
};

cdecl print_char(int fields, int blank, void* block, byte* fmt_string, int width, int pad) -> void
{
    byte* p = block;
};

cdecl print_s_short(int fields, int blank, void* block, byte* fmt_string, int width, int pad) -> void
{
    int* p = block;
};

cdecl print_short(int fields, int blank, void* block, byte* fmt_string, int width, int pad) -> void
{
    uint* p = block;
};

cdecl print_int(int fields, int blank, void* block, byte* fmt_string, int width, int pad) -> void
{
    uint* p = block;
};

cdecl print_long(int fields, int blank, void* block, byte* fmt_string, int width, int pad) -> void
{
    ulong* p = block;
};

cdecl print_long_long(int fields, int blank, void* block, byte* fmt_string, int width, int pad) -> void
{
    ulong* p = block;
};

cdecl print_intmax(int fields, int blank, void* block, byte* fmt_string, int width, int pad) -> void
{
    ulong* p = block;
};

cdecl print_bfloat(int fields, int blank, void* block, int* fmt_string, int width, int pad) -> void
{
    float* p = block;
};

cdecl print_halffloat(int fields, int blank, void* block, int* fmt_string, int width, int pad) -> void
{
    float* p = block;
};

cdecl print_float(int fields, int blank, void* block, int* fmt_string, int width, int pad) -> void
{
    float* p = block;
};

cdecl print_double(int fields, int blank, void* block, int* fmt_string, int width, int pad) -> void
{
    double* p = block;
};

cdecl print_long_double(int fields, int blank, void* block, int* fmt_string, int width, int pad) -> void
{
    double* p = block;
};

cdecl dump_hexl_mode_trailer(int n_bytes, byte* block) -> void
{
    fputs("  >", stdout);
    putchar('<');
};

cdecl print_named_ascii(int fields, int blank, void* block, int* unused_fmt_string, int width, int pad) -> void
{
    byte* p = block;
};

cdecl print_ascii(int fields, int blank, void* block, int* unused_fmt_string, int width, int pad) -> void
{
    byte* p = block;
};

cdecl simple_strtoi(byte* s, byte** p, int* val) -> int
{
    int sum;
    *p = s;
    *val = sum;
};

cdecl ispec_to_format(size_spec size_spec, byte* int_format, byte* long_format, byte* long_long_format, byte* intmax_format) -> byte*
{
    return (LONG < INTMAX & size_spec == INTMAX ? intmax_format : LONG < LONG_LONG & size_spec == LONG_LONG ? long_long_format : INT < LONG & size_spec == LONG ? long_format : int_format);
};
