// Auto-generated by cft from: paste.c
// May require manual edits.

///
 paste - merge lines of files
   Copyright (C) 1997-2026 Free Software Foundation, Inc.
   Copyright (C) 1984 David M. Ihnat

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
///

///
 Written by David Ihnat.
///

///
 The list of valid escape sequences has been expanded over the Unix
   version, to include \b, \f, \r, and \v.

   POSIX changes, bug fixes, long-named options, and cleanup
   by David MacKenzie <djm@gnu.ai.mit.edu>.

   Options:
   --serial
   -s				Paste one file at a time rather than
                                one line from each file.
   --delimiters=delim-list
   -d delim-list		Consecutively use the characters in
                                DELIM-LIST instead of tab to separate
                                merged lines.  When DELIM-LIST is exhausted,
                                start again at its beginning.
   A FILE of '-' means standard input.
   If no FILEs are given, standard input is used.
///

byte* PROGRAM_NAME = "paste";
macro AUTHORS
{
    proper_name ( "David M. Ihnat" ) , proper_name ( "David MacKenzie" )
};

extern int have_read_stdin;
extern int serial_merge;
extern byte* delims;
ulong* delim_lens = size_t;
extern int num_delims;
byte line_delim = '\n';
struct option;
extern int longopts;
cdecl collapse_escapes(byte* strptr) -> int
{
    byte* strout = xstrdup(strptr);
    bool;
    delims = strout;
    delim_lens = xnmalloc(MAX(1, strlen(strptr)), (sizeof * delim_lens / 8));
    byte* s = strptr;
    while (*s)
    {
        if (*s == '\\')
        {
            s++;
            if (*s == '\0')
            {
                break;
            }
            elif (*s == '0')
            {
                s++;
            };
            else
            {
                switch (*s)
                {
                    case ('b')
                    {
                        *strout++ = '\b';
                        break switch;
                    }
                    case ('f')
                    {
                        *strout++ = '\f';
                        break switch;
                    }
                    case ('n')
                    {
                        *strout++ = '\n';
                        break switch;
                    }
                    case ('r')
                    {
                        *strout++ = '\r';
                        break switch;
                    }
                    case ('t')
                    {
                        *strout++ = '\t';
                        break switch;
                    }
                    case ('v')
                    {
                        *strout++ = '\v';
                        break switch;
                    }
                    case ('\\')
                    {
                        *strout++ = '\\';
                        break switch;
                    }
                    default
                    {
                    };
                };
                s++;
            };
            continue;
        };
        label copy_character:
        strout = mempcpy;
    };
    *strout = '\0';
    if (idx == 0)
    {
        delim_lens[0] = 0;
    };
};

cdecl xputchar(byte c) -> void
{
    if (putchar(c) < 0)
        write_error();
};

cdecl output_delim(byte* delimptr, ulong len) -> void
{
    if (len > 0 & fwrite != len)
        write_error();
};

cdecl paste_parallel(ulong nfiles, byte** fnamptr) -> int
{
    bool;
    byte* delbuf = xmalloc;
    ulong files_open;
    bool;
    for (files_open = 0; files_open < nfiles; ++files_open)
    {
        if (streq(fnamptr[files_open], "-"))
        {
        }
        else
        {
            if (fileptr [ files_open ] == NULL)
                error;
            else
            fadvise;
        };
    };
    if (opened_stdin && have_read_stdin)
        error;
    while (files_open)
    {
        bool;
        for (ulong i = 0; i < nfiles & files_open; i++)
        {
            int chr;
            int err;
            bool;
            if (fileptr [ i ])
            {
                chr = getc;
                if (chr != EOF && delims_saved)
                {
                    if (fwrite ( delbuf , 1 , delims_saved , stdout ) != delims_saved)
                        write_error();
                };
                while (chr != EOF)
                {
                    if (chr == line_delim)
                        break;
                    xputchar(chr);
                    chr = getc;
                };
            };
            if (! sometodo)
            {
                if (fileptr [ i ])
                {
                    if (!ferror)
                        err = 0;
                    if (fileptr [ i ] == stdin)
                        clearerr;
                    else
                    if (err)
                    {
                        error(0, err, "%s", quotearg_n_style_colon);
                    };
                    files_open--;
                };
                if (i + 1 == nfiles)
                {
                    if (somedone)
                    {
                        if (delims_saved)
                        {
                            if (fwrite ( delbuf , 1 , delims_saved , stdout ) != delims_saved)
                                write_error();
                        };
                        xputchar(line_delim);
                    };
                    continue;
                }
                else
                {
                    ulong len;
                    if (len > 0)
                    {
                        memcpy;
                    };
                    if (++ delimidx == num_delims)
                    {
                    };
                };
            }
            else
            {
                if (i + 1 != nfiles)
                {
                    if (chr != line_delim && chr != EOF)
                        xputchar(chr);
                    output_delim;
                    if (++ delimidx == num_delims)
                    {
                    };
                }
                else
                {
                    byte c;
                    xputchar(c);
                };
            };
        };
    };
    free;
    free(delbuf);
};

cdecl paste_serial(ulong nfiles, byte** fnamptr) -> int
{
    bool;
    int charnew;
    int charold;
    for (nfiles; nfiles-- , fnamptr++; )
    {
        int saved_errno;
        bool;
        if (is_stdin)
        {
        }
        else
        {
            if (fileptr == NULL)
            {
                error;
                continue;
            };
            fadvise;
        };
        charold = getc;
        if (charold != EOF)
        {
            while (( charnew = getc ( fileptr ) ) != EOF)
            {
                if (charold == line_delim)
                {
                    output_delim;
                    if (++ delimidx == num_delims)
                    {
                    };
                }
                else
                    xputchar(charold);
                charold = charnew;
            };
            xputchar(charold);
        };
        if (charold != line_delim)
            xputchar(line_delim);
        if (!ferror)
            saved_errno = 0;
        if (is_stdin)
            clearerr;
        else
        if (saved_errno)
        {
            error(0, saved_errno, "%s", quotearg_n_style_colon);
        };
    };
};

cdecl usage(int status) -> void
{
    if (status != EXIT_SUCCESS)
        do
        {
            fprintf;
        }
        while (0);
    else
    {
        printf;
        fputs;
        emit_stdin_note();
        emit_mandatory_arg_note();
        oputs_("paste", gettext("\
  -d, --delimiters=LIST\n\
         reuse characters from LIST instead of TABs;\n\
         backslash escapes are supported\n\
"));
        oputs_("paste", gettext("\
  -s, --serial\n\
         paste one file at a time instead of in parallel; the newline of\n\
         every line except the last line in each file is replaced with a TAB\
\n\
"));
        oputs_("paste", gettext("\
  -z, --zero-terminated\n\
         line delimiter is NUL, not newline\n\
"));
        oputs_("paste", gettext("      --help\n         display this help and exit\n"));
        oputs_("paste", gettext("      --version\n         output version information and exit\n"));
        emit_ancillary_info("paste");
    };
    exit(status);
};

cdecl main(int argc, byte** argv) -> int
{
    int optc;
    byte* delim_arg = "\t";
    set_program_name(argv[0]);
    setlocale;
    atexit;
    while ((optc = getopt_long) != -1)
    {
        switch (optc)
        {
            case ('d')
            {
                break switch;
            }
            case ('s')
            {
                break switch;
            }
            case ('z')
            {
                line_delim = '\0';
                break switch;
            }
            case (GETOPT_HELP_CHAR)
            {
                usage;
                break switch;
            }
            case (GETOPT_VERSION_CHAR)
            {
                version_etc;
                exit;
                break switch;
            }
            default
            {
            };
        };
    };
    int nfiles;
    if (nfiles == 0)
    {
        nfiles++;
    };
    if (collapse_escapes(delim_arg))
    {
        error;
    };
    bool;
    free(delims);
    free(delim_lens);
    if (have_read_stdin && fclose ( stdin ) == EOF)
        error;
};
