// Auto-generated by cft from: pr.c
// May require manual edits.

///
 pr -- convert text files for printing.
   Copyright (C) 1988-2026 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
///

///
  By Pete TerMaat, with considerable refinement by Roland Huebner.
///

///
 Things to watch: Sys V screws up on ...
   pr -n -3 -s: /usr/dict/words
   pr -m -o10 -n /usr/dict/words{,,,}
   pr -6 -a -n -o5 /usr/dict/words

   Ideas:

   Keep a things_to_do list of functions to call when we know we have
   something to print.  Cleaner than current series of checks.

   Improve the printing of control prefixes.

   Expand the file name in the centered header line to a full file name.


   Concept:

   If the input_tab_char differs from the default value TAB
   ('-e[CHAR[...]]' is used), any input text tab is expanded to the
   default width of 8 spaces (compare char_to_clump). - Same as SunOS
   does.

   The treatment of the number_separator (compare add_line_number):
   The default value TAB of the number_separator ('-n[SEP[...]]') doesn't
   be thought to be an input character. An optional '-e'-input has no
   effect.
   -  With single column output
      only one POSIX requirement has to be met:
   The default n-separator should be a TAB. The consequence is a
   different width between the number and the text if the output position
   of the separator changes, i.e., it depends upon the left margin used.
   That's not nice but easy-to-use together with the defaults of other
   utilities, e.g. sort or cut. - Same as SunOS does.
   -  With multicolumn output
      two conflicting POSIX requirements exist:
   First "default n-separator is TAB", second "output text columns shall
   be of equal width". Moreover POSIX specifies the number+separator a
   part of the column, together with '-COLS' and '-a -COLS'.
   (With -m output the number shall occupy each line only once. Exactly
   the same situation as single column output exists.)
      GNU pr gives priority to the 2nd requirement and observes POSIX
   column definition. The n-separator TAB is expanded to the same number
   of spaces in each column using the default value 8. Tabification is
   only performed if it is compatible with the output position.
   Consequence: The output text columns are of equal width. The layout
   of a page does not change if the left margin varies. - Looks better
   than the SunOS approach.
      SunOS pr gives priority to the 1st requirement. n-separator TAB
   width varies with each column. Only the width of text part of the
   column is fixed.
   Consequence: The output text columns don't have equal width. The
   widths and the layout of the whole page varies with the left margin.
   An overflow of the line length (without margin) over the input value
   PAGE_WIDTH may occur.

   The interference of the POSIX-compliant small letter options -w and -s:
   ("interference" means "setting a _separator_ with -s switches off the
   column structure and the default - not generally - page_width,
   acts on -w option")
       options:       text form  / separator:     equivalent new options:
       -w l   -s[x]
    --------------------------------------------------------------------
    1.  --     --     columns    / space          --
                      trunc. to page_width = 72
    2.  --    -s[:]   full lines / TAB[:]         -J  --sep-string[="<TAB>"|:]
                      no truncation
    3.  -w l   --     columns    / space          -W l
                      trunc. to page_width = l
    4.  -w l  -s[:]   columns    / no sep.[:]     -W l  --sep-string[=:]
                      trunc. to page_width = l
    --------------------------------------------------------------------


   Options:

   Including version 1.22i:
   Some SMALL LETTER options have been redefined with the object of a
   better POSIX compliance. The output of some further cases has been
   adapted to other UNIXes. A violation of downward compatibility has to
   be accepted.
   Some NEW CAPITAL LETTER options ( -J, -S, -W) has been introduced to
   turn off unexpected interference of small letter options (-s and -w
   together with the three column options).
   -N option and the second argument LAST_PAGE of +FIRST_PAGE offer more
   flexibility; The detailed handling of form feeds set in the input
   files requires -T option.

   Capital letter options dominate small letter ones.

   Some of the option-arguments cannot be specified as separate arguments
   from the preceding option letter (already stated in POSIX specification).

   Form feeds in the input cause page breaks in the output. Multiple
   form feeds produce empty pages.

   +FIRST_PAGE[:LAST_PAGE], --pages=FIRST_PAGE[:LAST_PAGE]
                begin [stop] printing with page FIRST_[LAST_]PAGE

   -COLS, --columns=COLS
                Produce output that is COLS columns wide and
                print columns down, unless -a is used. Balance number of
                lines in the columns on each page.

   -a, --across		Print columns across rather than down, used
                together with -COLS. The input
                one
                two
                three
                four
                will be printed with '-a -3' as
                one	two	three
                four

   -b		Balance columns on the last page.
                -b is no longer an independent option. It's always used
                together with -COLS (unless -a is used) to get a
                consistent formulation with "FF set by hand" in input
                files. Each formfeed found terminates the number of lines
                to be read with the actual page. The situation for
                printing columns down is equivalent to that on the last
                page. So we need a balancing.

                Keeping -b as an underground option guarantees some
                downward compatibility. Utilities using pr with -b
                (a most frequently used form) still work as usual.

   -c, --show-control-chars
                Print nonprintable characters as control prefixes.
                Control-g is printed as ^G (use hat notation) and
                octal backslash notation.

   -d, --double-space	Double space the output.

   -D FORMAT, --date-format=FORMAT  Use FORMAT for the header date.

   -e[CHAR[WIDTH]], --expand-tabs[=CHAR[WIDTH]]
                Expand tabs to spaces on input.  Optional argument CHAR
                is the input TAB character. (Default is TAB).  Optional
                argument WIDTH is the input TAB character's width.
                (Default is 8.)

   -F, -f, --form-feed	Use formfeeds instead of newlines to separate
                pages. A three line HEADER is used, no TRAILER with -F,
                without -F both HEADER and TRAILER are made of five lines.

   -h HEADER, --header=HEADER
                Replace the filename in the header with the string HEADER.
                A centered header is used.

   -i[CHAR[WIDTH]], --output-tabs[=CHAR[WIDTH]]
                Replace spaces with tabs on output.  Optional argument
                CHAR is the output TAB character. (Default is TAB).
                Optional argument WIDTH is the output TAB character's
                width. (Default is 8)

   -J, --join-lines	Merge lines of full length, turns off -W/-w
                line truncation, no column alignment, --sep-string[=STRING]
                sets separators, works with all column options
                (-COLS | -a -COLS | -m).
                -J has been introduced (together with -W and --sep-string) to
                disentangle the old (POSIX compliant) options -w, -s
                along with the 3 column options.

   -l PAGE_LENGTH, --length=PAGE_LENGTH
                Set the page length to PAGE_LENGTH lines. Default is 66,
                including 5 lines of HEADER and 5 lines of TRAILER
                without -F, but only 3 lines of HEADER and no TRAILER
                with -F (i.e the number of text lines defaults to 56 or
                63 respectively).

   -m, --merge		Print files in parallel; pad_across_to align
                columns; truncate lines and print separator strings;
                Do it also with empty columns to get a continuous line
                numbering and column marking by separators throughout
                the whole merged file.

                Empty pages in some input files produce empty columns
                [marked by separators] in the merged pages. Completely
                empty merged pages show no column separators at all.

                The layout of a merged page is ruled by the largest form
                feed distance of the single pages at that page. Shorter
                columns will be filled up with empty lines.

                Together with -J option join lines of full length and
                set separators when -S option is used.

   -n[SEP[DIGITS]], --number-lines[=SEP[DIGITS]]
                Provide DIGITS digit line numbering (default for DIGITS
                is 5). With multicolumn output the number occupies the
                first DIGITS column positions of each text column or only
                each line of -m output.
                With single column output the number precedes each line
                just as -m output.
                Optional argument SEP is the character appended to the
                line number to separate it from the text followed.
                The default separator is a TAB. In a strict sense a TAB
                is always printed with single column output only. The
                TAB-width varies with the TAB-position, e.g. with the
                left margin specified by -o option.
                With multicolumn output priority is given to "equal width
                of output columns" (a POSIX specification). The TAB-width
                is fixed to the value of the 1st column and does not
                change with different values of left margin. That means a
                fixed number of spaces is always printed in the place of
                a TAB. The tabification depends upon the output
                position.

                Default counting of the line numbers starts with 1st
                line of the input file (not the 1st line printed,
                compare the --page option and -N option).

   -N NUMBER, --first-line-number=NUMBER
                Start line counting with the number NUMBER at the 1st
                line of first page printed (mostly not the 1st line of
                the input file).

   -o MARGIN, --indent=MARGIN
                Offset each line with a margin MARGIN spaces wide.
                Total page width is the size of the margin plus the
                PAGE_WIDTH set with -W/-w option.

   -r, --no-file-warnings
                Omit warning when a file cannot be opened.

   -s[CHAR], --separator[=CHAR]
                Separate columns by a single character CHAR, default for
                CHAR is the TAB character without -w and 'no char' with -w.
                Without '-s' default separator 'space' is set.
                -s[CHAR] turns off line truncation of all 3 column options
                (-COLS|-a -COLS|-m) except -w is set. That is a POSIX
                compliant formulation. The source code translates -s into
                the new options -S and -J, also -W if required.

   -S[STRING], --sep-string[=STRING]
                Separate columns by any string STRING. The -S option
                doesn't react upon the -W/-w option (unlike -s option
                does). It defines a separator nothing else.
                Without -S: Default separator TAB is used with -J and
                'space' otherwise (same as -S" ").
                With -S "": No separator is used.
                Quotes should be used with blanks and some shell active
                characters.
                -S is problematic because in its obsolete form you
                cannot use -S "STRING", but in its standard form you
                must use -S "STRING" if STRING is empty.  Use
                --sep-string to avoid the ambiguity.

   -t, --omit-header	Do not print headers or footers but retain form
                feeds set in the input files.

   -T, --omit-pagination
                Do not print headers or footers, eliminate any pagination
                by form feeds set in the input files.

   -v, --show-nonprinting
                Print nonprintable characters as escape sequences. Use
                octal backslash notation. Control-G becomes \007.

   -w PAGE_WIDTH, --width=PAGE_WIDTH
                Set page width to PAGE_WIDTH characters for multiple
                text-column output only (default for PAGE_WIDTH is 72).
                -s[CHAR] turns off the default page width and any line
                truncation. Lines of full length will be merged,
                regardless of the column options set. A POSIX compliant
                formulation.

   -W PAGE_WIDTH, --page-width=PAGE_WIDTH
                Set the page width to PAGE_WIDTH characters. That's valid
                with and without a column option. Text lines will be
                truncated, unless -J is used. Together with one of the
                column options (-COLS| -a -COLS| -m) column alignment
                is always used.
                Default is 72 characters.
                Without -W PAGE_WIDTH
                - but with one of the column options default truncation of
                  72 characters is used (to keep downward compatibility
                  and to simplify most frequently met column tasks).
                  Column alignment and column separators are used.
                - and without any of the column options NO line truncation
                  is used (to keep downward compatibility and to meet most
                  frequent tasks). That's equivalent to  -W 72 -J .

                With/without  -W PAGE_WIDTH  the header line is always
                truncated to avoid line overflow.

                (In pr versions newer than 1.14 -S option does no longer
                affect -W option.)

///

byte* PROGRAM_NAME = "pr";
macro AUTHORS
{
    proper_name ( "Pete TerMaat" ) , proper_name ( "Roland Huebner" )
};

uint ANYWHERE = 0;
macro TAB_WIDTH(c_, h_)
{
    ( ( c_ ) - ( ( h_ ) % ( c_ ) ) )
};

macro POS_AFTER_TAB(c_, h_)
{
    ( ( h_ ) + TAB_WIDTH ( c_ , h_ ) )
};

struct COLUMN;
cdecl char_to_clump(byte c) -> int;
cdecl read_line(COLUMN* p) -> int;
cdecl print_page() -> int;
cdecl print_stored(COLUMN* p) -> int;
cdecl open_file(byte* name, COLUMN* p) -> int;
cdecl skip_to_page(ulong page) -> int;
cdecl print_header() -> void;
cdecl pad_across_to(int position) -> void;
cdecl add_line_number(COLUMN* p) -> void;
cdecl getoptnum(byte* n_str, int min, byte* errfmt) -> int;
cdecl getoptarg(byte* arg, byte switch_char, byte* character, int* number) -> void;
cdecl print_files(int number_of_files, byte** av) -> void;
cdecl init_parameters(int number_of_files) -> void;
cdecl init_header(byte* filename, int desc) -> void;
cdecl init_fps(int number_of_files, byte** av) -> int;
cdecl init_funcs() -> void;
cdecl init_store_cols() -> void;
cdecl store_columns() -> void;
cdecl balance(int total_stored) -> void;
cdecl store_char(byte c) -> void;
cdecl pad_down(uint lines) -> void;
cdecl read_rest_of_line(COLUMN* p) -> void;
cdecl skip_read(COLUMN* p, int column_number) -> void;
cdecl print_char(byte c) -> void;
cdecl cleanup() -> void;
cdecl print_sep_string() -> void;
cdecl separator_string(byte* optarg_S) -> void;
COLUMN* column_vector = COLUMN;
extern byte* buff;
extern uint buff_current;
extern int buff_allocated;
extern int* line_vector;
extern int* end_vector;
extern int parallel_files;
extern int align_empty_cols;
extern int empty_line;
extern int FF_only;
extern int explicit_columns;
extern int extremities;
extern int keep_FF;
extern int print_a_FF;
extern int print_a_header;
extern int use_form_feed;
extern int have_read_stdin;
extern int print_across_flag;
extern int storing_columns;
extern int balance_columns;
int lines_per_page = 66;
uint lines_per_header = 5;

extern int lines_per_body;
uint lines_per_footer = 5;

int chars_per_line = 72;
extern int truncate_lines;
extern int join_lines;
extern int chars_per_column;
extern int untabify_input;
byte input_tab_char = '\t';
int chars_per_input_tab = 8;
extern int tabify_output;
byte output_tab_char = '\t';
int chars_per_output_tab = 8;
extern int spaces_not_printed;
int chars_per_margin = 0;
extern int output_position;
extern int input_position;
extern int failed_opens;
int columns = 1;
ulong first_page_number = uintmax_t;
ulong last_page_number = uintmax_t;
int files_ready_to_read = 0;
ulong page_number = uintmax_t;
extern int line_number;
extern int numbered_lines;
byte number_separator = '\t';
int line_count = 1;
extern int skip_count;
int start_line_num = 1;
int chars_per_number = 5;
extern int number_width;
extern byte* number_buff;
extern int use_esc_sequence;
extern int use_cntrl_prefix;
extern int double_space;
int total_files = 0;
extern int ignore_failed_opens;
extern int use_col_separator;
byte* col_sep_string = "";
int col_sep_length = 0;
byte* column_separator = (byte*)" ";
byte* line_separator = (byte*)"\t";
extern int separators_not_printed;
extern int padding_not_printed;
extern int pad_vertically;
extern byte* custom_header;
extern byte* date_format;
extern int localtz;
extern byte* date_text;
extern byte* file_text;
extern int header_width_available;
extern byte* clump_buff;
extern int last_line;
uint COLUMNS_OPTION = 128;
uint PAGES_OPTION = 129;

byte[53] short_options = "-0123456789D:FJN:S::TW:abcde::fh:i::l:mn::o:rs::tvw:";
option[27] long_options = option;
cdecl integer_overflow() -> void
{
    error(0, 0, gettext("integer overflow"));
};

cdecl cols_ready_to_print() -> int
{
    COLUMN* q;
    uint i;
    uint n;
    n = 0;
    for (q = column_vector , i = 0; i < columns; ++q , ++i)
    {};
    return n;
};

cdecl first_last_page(int oi, byte c, byte* pages) -> int
{
    byte* p;
    ulong first;
    ulong last = (0);
    if (*p == ':')
    {
        byte* p1 = p + 1;
    };
    first_page_number = first;
    last_page_number = last;
};

cdecl parse_column_count(byte* s) -> void
{
    columns = getoptnum(s, 1, gettext("invalid number of columns"));
};

cdecl main(int argc, byte** argv) -> int
{
    uint n_files;
    bool;
    bool;
    bool;
    byte** file_names;
    byte* column_count_string = ((void*)0);
    set_program_name(argv[0]);
    setlocale(0, "");
    n_files = 0;
    file_names = (argc > 1 ? xnmalloc(argc - 1, (sizeof ( char * ) / 8)) : ((void*)0));
    while (?)
    {
        int oi = -1;
        int c = getopt_long(argc, argv, short_options, long_options, @oi);
        if (c == -1)
            break;
        if (c_isdigit(c))
        {
            continue;
        };
        switch (c)
        {
            case (1)
            {
                if (!(first_page_number == 0 & *optarg == '+' & ?(-2, '+', optarg + 1)))
                    file_names[n_files++] = optarg;
            }
            goto _switch_end_139188838867536;
            case (PAGES_OPTION)
            {
                {
                    if (!optarg)
                        error(0, 0, gettext("'--pages=FIRST_PAGE[:LAST_PAGE]' missing argument"));
                    elif (!?(oi, 0, optarg))
                        error(0, 0, gettext("invalid page range %s"), quote(optarg));
                    goto _switch_end_139188838867536;
                };
            }
            case (COLUMNS_OPTION)
            {
                {
                    parse_column_count(optarg);
                    free(column_count_string);
                    column_count_string = ((void*)0);
                    goto _switch_end_139188838867536;
                };
            }
            case ('a')
            {
            }
            goto _switch_end_139188838867536;
            case ('b')
            {
            }
            goto _switch_end_139188838867536;
            case ('c')
            {
            }
            goto _switch_end_139188838867536;
            case ('d')
            {
            }
            goto _switch_end_139188838867536;
            case ('D')
            {
                date_format = optarg;
            }
            goto _switch_end_139188838867536;
            case ('e')
            {
                if (optarg)
                    getoptarg(optarg, 'e', @input_tab_char, @chars_per_input_tab);
            }
            goto _switch_end_139188838867536;
            case ('f')
            {
                case ('F')
                {
                }
            }
            goto _switch_end_139188838867536;
            case ('h')
            {
                custom_header = optarg;
            }
            goto _switch_end_139188838867536;
            case ('i')
            {
                if (optarg)
                    getoptarg(optarg, 'i', @output_tab_char, @chars_per_output_tab);
            }
            goto _switch_end_139188838867536;
            case ('J')
            {
            }
            goto _switch_end_139188838867536;
            case ('l')
            {
                lines_per_page = getoptnum(optarg, 1, gettext("'-l PAGE_LENGTH' invalid number of lines"));
            }
            goto _switch_end_139188838867536;
            case ('m')
            {
            }
            goto _switch_end_139188838867536;
            case ('n')
            {
            }
            if (optarg)
                getoptarg(optarg, 'n', @number_separator, @chars_per_number);
            goto _switch_end_139188838867536;
            case ('N')
            {
            }
            start_line_num = getoptnum(optarg, (?0 ? 0), gettext("'-N NUMBER' invalid starting line number"));
            goto _switch_end_139188838867536;
            case ('o')
            {
                chars_per_margin = getoptnum(optarg, 0, gettext("'-o MARGIN' invalid line offset"));
            }
            goto _switch_end_139188838867536;
            case ('r')
            {
            }
            goto _switch_end_139188838867536;
            case ('s')
            {
            }
            if (!? & optarg)
                separator_string(optarg);
            goto _switch_end_139188838867536;
            case ('S')
            {
            }
            col_sep_string = "";
            col_sep_length = 0;
            if (optarg)
                separator_string(optarg);
            goto _switch_end_139188838867536;
            case ('t')
            {
            }
            goto _switch_end_139188838867536;
            case ('T')
            {
            }
            goto _switch_end_139188838867536;
            case ('v')
            {
            }
            goto _switch_end_139188838867536;
            case ('w')
            {
            }
            {
                int tmp_cpl = getoptnum(optarg, 1, gettext("'-w PAGE_WIDTH' invalid number of characters"));
                if (!?)
                    chars_per_line = tmp_cpl;
            };
            goto _switch_end_139188838867536;
            case ('W')
            {
            }
            chars_per_line = getoptnum(optarg, 1, gettext("'-W PAGE_WIDTH' invalid number of characters"));
            goto _switch_end_139188838867536;
            case (GETOPT_HELP_CHAR)
            {
                usage(0);
            }
            goto _switch_end_139188838867536;
            case (GETOPT_VERSION_CHAR)
            {
            }
            exit(0);
            goto _switch_end_139188838867536;
            default
            {
                usage(0);
            };
            goto _switch_end_139188838867536;
        };
        label _switch_end_139188838867536:
    };
    if (column_count_string)
    {
        parse_column_count(column_count_string);
        free(column_count_string);
    };
    if (!date_format)
        date_format = (getenv("POSIXLY_CORRECT") & !hard_locale(0) ? "%b %e %H:%M %Y" : "%Y-%m-%d %H:%M");
    localtz = tzalloc(getenv("TZ"));
    if (first_page_number == 0)
        first_page_number = 1;
    if (? & ?)
        error(0, 0, gettext("cannot specify number of columns when printing in parallel"));
    if (? & ?)
        error(0, 0, gettext("cannot specify both printing across and printing in parallel"));
    if (?)
    {
        if (?)
        {
            if (? | ?)
            {
            }
            else
        }
        elif (!?)
        {
            if (?)
            {
                if (!?)
                {
                }
                else
            };
        };
    };
    for (optind < argc; optind++; )
    {
        file_names[n_files++] = argv[optind];
    };
    if (n_files == 0)
    {
        print_files(0, ((void*)0));
    }
    else
    {
        if (?)
            print_files(n_files, file_names);
        else
        {
            for (uint i = 0; i < n_files; i++)
            {};
        };
    };
    cleanup();
    if (?)
        error(0, (?__errno_location()), gettext("standard input"));
    return ? ? 1 : 0;
};

cdecl close_file(COLUMN* p) -> void
{
    COLUMN* q;
    int i;
    if (p.status == CLOSED)
        return void;
    int err = (?__errno_location());
    if (!ferror(p))
        err = 0;
    if (fileno(p) == 0)
        clearerr(p);
    elif (fclose(p) != 0 & !err)
        err = (?__errno_location());
    if (!?)
    {
        for (q = column_vector , i = columns; i; ++q , --i)
        {
            q.status = CLOSED;
            if (q.lines_stored == 0)
            {
                q.lines_to_print = 0;
            };
        };
    }
    else
    {
        p.status = CLOSED;
        p.lines_to_print = 0;
    };
    --files_ready_to_read;
};

cdecl hold_file(COLUMN* p) -> void
{
    COLUMN* q;
    int i;
    if (!?)
        for (q = column_vector , i = columns; i; ++q , --i)
        {
            if (?)
                q.status = FF_FOUND;
            else
                q.status = ON_HOLD;
        }
    else
        p.status = ON_HOLD;
    p.lines_to_print = 0;
    --files_ready_to_read;
};

cdecl reset_status() -> void
{
    int i = columns;
    COLUMN* p;
    for (p = column_vector; i; --i , ++p)
    {};
    if (?)
    {
        if (column_vector.status == CLOSED)
            files_ready_to_read = 0;
        else
            files_ready_to_read = 1;
    };
};

cdecl init_page() -> void
{
    int j;
    COLUMN* p;
    if (?)
    {
        store_columns();
        for (j = columns - 1 , p = column_vector; j; --j , ++p)
        {
            p.lines_to_print = p.lines_stored;
        };
        if (?)
        {
            p.lines_to_print = p.lines_stored;
        }
        else
        {
            if (p.status == OPEN)
            {
                p.lines_to_print = lines_per_body;
            }
            else
                p.lines_to_print = 0;
        };
    }
    else
        for (j = columns , p = column_vector; j; --j , ++p)
        {};
};

cdecl align_column(COLUMN* p) -> void
{
    padding_not_printed = p.start_position;
    if (col_sep_length < padding_not_printed)
    {
        pad_across_to(padding_not_printed - col_sep_length);
        padding_not_printed = 0;
    };
    if (?)
        print_sep_string();
    if (p)
        add_line_number(p);
};

cdecl print_white_space() -> void
{
    int h_new;
    int h_old = output_position;
    int goal = h_old + spaces_not_printed;
    while (goal - h_old > 1 & (h_new = ((h_old) ? ((chars_per_output_tab) ? ((h_old) ? (chars_per_output_tab))))) <= goal)
    {
        putchar(output_tab_char);
        h_old = h_new;
    };
    while (++h_old <= goal)
        putchar(' ');
    output_position = goal;
    spaces_not_printed = 0;
};

cdecl print_clump(COLUMN* p, int n, byte* clump) -> void
{
    while (n--)
        (p.char_func)(*clump++);
    if (?)
        write_error();
};

cdecl usage(int status) -> void
{
    if (status != 0)
        do
        {
        }
        while (0);
    else
    {
        emit_stdin_note();
        emit_mandatory_arg_note();
        oputs_("pr", gettext("\n\
  +FIRST_PAGE[:LAST_PAGE], --pages=FIRST_PAGE[:LAST_PAGE]\n\
         begin [stop] printing with page FIRST_[LAST_]PAGE\n\
"));
        oputs_("pr", gettext("\
  -COLS, --columns=COLS\n\
         output COLS columns and print columns down, unless -a is used.\n\
         Balance number of lines in the columns on each page\n\
"));
        oputs_("pr", gettext("\
  -a, --across\n\
         print columns across rather than down, used together with -COLS\n\
"));
        oputs_("pr", gettext("\
  -c, --show-control-chars\n\
         use hat notation (^G) and octal backslash notation\n\
"));
        oputs_("pr", gettext("\
  -d, --double-space\n\
         double space the output\n\
"));
        oputs_("pr", gettext("\
  -D, --date-format=FORMAT\n\
         use FORMAT for the header date\n\
"));
        oputs_("pr", gettext("\
  -e[CHAR[WIDTH]], --expand-tabs[=CHAR[WIDTH]]\n\
         expand input CHARs (TABs) to tab WIDTH (8)\n\
"));
        oputs_("pr", gettext("\
  -F, -f, --form-feed\n\
         use form feeds instead of newlines to separate pages\n\
         (by a 3-line page header with -F or a 5-line header\n\
         and trailer without -F)\n\
"));
        oputs_("pr", gettext("\
  -h, --header=HEADER\n\
         use a centered HEADER instead of filename in page header,\n\
         -h \"\" prints a blank line, don't use -h\"\"\n\
"));
        oputs_("pr", gettext("\
  -i[CHAR[WIDTH]], --output-tabs[=CHAR[WIDTH]]\n\
         replace spaces with CHARs (TABs) to tab WIDTH (8)\n\
"));
        oputs_("pr", gettext("\
  -J, --join-lines\n\
         merge full lines, turns off -W line truncation,\n\
         no column alignment, --sep-string[=STRING] sets separators\n\
"));
        oputs_("pr", gettext("\
  -l, --length=PAGE_LENGTH\n\
         set the page length to PAGE_LENGTH (66) lines\n\
         (default number of lines of text 56, and with -F 63).\n\
         implies -t if PAGE_LENGTH <= 10\n\
"));
        oputs_("pr", gettext("\
  -m, --merge\n\
         print all files in parallel, one in each column,\n\
         truncate lines, but join lines of full length with -J\n\
"));
        oputs_("pr", gettext("\
  -n[SEP[DIGITS]], --number-lines[=SEP[DIGITS]]\n\
         number lines, use DIGITS (5) digits, then SEP (TAB),\n\
         default counting starts with 1st line of input file\n\
"));
        oputs_("pr", gettext("\
  -N, --first-line-number=NUMBER\n\
         start counting with NUMBER at 1st line of first\n\
         page printed (see +FIRST_PAGE)\n\
"));
        oputs_("pr", gettext("\
  -o, --indent=MARGIN\n\
         offset each line with MARGIN (zero) spaces, do not\n\
         affect -w or -W, MARGIN will be added to PAGE_WIDTH\n\
"));
        oputs_("pr", gettext("\
  -r, --no-file-warnings\n\
         omit warning when a file cannot be opened\n\
"));
        oputs_("pr", gettext("\
  -s[CHAR], --separator[=CHAR]\n\
         separate columns by a single character, default for CHAR\n\
         is the <TAB> character without -w and \'no char\' with -w.\n\
         -s[CHAR] turns off line truncation of all 3 column\n\
         options (-COLS|-a -COLS|-m) except -w is set\n\
"));
        oputs_("pr", gettext("\
  -S[STRING], --sep-string[=STRING]\n\
         separate columns by STRING,\n\
         without -S: Default separator <TAB> with -J and <space>\n\
         otherwise (same as -S\" \"), no effect on column options\n\
"));
        oputs_("pr", gettext("\
  -t, --omit-header\n\
         omit page headers and trailers; implied if PAGE_LENGTH <= 10\n\
"));
        oputs_("pr", gettext("\
  -T, --omit-pagination\n\
         omit page headers and trailers,\n\
         eliminate any pagination by form feeds set in input files\n\
"));
        oputs_("pr", gettext("\
  -v, --show-nonprinting\n\
         use octal backslash notation\n\
"));
        oputs_("pr", gettext("\
  -w, --width=PAGE_WIDTH\n\
         set page width to PAGE_WIDTH (72) characters for\n\
         multiple text-column output only, -s[char] turns off (72)\n\
"));
        oputs_("pr", gettext("\
  -W, --page-width=PAGE_WIDTH\n\
         set page width to PAGE_WIDTH (72) characters always,\n\
         truncate lines, except -J option is set,\n\
         no interference with -S or -s\n\
"));
        oputs_("pr", gettext("      --help\n         display this help and exit\n"));
        oputs_("pr", gettext("      --version\n         output version information and exit\n"));
        emit_ancillary_info("pr");
    };
    exit(status);
};
