// Auto-generated by cft from: printenv.c
// May require manual edits.

///
 printenv -- print all or part of environment
   Copyright (C) 1989-2026 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
///

///
 Usage: printenv [variable...]

   If no arguments are given, print the entire environment.
   If one or more variable names are given, print the value of
   each one that is set, and nothing for ones that are not set.

   Exit status:
   0 if all variables specified were found
   1 if not
   2 if some other error occurred

   David MacKenzie and Richard Mlynarik
///

byte* PROGRAM_NAME = "printenv";
macro AUTHORS
{
    proper_name ( "David MacKenzie" ) , proper_name ( "Richard Mlynarik" )
};

uint PRINTENV_FAILURE = 2;

option[4] longopts = option;
cdecl usage(int status) -> void
{
    if (status != 0)
        do
        {
        }
        while (0);
    else
    {
        oputs_("printenv", gettext("\
  -0, --null\n\
         end each output line with NUL, not newline\n\
"));
        oputs_("printenv", gettext("      --help\n         display this help and exit\n"));
        oputs_("printenv", gettext("      --version\n         output version information and exit\n"));
        printf(gettext("\n"), "printenv");
        emit_ancillary_info("printenv");
    };
    exit(status);
};

cdecl main(int argc, byte** argv) -> int
{
    bool;
    set_program_name(argv[0]);
    setlocale(0, "");
    initialize_exit_failure(PRINTENV_FAILURE);
    int optc;
    while ((optc = getopt_long(argc, argv, "+0", longopts, ((void*)0))) != -1)
    {
        switch (optc)
        {
            case ('0')
            {
            }
            goto _switch_end_139188819513296;
            case (GETOPT_HELP_CHAR)
            {
                usage(0);
            }
            goto _switch_end_139188819513296;
            case (GETOPT_VERSION_CHAR)
            {
            }
            exit(0);
            goto _switch_end_139188819513296;
            default
            {
                usage(PRINTENV_FAILURE);
            };
        };
        label _switch_end_139188819513296:
    };
    bool;
    if (optind >= argc)
    {
        for (byte** env; *env != ((void*)0); ++env)
        {
            fputs(*env, stdout);
        };
    }
    else
    {
        int matches = 0;
        for (int i = optind; i < argc; ++i)
        {
            bool;
            if (strchr(argv[i], '='))
                continue;
            for (byte** env; *env; ++env)
            {
                byte* ep = *env;
                byte* ap = argv[i];
                while (*ep != '\0' & *ap != '\0' & *ep++ == *ap++)
                {
                    if (*ep == '=' & *ap == '\0')
                    {
                        fputs(ep + 1, stdout);
                        break;
                    };
                };
            };
        };
    };
};
