// Auto-generated by cft from: prog-fprintf.c
// May require manual edits.

///
 prog-fprintf.c - common formatting output functions and definitions
   Copyright (C) 2008-2026 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
///

cdecl prog_fprintf(_IO_FILE* fp, byte* fmt, ...) -> void
{
    __va_list_tag[1] ap;
    fputs(": ", fp);
    __builtin_va_start(ap, fmt);
    vfprintf(fp, fmt, ap);
    __builtin_va_end(ap);
    fputc('\n', fp);
};
