// Auto-generated by cft from: readlink.c
// May require manual edits.

///
 readlink -- display value of a symbolic link.
   Copyright (C) 2002-2026 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
///

///
 Written by Dmitry V. Levin
///

byte* PROGRAM_NAME = "readlink";
macro AUTHORS
{
    proper_name ( "Dmitry V. Levin" )
};

extern int no_newline;
extern int verbose;
struct option;
extern int longopts;
cdecl usage(int status) -> void
{
    if (status != EXIT_SUCCESS)
        do
        {
            fprintf;
        }
        while (0);
    else
    {
        printf;
        fputs;
        oputs_("readlink", gettext("\
  -f, --canonicalize\n\
         canonicalize by following every symlink\n\
         in every component of the given name recursively;\n\
         all but the last component must exist\n\
"));
        oputs_("readlink", gettext("\
  -e, --canonicalize-existing\n\
         canonicalize by following every symlink\n\
         in every component of the given name recursively;\n\
         all components must exist\n\
"));
        oputs_("readlink", gettext("\
  -m, --canonicalize-missing\n\
         canonicalize by following every symlink\n\
         in every component of the given name recursively,\n\
         without requirements on components existence\n\
"));
        oputs_("readlink", gettext("\
  -n, --no-newline\n\
         do not output the trailing delimiter\n\
"));
        oputs_("readlink", gettext("\
  -q, --quiet\n\
"));
        oputs_("readlink", gettext("\
  -s, --silent\n\
         suppress most error messages\n\
         (on by default if POSIXLY_CORRECT is not set)\n\
"));
        oputs_("readlink", gettext("\
  -v, --verbose\n\
         report error messages\n\
         (on by default if POSIXLY_CORRECT is set)\n\
"));
        oputs_("readlink", gettext("\
  -z, --zero\n\
         end each output line with NUL, not newline\n\
"));
        oputs_("readlink", gettext("      --help\n         display this help and exit\n"));
        oputs_("readlink", gettext("      --version\n         output version information and exit\n"));
        emit_ancillary_info("readlink");
    };
    exit(status);
};

cdecl main(int argc, byte** argv) -> int
{
    int can_mode = -1;
    int status;
    int optc;
    bool;
    set_program_name(argv[0]);
    setlocale;
    atexit;
    while ((optc = getopt_long) != -1)
    {
        switch (optc)
        {
            case ('e')
            {
                break switch;
            }
            case ('f')
            {
                break switch;
            }
            case ('m')
            {
                break switch;
            }
            case ('n')
            {
                break switch;
            }
            case ('q')
            {
                break switch;
            }
            case ('v')
            {
                break switch;
            }
            case ('z')
            {
                break switch;
            }
            case (GETOPT_HELP_CHAR)
            {
                usage;
                break switch;
            }
            case (GETOPT_VERSION_CHAR)
            {
                version_etc;
                exit;
                break switch;
            }
            default
            {
            };
        };
    };
    if (optind >= argc)
    {
        error(0, 0, gettext("missing operand"));
        usage;
    };
    if (argc - optind > 1)
    {
        if (no_newline)
            error(0, 0, gettext("ignoring --no-newline with multiple arguments"));
    };
    return status;
};
