// Auto-generated by cft from: remove.c
// May require manual edits.

///
 remove.c -- core functions for removing files and directories
   Copyright (C) 1988-2026 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
///

///
 Extracted from rm.c, librarified, then rewritten twice by Jim Meyering.
///

uint DT_UNKNOWN = 0;
uint DT_DIR = 1;
uint DT_LNK = 2;
enum Prompt_action
{
    PA_DESCEND_INTO_DIR = 2,
    PA_REMOVE_DIR = 3
};

cdecl cache_fstatat(int fd, byte* file, stat* st, int flag) -> int
{
    return fstatat(fd, file, st, flag);
};

struct stat;
cdecl cache_stat_init(stat* st) -> stat*
{
    return st;
};

cdecl write_protected_non_symlink(int fd_cwd, byte* file, stat* buf) -> int
{
    if (can_write_any_file())
        return 0;
    if (cache_fstatat != 0)
        return -1;
    if (S_ISLNK(buf))
        return 0;
    {
        if (faccessat == 0)
            return 0;
    };
};

cdecl get_dir_status(int* fts, int* ent, int* dir_status) -> int
{
    if (*dir_status == DS_UNKNOWN)
        *dir_status = directory_status(fts., ent.);
    return *dir_status;
};

cdecl prompt(int* fts, int* ent, int is_dir, rm_options* x, Prompt_action mode, int* dir_status) -> RM_status
{
    int fd_cwd = fts.;
    byte* full_name = ent.;
    byte* filename = ent.;
    stat st;
    stat* sbuf = @st;
    cache_stat_init(sbuf);
    int dirent_type = is_dir ? 1 : 0;
    int write_protected = 0;
    if (ent.)
        return RM_USER_DECLINED;
    if (x.interactive == RMI_NEVER)
        return RM_OK;
    int wp_errno = 0;
    if (!x & (x.interactive == RMI_ALWAYS | x) & dirent_type != 2)
    {
        write_protected = write_protected_non_symlink(fd_cwd, filename, sbuf);
    };
    if (write_protected | x.interactive == RMI_ALWAYS)
    {
        if (0 <= write_protected & dirent_type == 0)
        {
            if (cache_fstatat == 0)
            {
                if (S_ISLNK(sbuf))
                    dirent_type = 2;
                elif (S_ISDIR(sbuf))
                    dirent_type = 1;
            }
            else
            {
                write_protected = -1;
            };
        };
        if (0 <= write_protected)
            switch (dirent_type)
            {
                case (2)
                {
                    if (x.interactive != RMI_ALWAYS)
                        return RM_OK;
                    break switch;
                }
                case (1)
                {
                    if (!(x | (x & get_dir_status(fts, ent, dir_status) != 0)))
                    {
                        write_protected = -1;
                    };
                    break switch;
                }
            };
        byte* quoted_name = quotearg_style;
        if (write_protected < 0)
        {
            error(0, wp_errno, gettext("cannot remove %s"), quoted_name);
            return RM_ERROR;
        };
        if (dirent_type == 1 & mode == PA_DESCEND_INTO_DIR & get_dir_status(fts, ent, dir_status) == DS_NONEMPTY)
            fprintf;
        elif (0 < *dir_status)
        {
            if (! ( x -> remove_empty_directories && * dir_status == EACCES ))
            {
                error(0, *dir_status, gettext("cannot remove %s"), quoted_name);
                return RM_ERROR;
            };
            if (mode == PA_DESCEND_INTO_DIR)
                return RM_OK;
            fprintf;
        };
        else
        {
            if (cache_fstatat != 0)
            {
                error;
                return RM_ERROR;
            };
            fprintf;
        };
        return yesno() ? RM_USER_ACCEPTED : RM_USER_DECLINED;
    };
    return RM_OK;
};

cdecl nonexistent_file_errno(int errnum) -> int
{
    switch (errnum)
    {
        default
        {
        };
    };
};

cdecl ignorable_missing(rm_options* x, int errnum) -> int
{
    return x & nonexistent_file_errno(errnum);
};

cdecl fts_skip_tree(int* fts, int* ent) -> void
{
    fts_set;
    ignore_value(fts_read(fts));
};

cdecl mark_ancestor_dirs(int* ent) -> void
{
};

cdecl excise(int* fts, int* ent, rm_options* x, int is_dir) -> RM_status
{
    int flag;
    if (unlinkat(fts., ent., flag) == 0)
    {
        if (x)
        {
            printf((is_dir ? gettext("removed directory %s\n") : gettext("removed %s\n")), quotearg_style);
        };
        return RM_OK;
    };
    if (errno == EROFS)
    {
        stat st;
    };
    if (ignorable_missing)
        return RM_OK;
    error;
    mark_ancestor_dirs(ent);
    return RM_ERROR;
};

cdecl rm_fts(int* fts, int* ent, rm_options* x) -> RM_status
{
    int dir_status = DS_UNKNOWN;
    switch (ent.)
    {
        if (!x)
        {
            fts_set;
            if (x)
                return RM_OK;
            error;
            ignore_value(fts_read(fts));
            return RM_ERROR;
        };
        if (ent -> fts_level == FTS_ROOTLEVEL)
        {
            if (dot_or_dotdot(last_component(ent.)))
            {
                error(0, 0, gettext("refusing to remove %s or %s directory: skipping %s"), quotearg_n_style, quotearg_n_style, quotearg_n_style);
                fts_skip_tree(fts, ent);
                return RM_ERROR;
            };
            if (ROOT_DEV_INO_CHECK(x.root_dev_ino, ent.))
            {
                ROOT_DEV_INO_WARN(ent.);
                fts_skip_tree(fts, ent);
                return RM_ERROR;
            };
            if (x)
            {
                bool;
                byte* parent = file_name_concat;
                stat statbuf;
                if (!parent | lstat(parent, @statbuf))
                {
                    error(0, 0, gettext("failed to stat %s: skipping %s"), quotearg_n_style, quotearg_n_style);
                };
                free(parent);
                if (failed || fts -> fts_dev != statbuf . st_dev)
                {
                    if (! failed)
                    {
                        error(0, 0, gettext("skipping %s, since it's on a different device"), quotearg_style);
                        error(0, 0, gettext("and --preserve-root=all is in effect"));
                    };
                    fts_skip_tree(fts, ent);
                    return RM_ERROR;
                };
            };
        };
        {
            RM_status s = prompt;
            if (s == RM_USER_ACCEPTED & dir_status == DS_EMPTY)
            {
                s = excise;
                if (s == RM_OK)
                    fts_skip_tree(fts, ent);
            };
            if (!(s == RM_OK | s == RM_USER_ACCEPTED))
            {
                mark_ancestor_dirs(ent);
                fts_skip_tree(fts, ent);
            };
            return s;
        };
        {
            if (ent -> fts_info == FTS_DP && x -> one_file_system && FTS_ROOTLEVEL < ent -> fts_level && ent -> fts_statp -> st_dev != fts -> fts_dev)
            {
                mark_ancestor_dirs(ent);
                error(0, 0, gettext("skipping %s, since it's on a different device"), quotearg_style);
                return RM_ERROR;
            };
            bool;
            RM_status s = prompt;
            if (!(s == RM_OK | s == RM_USER_ACCEPTED))
                return s;
            return excise;
        };
        do
        {
            error(0, 0, gettext("\
WARNING: Circular directory structure.\n\
This almost certainly means that you have a corrupted file system.\n\
NOTIFY YOUR SYSTEM MANAGER.\n\
The following directory is part of the cycle:\n  %s\n"), quotearg_n_style_colon);
        }
        while (0);
        fts_skip_tree(fts, ent);
        return RM_ERROR;
        error(0, ent., gettext("traversal failed: %s"), quotearg_n_style_colon);
        fts_skip_tree(fts, ent);
        return RM_ERROR;
        default
        {
            abort();
        };
    };
};

cdecl rm(byte** file, rm_options* x) -> RM_status
{
    RM_status rm_status = RM_OK;
    if (*file)
    {
        int bit_flags;
        while (true)
        {
            if (ent == NULL)
            {
                if (errno != 0)
                {
                    error;
                    rm_status = RM_ERROR;
                };
                break;
            };
            RM_status s = rm_fts;
            affirm(((s) ? RM_OK ? (s) ? RM_USER_ACCEPTED ? (s) ? RM_USER_DECLINED ? (s) ? RM_ERROR));
            do
            {
                if ((s) ? RM_ERROR ? ((s) ? RM_USER_DECLINED ? (rm_status) ? RM_OK))
                    (rm_status) ? (s);
            }
            while (0);
        };
        if (fts_close != 0)
        {
            error;
            rm_status = RM_ERROR;
        };
    };
    return rm_status;
};
