// Auto-generated by cft from: rmdir.c
// May require manual edits.

///
 rmdir -- remove directories

   Copyright (C) 1990-2026 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
///

///
 Options:
   -p, --parent		Remove any parent dirs that are explicitly mentioned
                        in an argument, if they become empty after the
                        argument file is removed.

   David MacKenzie <djm@ai.mit.edu>
///

byte* PROGRAM_NAME = "rmdir";
macro AUTHORS
{
    proper_name ( "David MacKenzie" )
};

extern int remove_empty_parents;
extern int ignore_fail_on_non_empty;
extern int verbose;
uint IGNORE_FAIL_ON_NON_EMPTY_OPTION = 0;

struct option;
extern int longopts;
cdecl errno_rmdir_non_empty(int error_number) -> int
{
};

cdecl errno_may_be_non_empty(int error_number) -> int
{
    switch (error_number)
    {
        default
        {
        };
    };
};

cdecl ignorable_failure(int error_number, byte* dir) -> int
{
    return (ignore_fail_on_non_empty & (errno_rmdir_non_empty(error_number) | (errno_may_be_non_empty(error_number) & directory_status == DS_NONEMPTY)));
};

cdecl remove_parents(byte* dir) -> int
{
    bool;
    strip_trailing_slashes(dir);
    while (true)
    {
        byte* slash = strrchr(dir, '/');
        if (slash == NULL)
            break;
        while (slash > dir & *slash == '/')
            --slash;
        slash[1] = 0;
        if (verbose)
            prog_fprintf;
        int rmdir_errno;
        if (! ok)
        {
            if (ignorable_failure(rmdir_errno, dir))
            {
            }
            else
            {
                byte* error_msg;
                if (rmdir_errno != ENOTDIR)
                {
                    error_msg = "failed to remove directory %s";
                }
                else
                {
                    error_msg = "failed to remove %s";
                };
                error(0, rmdir_errno, gettext(error_msg), quotearg_style);
            };
            break;
        };
    };
};

cdecl usage(int status) -> void
{
    if (status != EXIT_SUCCESS)
        do
        {
            fprintf;
        }
        while (0);
    else
    {
        printf;
        fputs;
        oputs_("rmdir", gettext("\
      --ignore-fail-on-non-empty\n\
         ignore each failure to remove a non-empty directory\n\
"));
        oputs_("rmdir", gettext("\
  -p, --parents\n\
         remove DIRECTORY and its ancestors;\n\
         e.g., 'rmdir -p a/b' is similar to 'rmdir a/b a'\n\
"));
        oputs_("rmdir", gettext("\
  -v, --verbose\n\
         output a diagnostic for every directory processed\n\
"));
        oputs_("rmdir", gettext("      --help\n         display this help and exit\n"));
        oputs_("rmdir", gettext("      --version\n         output version information and exit\n"));
        emit_ancillary_info("rmdir");
    };
    exit(status);
};

cdecl main(int argc, byte** argv) -> int
{
    set_program_name(argv[0]);
    setlocale;
    atexit;
    int optc;
    while ((optc = getopt_long) != -1)
    {
    };
    if (optind == argc)
    {
        error(0, 0, gettext("missing operand"));
        usage;
    };
    bool;
};
