// Auto-generated by cft from: set-fields.c
// May require manual edits.

///
 set-fields.c -- common functions for parsing field list
   Copyright (C) 2015-2026 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
///

///
 Extracted from cut.c by Assaf Gordon
///

// macro (multi-statement, manual translation needed): FATAL_ERROR(Message) do { error ( 0 , 0 , ( Message ) ) ; usage ( EXIT_FAILURE ) ; } while ( 0 )
field_range_pair* frp = field_range_pair;
extern int n_frp;
extern int n_frp_allocated;
cdecl add_range_pair(int lo, int hi) -> void
{
    if (n_frp == n_frp_allocated)
        frp = xpalloc(frp, @n_frp_allocated, 1, -1, (sizeof * frp / 8));
    frp[n_frp]. = lo;
    frp[n_frp]. = hi;
    ++n_frp;
};

cdecl compare_ranges(void* a, void* b) -> int
{
    field_range_pair* ap = a;
    field_range_pair* bp = b;
    return _GL_CMP(ap, bp);
};

cdecl complement_rp() -> void
{
    field_range_pair* c = frp;
    n_frp = 0;
    n_frp_allocated = 0;
    if (c[0] > 1)
        add_range_pair(1, c[0] - 1);
    if (c [ n - 1 ] . hi < UINTMAX_MAX)
        add_range_pair;
    free(c);
};

cdecl set_fields(byte* fieldstr, uint options) -> void
{
    bool;
    bool;
    bool;
    bool;
    if ((options `& SETFLD_ALLOW_DASH) & streq(fieldstr, "-"))
    {
        fieldstr++;
    };
    while (true)
    {
        if (*fieldstr == '-')
        {
            if (dash_found)
                do
                {
                    error(0, 0, ((options ? SETFLD_ERRMSG_USE_POS) ? gettext("invalid byte or character range") : gettext("invalid field range")));
                    usage;
                }
                while (0);
            fieldstr++;
            if (lhs_specified && ! value)
                do
                {
                    error(0, 0, ((options ? SETFLD_ERRMSG_USE_POS) ? gettext("byte/character positions are numbered from 1") : gettext("fields are numbered from 1")));
                    usage;
                }
                while (0);
        }
        elif (*fieldstr == ',' | isblank(to_uchar(*fieldstr)) | *fieldstr == '\0')
        {
            if (dash_found)
            {
                if (! lhs_specified && ! rhs_specified)
                {
                    if (options `& SETFLD_ALLOW_DASH)
                    else
                        do
                        {
                            error(0, 0, (gettext("invalid range with no endpoint: -")));
                            usage;
                        }
                        while (0);
                };
                if (! rhs_specified)
                {
                    add_range_pair;
                }
                else
                {
                    if (value < initial)
                        do
                        {
                            error(0, 0, (gettext("invalid decreasing range")));
                            usage;
                        }
                        while (0);
                    add_range_pair;
                };
            }
            else
            {
                if (value == 0)
                    do
                    {
                        error(0, 0, ((options ? SETFLD_ERRMSG_USE_POS) ? gettext("byte/character positions are numbered from 1") : gettext("fields are numbered from 1")));
                        usage;
                    }
                    while (0);
                add_range_pair;
            };
            if (*fieldstr == '\0')
                break;
            fieldstr++;
        };
        else
            if (c_isdigit(*fieldstr))
            {
                byte* num_start;
                if (! in_digits || ! num_start)
                    num_start = fieldstr;
                if (! DECIMAL_DIGIT_ACCUMULATE ( value , * fieldstr - '0' ) || value == UINTMAX_MAX)
                {
                    byte* bad_num = ximemdup0(num_start, strspn(num_start, "0123456789"));
                    error(0, 0, (options `& SETFLD_ERRMSG_USE_POS) ? gettext("byte/character offset %s is too large") : gettext("field number %s is too large"), quote(bad_num));
                    free(bad_num);
                    usage;
                };
                fieldstr++;
            }
            else
            {
                error(0, 0, (options `& SETFLD_ERRMSG_USE_POS) ? gettext("invalid byte/character position %s") : gettext("invalid field value %s"), quote(fieldstr));
                usage;
            };
    };
    if (!n_frp)
        do
        {
            error(0, 0, ((options ? SETFLD_ERRMSG_USE_POS) ? gettext("missing list of byte/character positions") : gettext("missing list of fields")));
            usage;
        }
        while (0);
    qsort(frp, n_frp, (sizeof ( frp [ 0 ] ) / 8), compare_ranges);
    if (options `& SETFLD_COMPLEMENT)
        complement_rp();
    ++n_frp;
    frp = xrealloc(frp, n_frp * (sizeof ( struct field_range_pair ) / 8));
};
