// Auto-generated by cft from: show-date.c
// May require manual edits.

cdecl show_date(byte* format, timespec when, int tz) -> int
{
    tm tm;
    if (!localtime_rz(?, @when.tv_sec, @tm))
    {
        void* /* untranslated: char[INT_BUFSIZE_BOUND(<recovery-expr>())] */ buf = INT_BUFSIZE_BOUND(?);
        error(0, 0, gettext("time %s is out of range"), quote(timetostr(when.tv_sec, buf)));
    };
    if (fprintftime(stdout, format, @tm, ?, when.tv_nsec) < 0)
    {
        if (!ferror(stdout))
            error(0, (?__errno_location()), gettext("fprintftime error"));
    };
};
