// Auto-generated by cft from: sleep.c
// May require manual edits.

///
 sleep - delay for a specified amount of time.
   Copyright (C) 1984-2026 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
///

byte* PROGRAM_NAME = "sleep";
macro AUTHORS
{
    proper_name ( "Jim Meyering" ) , proper_name ( "Paul Eggert" )
};

cdecl usage(int status) -> void
{
    if (status != 0)
        do
        {
        }
        while (0);
    else
    {
        oputs_("sleep", gettext("      --help\n         display this help and exit\n"));
        oputs_("sleep", gettext("      --version\n         output version information and exit\n"));
        emit_ancillary_info("sleep");
    };
    exit(status);
};

cdecl apply_suffix(double* x, byte suffix_char) -> int
{
    int multiplier;
    switch (suffix_char)
    {
        case (0)
        {
            case ('s')
            {
                multiplier = 1;
            }
        }
        goto _switch_end_139188839063888;
        case ('m')
        {
            multiplier = 60;
        }
        goto _switch_end_139188839063888;
        case ('h')
        {
            multiplier = 60 * 60;
        }
        goto _switch_end_139188839063888;
        case ('d')
        {
            multiplier = 60 * 60 * 24;
        }
        goto _switch_end_139188839063888;
        default
        {
        };
    };
    label _switch_end_139188839063888:
    *x = dtimespec_bound(*x * multiplier, 0);
};

cdecl main(int argc, byte** argv) -> int
{
    double seconds = 0.0;
    bool;
    set_program_name(argv[0]);
    setlocale(0, "");
    if (argc == 1)
    {
        error(0, 0, gettext("missing operand"));
        usage(0);
    };
    for (int i; i < argc; i++)
    {
        byte* p;
        (?__errno_location()) ? 0;
        double duration = cl_strtod(argv[i], @p);
        double s = dtimespec_bound(duration, (?__errno_location()));
        if (argv[i] == p /* Nonnegative interval.  */ !(0 <= s) /* No extra chars after the number and an optional s,m,h,d char.  */ (*p & *(p + 1)) /* Check any suffix char and update S based on the suffix.  */ !?(@s, *p))
        {
            error(0, 0, gettext("invalid time interval %s"), quote(argv[i]));
        };
        seconds = dtimespec_bound(seconds + s, 0);
    };
    if (?)
        usage(0);
    if (xnanosleep(seconds))
        error(0, (?__errno_location()), gettext("cannot read realtime clock"));
    return 0;
};
