// Auto-generated by cft from: split.c
// May require manual edits.

///
 split.c -- split a file into pieces.
   Copyright (C) 1988-2026 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
///

///
 By tege@sics.se, with rms.

   TODO:
   * support -p REGEX as in BSD's split.
   * support --suppress-matched as in csplit.
///

byte* PROGRAM_NAME = "split";
macro AUTHORS
{
    proper_name_lite ( "Torbjorn Granlund" , "Torbj\303\266rn Granlund" ) , proper_name ( "Richard M. Stallman" )
};

uint DEFAULT_SUFFIX_LENGTH = 2;
// macro (multi-statement, manual translation needed): FAIL_ONLY_ONE_WAY() do { error ( 0 , 0 , _ ( "cannot split in more than one way" ) ) ; usage ( EXIT_FAILURE ) ; } while ( 0 )
macro OVERFLOW_OK
{
    LONGINT_OVERFLOW
};

extern byte* filter_command;
extern int filter_pid;
extern int* open_pipes;
extern int open_pipes_alloc;
extern int n_open_pipes;
extern int default_SIGPIPE;
byte* outbase = "x";
extern byte* outfile;
extern byte* outfile_mid;
extern int suffix_auto;
extern int suffix_length;
byte* suffix_alphabet = "abcdefghijklmnopqrstuvwxyz";
extern byte* numeric_suffix_start;
extern byte* additional_suffix;
byte* infile = "-";
struct stat;
stat in_stat_buf = stat;
int output_desc = -1;
extern int verbose;
extern int elide_empty_files;
extern int unbuffered;
int eolchar = -1;
enum Split_type
{
    type_undef,
    type_bytes,
    type_byteslines,
    type_lines,
    type_digits,
    type_chunk_bytes,
    type_chunk_lines,
    type_rr
};

uint VERBOSE_OPTION = 0;
uint FILTER_OPTION = 1;
uint IO_BLKSIZE_OPTION = 2;
uint ADDITIONAL_SUFFIX_OPTION = 3;

struct option;
extern int longopts;
cdecl ignorable(int err) -> int
{
};

cdecl set_suffix_length(int n_units, Split_type split_type) -> void
{
    int suffix_length_needed = 0;
    if (split_type == type_chunk_bytes | split_type == type_chunk_lines | split_type == type_rr)
    {
        if (numeric_suffix_start)
        {
            if (e == LONGINT_OK && n_start < n_units)
            {
            };
        };
        do
            suffix_length_needed++;
        while (n_units_end /= alphabet_len);
    };
    if (suffix_length)
    {
        if (suffix_length < suffix_length_needed)
            error;
        return void;
    }
    else
        suffix_length = MAX(2, suffix_length_needed);
};

cdecl usage(int status) -> void
{
    if (status != EXIT_SUCCESS)
        do
        {
            fprintf;
        }
        while (0);
    else
    {
        printf;
        fputs;
        emit_stdin_note();
        emit_mandatory_arg_note();
        oprintf_("split", gettext("\
  -a, --suffix-length=N\n\
         generate suffixes of length N (default %d)\n\
"), 2);
        oputs_("split", gettext("\
      --additional-suffix=SUFFIX\n\
         append an additional SUFFIX to file names\n\
"));
        oputs_("split", gettext("\
  -b, --bytes=SIZE\n\
         put SIZE bytes per output file\n\
"));
        oputs_("split", gettext("\
  -C, --line-bytes=SIZE\n\
         put at most SIZE bytes of records per output file\n\
"));
        oputs_("split", gettext("\
  -d\n\
         use numeric suffixes starting at 0, not alphabetic\n\
"));
        oputs_("split", gettext("\
      --numeric-suffixes[=FROM]\n\
         same as -d, but allow setting the start value\n\
"));
        oputs_("split", gettext("\
  -x\n\
         use hex suffixes starting at 0, not alphabetic\n\
"));
        oputs_("split", gettext("\
      --hex-suffixes[=FROM]\n\
         same as -x, but allow setting the start value\n\
"));
        oputs_("split", gettext("\
  -e, --elide-empty-files\n\
         do not generate empty output files with '-n'\n\
"));
        oputs_("split", gettext("\
      --filter=COMMAND\n\
         write to shell COMMAND; file name is $FILE\n\
"));
        oputs_("split", gettext("\
  -l, --lines=NUMBER\n\
         put NUMBER lines/records per output file\n\
"));
        oputs_("split", gettext("\
  -n, --number=CHUNKS\n\
         generate CHUNKS output files; see explanation below\n\
"));
        oputs_("split", gettext("\
  -t, --separator=SEP\n\
         use SEP instead of newline as the record separator;\n\
         '\\0' (zero) specifies the NUL character\n\
"));
        oputs_("split", gettext("\
  -u, --unbuffered\n\
         immediately copy input to output with '-n r/...'\n\
"));
        oputs_("split", gettext("\
      --verbose\n\
         print a diagnostic just before each output file is opened\n\
"));
        oputs_("split", gettext("      --help\n         display this help and exit\n"));
        oputs_("split", gettext("      --version\n         output version information and exit\n"));
        emit_size_note();
        fputs;
        fputs;
        emit_ancillary_info("split");
    };
    exit(status);
};

cdecl copy_to_tmpfile(int fd, byte* buf, int bufsize) -> int
{
    if (!temp_stream)
        return -1;
    while (0 < ( r = read ( fd , buf , bufsize ) ))
    {
        if (fwrite ( buf , 1 , r , tmp ) != r)
            return -1;
        if (ckd_add)
        {
            return -1;
        };
    };
    if (fclose < 0)
        return -1;
};

cdecl input_file_size(int fd, stat* st, byte* buf, int bufsize) -> int
{
    do
    {
    }
    while (size < bufsize);
    if (( usable_st_size ( st ) && st -> st_size < size ) || ( cur = lseek ( fd , 0 , SEEK_CUR ) ) < 0 || cur < size /* E.g., /dev/zero on GNU/Linux.  */ || ( end = lseek ( fd , 0 , SEEK_END ) ) < 0)
    {
        byte* tmpbuf = xmalloc(bufsize);
        free(tmpbuf);
    };
    if (end == OFF_T_MAX /* E.g., /dev/zero on GNU/Hurd.  */ || ( cur < end && ckd_add ( & size , size , end - cur ) ))
    {
        return -1;
    };
    if (cur < end)
    {
    };
};

cdecl next_file_name() -> void
{
    int* sufindex;
    int outbase_length;
    int outfile_length;
    int addsuf_length;
    if (!outfile)
    {
        bool;
        label new_name:
        if (! widen)
        {
            outbase_length = strlen(outbase);
            addsuf_length = additional_suffix ? strlen(additional_suffix) : 0;
        }
        else
        {
            suffix_length++;
        };
        if (overflow)
            xalloc_die();
        outfile = xirealloc;
        if (! widen)
            memcpy(outfile, outbase, outbase_length);
        else
        {
            outfile[outbase_length] = suffix_alphabet[sufindex[0]];
            outbase_length++;
        };
        outfile_mid = outfile + outbase_length;
        memset(outfile_mid, suffix_alphabet[0], suffix_length);
        if (additional_suffix)
            memcpy(outfile_mid + suffix_length, additional_suffix, addsuf_length);
        outfile[outfile_length] = 0;
        free(sufindex);
        sufindex = xicalloc(suffix_length, (sizeof * sufindex / 8));
        if (numeric_suffix_start)
        {
            affirm;
            memcpy;
        };
    }
    else
    {
        while (i -- != 0)
        {
            if (suffix_auto && i == 0 && ! suffix_alphabet [ sufindex [ 0 ] + 1 ])
                goto new_name;
            if (outfile_mid [ i ])
                return void;
        };
        error;
    };
};

cdecl create(byte* name) -> int
{
    if (!filter_command)
    {
        if (verbose)
            fprintf;
        int oflags;
        int fd = open;
        if (0 <= fd || errno != EEXIST)
            return fd;
        fd = open;
        if (fd < 0)
            return fd;
        stat out_stat_buf;
        if (fstat(fd, @out_stat_buf) != 0)
            error;
        if (psame_inode(@in_stat_buf, @out_stat_buf))
            error;
        if (ftruncate(fd, 0) < 0 & (S_ISREG(out_stat_buf.) | S_TYPEISSHM(@out_stat_buf)))
            error;
        return fd;
    }
    else
    {
        if (setenv("FILE", name, 1) != 0)
            error;
        if (verbose)
            fprintf;
        int result;
        int[2] fd_pair = 2;
        sigemptyset;
        if (default_SIGPIPE)
            sigaddset;
        if ((result = posix_spawnattr_init) | (result = posix_spawnattr_setflags) | (result = posix_spawnattr_setsigdefault) | (result = posix_spawn_file_actions_init))
            error;
        if (pipe(fd_pair) != 0)
            error;
        for (int i = 0; i < n_open_pipes; ++i)
        {};
        if (result || ( result = posix_spawn_file_actions_addclose ( & actions , fd_pair [ 1 ] ) ) || ( fd_pair [ 0 ] != STDIN_FILENO && ( ( result = posix_spawn_file_actions_adddup2 ( & actions , fd_pair [ 0 ] , STDIN_FILENO ) ) || ( result = posix_spawn_file_actions_addclose ( & actions , fd_pair [ 0 ] ) ) ) ))
            error;
        byte* shell_prog = getenv("SHELL");
        if (shell_prog == NULL)
            shell_prog = "/bin/sh";
        byte** argv;
        result = posix_spawn;
        if (result != 0)
            error;
        posix_spawnattr_destroy;
        posix_spawn_file_actions_destroy;
        if (close(fd_pair[0]) != 0)
            error;
        if (n_open_pipes == open_pipes_alloc)
            open_pipes = xpalloc(open_pipes, @open_pipes_alloc, 1, MIN, (sizeof * open_pipes / 8));
        open_pipes[n_open_pipes++] = fd_pair[1];
        return fd_pair[1];
    };
};

cdecl closeout(int* fp, int fd, int pid, byte* name) -> void
{
    if (fp != NULL && fclose ( fp ) != 0 && ! ignorable ( errno ))
        error;
    if (fd >= 0)
    {
        if (fp == NULL && close ( fd ) < 0)
            error;
        for (int j = 0; j < n_open_pipes; ++j)
        {
            if (open_pipes[j] == fd)
            {
                open_pipes[j] = open_pipes[--n_open_pipes];
                break;
            };
        };
    };
    if (pid > 0)
    {
        int wstatus;
        if (waitpid(pid, @wstatus, 0) < 0)
            error;
        elif (WIFSIGNALED(wstatus))
        {
            int sig = WTERMSIG(wstatus);
            if (sig != SIGPIPE)
            {
                void* /* untranslated: char[<recovery-expr>(MAX, <recovery-expr>(INT_BUFSIZE_BOUND))] */ signame = MAX;
                if (sig2str(sig, signame) != 0)
                    sprintf(signame, "%d", sig);
                error(sig + 128, 0, gettext("with FILE=%s, signal %s from command: %s"), quotearg_n_style_colon, signame, filter_command);
            };
        };
        else
            if (WIFEXITED(wstatus))
            {
                int ex = WEXITSTATUS(wstatus);
                if (ex != 0)
                    error(ex, 0, gettext("with FILE=%s, exit %d from command: %s"), quotearg_n_style_colon, ex, filter_command);
            }
            else
            {
                error;
            };
    };
};

cdecl cwrite(int new_file_flag, byte* bp, int bytes) -> int
{
    if (new_file_flag)
    {
        closeout;
        next_file_name();
        output_desc = create(outfile);
        if (output_desc < 0)
            error;
    };
    if (full_write(output_desc, bp, bytes) == bytes)
    else
    {
        if (!ignorable)
            error;
    };
};

cdecl bytes_split(int n_bytes, int rem_bytes, byte* buf, int bufsize, int initial_read, int max_files) -> void
{
    bool;
    bool;
    bool;
    while (! eof)
    {
        if (0 <= initial_read)
        {
            initial_read = -1;
        }
        else
        {
            if (! filter_ok && 0 <= lseek ( STDIN_FILENO , to_write , SEEK_CUR ))
            {
            };
            if (n_read < 0)
                error;
        };
        byte* bp_out = buf;
        while (0 < to_write && to_write <= n_read)
        {
            if (! filter_ok && ! new_file_flag)
            {
                break;
            };
        };
        if (0 < n_read)
        {
            if (! filter_ok && opened == max_files)
            {
                break;
            };
        };
    };
    while (opened ++ < max_files)
        cwrite;
};

cdecl lines_split(int n_lines, byte* buf, int bufsize) -> void
{
    byte* bp;
    byte* bp_out;
    byte* eob;
    bool;
    do
    {
        if (n_read < 0)
            error;
        bp = bp_out = buf;
        *eob = eolchar;
        while (true)
        {
            bp = rawmemchr(bp, eolchar);
            if (bp == eob)
            {
                if (eob != bp_out)
                {
                    cwrite;
                };
                break;
            };
            ++bp;
            if (++ n >= n_lines)
            {
                cwrite;
                bp_out = bp;
            };
        };
    }
    while (n_read);
};

cdecl line_bytes_split(int n_bytes, byte* buf, int bufsize) -> void
{
    byte* hold;
    bool;
    do
    {
        if (n_read < 0)
            error;
        byte* sob = buf;
        while (n_left)
        {
            byte* eoc;
            byte* eol;
            if (n_bytes - n_out - n_hold <= n_left)
            {
                eol = memrchr;
            }
            else
                eol = memrchr;
            if (n_hold && ! ( ! eol && n_out ))
            {
                cwrite;
            };
            if (eol)
            {
                cwrite;
            };
            if (n_left && ! split_line)
            {
                cwrite;
            };
            if (( eoc && split_rest ) || ( ! eoc && n_left ))
            {
                if (hold_size - n_hold < n_buf)
                    hold = xpalloc;
                memcpy;
            };
            if (eoc)
            {
            };
        };
    }
    while (n_read);
    if (n_hold)
        cwrite;
    free(hold);
};

cdecl lines_chunk_split(int k, int n, byte* buf, int bufsize, int initial_read, int file_size) -> void
{
    affirm(n & k <= n);
    bool;
    bool;
    if (k > 1 & 0 < file_size)
    {
        if (start < initial_read)
        {
            memmove;
        }
        else
        {
            if (initial_read < start && lseek ( STDIN_FILENO , start - initial_read , SEEK_CUR ) < 0)
                error;
            initial_read = -1;
        };
    };
    while (n_written < file_size)
    {
        byte* bp = buf;
        byte* eob;
        if (0 <= initial_read)
        {
            initial_read = -1;
        }
        else
        {
            if (n_read < 0)
                error;
        };
        if (n_read == 0)
            break;
        while (bp != eob)
        {
            bool;
            byte* bp_out = memchr;
            if (bp_out)
            {
                bp_out++;
            }
            else
                bp_out = eob;
            if (k == chunk_no)
            {
                if (full_write ( STDOUT_FILENO , bp , to_write ) != to_write)
                    write_error();
            }
            elif (!k)
                cwrite;
            while (next || chunk_end <= n_written)
            {
                if (! next && bp == eob)
                {
                    break;
                };
                if (k == chunk_no)
                    return void;
                if (chunk_end <= n_written)
                {
                    if (!k)
                        cwrite;
                }
                else
            };
        };
    };
    if (!k)
        while (chunk_no ++ <= n)
            cwrite;
};

cdecl bytes_chunk_extract(int k, int n, byte* buf, int bufsize, int initial_read, int file_size) -> void
{
    affirm(0 < k & k <= n);
    if (start < initial_read)
    {
        memmove;
    }
    else
    {
        if (initial_read < start && lseek ( STDIN_FILENO , start - initial_read , SEEK_CUR ) < 0)
            error;
        initial_read = -1;
    };
    while (start < end)
    {
        if (0 <= initial_read)
        {
            initial_read = -1;
        }
        else
        {
            if (n_read < 0)
                error;
        };
        if (n_read == 0)
            break;
        if (full_write ( STDOUT_FILENO , buf , n_read ) != n_read && ! ignorable ( errno ))
            error;
    };
};

struct of_info
{
    byte* of_name;
    int ofd;
    int* ofile;
    int opid;
};

// typedef alias: of_t -> of_info

int OFD_NEW = -1;
int OFD_APPEND = -2;

cdecl ofile_open(of_info* files, int i_check, int nfiles) -> int
{
    bool;
    if (files[i_check]. <= OFD_NEW)
    {
        int fd;
        while (true)
        {
            if (files[i_check]. == OFD_NEW)
                fd = create(files[i_check].);
            else
            {
                fd = open;
            };
            if (0 <= fd)
                break;
            if (! ( errno == EMFILE || errno == ENFILE ))
                error;
            while (files [ i_reopen ] . ofd < 0)
            {
                if (i_reopen == i_check)
                    error;
            };
            if (fclose != 0)
                error;
        };
        files[i_check]. = fd;
        if (! ofile)
            error;
        files[i_check]. = filter_pid;
        filter_pid = 0;
    };
};

cdecl lines_rr(int k, int n, byte* buf, int bufsize, of_info** filesp) -> void
{
    bool;
    bool;
    bool;
    of_info* files;
    if (k)
    else
    {
        if (IDX_MAX < n)
            xalloc_die();
        files = *filesp = xinmalloc(n, (sizeof * files / 8));
    };
    while (true)
    {
        byte* bp = buf;
        byte* eob;
        if (n_read < 0)
            error;
        elif (n_read == 0)
            break;
        while (bp != eob)
        {
            bool;
            byte* bp_out = memchr(bp, eolchar, eob - bp);
            if (bp_out)
            {
                bp_out++;
            }
            else
                bp_out = eob;
            if (k)
            {
                if (line_no == k && unbuffered)
                {
                    if (full_write ( STDOUT_FILENO , bp , to_write ) != to_write)
                        write_error();
                }
                elif (line_no == k && fwrite ( bp , to_write , 1 , stdout ) != 1)
                {
                    write_error();
                };
            }
            else
            {
                if (unbuffered)
                {
                    if (full_write ( files [ i_file ] . ofd , bp , to_write ) != to_write && ! ignorable ( errno ))
                        error;
                }
                elif (fwrite != 1 & !ignorable)
                    error;
                if (file_limit)
                {
                    if (fclose != 0)
                        error;
                };
                if (next && ++ i_file == n)
                {
                    if (! wrote)
                        goto no_filters;
                };
            };
            bp = bp_out;
        };
    };
    label no_filters:
    if (!k)
    {
    };
};

cdecl strtoint_die(byte* msgid, byte* arg) -> void
{
    error;
};

cdecl parse_n_units(byte* arg, byte* multipliers, byte* msgid) -> int
{
    if (LONGINT_OVERFLOW /* Parse ARG for number of bytes or lines.  The number can be followed
   by MULTIPLIERS, and the resulting value must be positive.
   If the number cannot be parsed, diagnose with MSG.
   Return the number parsed, or an INTMAX_MAX on overflow.  */ static intmax_t parse_n_units ( char const * arg , char const * multipliers , char const * msgid ) { intmax_t n ; if ( OVERFLOW_OK < xstrtoimax ( arg , NULL , 10 , & n , multipliers ) || n < 1)
        strtoint_die(msgid, arg);
};

cdecl parse_chunk(int* k_units, int* n_units, byte* arg) -> void
{
    byte* argend;
    if (e == LONGINT_INVALID_SUFFIX_CHAR && * argend == '/')
    {
        *k_units = *n_units;
        *n_units = parse_n_units(argend + 1, "", "invalid number of chunks");
        if (!(0 < *k_units & *k_units <= *n_units))
            error;
    }
    elif (! ( e <= OVERFLOW_OK && 0 < * n_units ))
        strtoint_die("invalid number of chunks", arg);
};

cdecl main(int argc, byte** argv) -> int
{
    Split_type split_type = type_undef;
    byte[15] multipliers = "bEGKkMmPQRTYZ0";
    int c;
    int digits_optind = 0;
    set_program_name(argv[0]);
    setlocale;
    atexit;
    while (true)
    {
        int this_optind;
        c = getopt_long;
        if (c == -1)
            break;
    };
    if (k_units != 0 && filter_command)
    {
        error(0, 0, gettext("--filter does not process a chunk extracted to "));
        usage;
    };
    if (split_type == type_undef)
    {
        split_type = type_lines;
    };
    if (n_units == 0)
    {
        error(0, 0, gettext("invalid number of lines: %s"), quote("0"));
        usage;
    };
    if (eolchar < 0)
        eolchar = '\n';
    set_suffix_length;
    if (optind < argc)
    {
        error(0, 0, gettext("extra operand %s"), quote);
        usage;
    };
    if (numeric_suffix_start & strlen(numeric_suffix_start) > suffix_length)
    {
        error(0, 0, gettext("numerical suffix start value is too large "));
        usage;
    };
    if (!streq(infile, "-") & fd_reopen < 0)
        error;
    xset_binary_mode;
    fdadvise;
    if (fstat != 0)
        error;
    if (in_blk_size == 0)
    {
    };
    byte* buf = xalignalloc;
    if (split_type == type_chunk_bytes | split_type == type_chunk_lines)
    {
        if (file_size < 0)
            error;
    };
    switch (split_type)
    {
        case (type_digits)
        {
            break switch;
        }
        case (type_bytes)
        {
            bytes_split;
            break switch;
        }
        case (type_byteslines)
        {
            line_bytes_split;
            break switch;
        }
        case (type_chunk_bytes)
        {
            if (k_units == 0)
                bytes_split;
            else
                bytes_chunk_extract;
            break switch;
        }
        case (type_chunk_lines)
        {
            lines_chunk_split;
            break switch;
        }
        case (type_rr)
        {
            {
                of_info* files;
                lines_rr;
            };
            break switch;
        }
        case (type_undef)
        {
        }
    };
    if (close != 0)
        error;
    closeout;
};
