// Auto-generated by cft from: split.c
// May require manual edits.

///
 split.c -- split a file into pieces.
   Copyright (C) 1988-2026 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
///

///
 By tege@sics.se, with rms.

   TODO:
   * support -p REGEX as in BSD's split.
   * support --suppress-matched as in csplit.
///

byte* PROGRAM_NAME = "split";
macro AUTHORS
{
    proper_name_lite ( "Torbjorn Granlund" , "Torbj\303\266rn Granlund" ) , proper_name ( "Richard M. Stallman" )
};

uint DEFAULT_SUFFIX_LENGTH = 2;
// macro (multi-statement, manual translation needed): FAIL_ONLY_ONE_WAY() do { error ( 0 , 0 , _ ( "cannot split in more than one way" ) ) ; usage ( EXIT_FAILURE ) ; } while ( 0 )
macro OVERFLOW_OK
{
    LONGINT_OVERFLOW
};

extern byte* filter_command;
int filter_pid = pid_t;
extern int* open_pipes;
extern int open_pipes_alloc;
extern int n_open_pipes;
extern bool default_SIGPIPE;
byte* outbase = "x";
extern byte* outfile;
extern byte* outfile_mid;
bool suffix_auto = 0;
extern int suffix_length;
byte* suffix_alphabet = "abcdefghijklmnopqrstuvwxyz";
extern byte* numeric_suffix_start;
extern byte* additional_suffix;
byte* infile = "-";
stat in_stat_buf = stat;
int output_desc = -1;
extern bool verbose;
extern bool elide_empty_files;
extern bool unbuffered;
int eolchar = -1;
enum Split_type
{
    type_undef,
    type_bytes,
    type_byteslines,
    type_lines,
    type_digits,
    type_chunk_bytes,
    type_chunk_lines,
    type_rr
};

uint VERBOSE_OPTION = 128;
uint FILTER_OPTION = 129;
uint IO_BLKSIZE_OPTION = 130;
uint ADDITIONAL_SUFFIX_OPTION = 131;

option[17] longopts = option;
cdecl ignorable(int err) -> bool
{
    return filter_command & err == 0;
};

cdecl set_suffix_length(long n_units, Split_type split_type) -> void
{
    int suffix_length_needed = 0;
    if (numeric_suffix_start)
        suffix_auto = 0;
    if (split_type == type_chunk_bytes | split_type == type_chunk_lines | split_type == type_rr)
    {
        long n_units_end = n_units - 1;
        if (numeric_suffix_start)
        {
            long n_start;
            if (?)
            {
                if (__builtin_add_overflow((n_units_end), (n_start), (@n_units_end)))
                    n_units_end = (0);
            };
        };
        do
            suffix_length_needed++;
        while (?);
        suffix_auto = 0;
    };
    if (?)
    {
        if (? < suffix_length_needed)
            error(0, 0, gettext("the suffix length needs to be at least %d"), suffix_length_needed);
        suffix_auto = 0;
        return void;
    }
    else
        suffix_length = MAX(2, suffix_length_needed);
};

cdecl usage(int status) -> void
{
    if (status != 0)
        do
        {
        }
        while (0);
    else
    {
        fputs(gettext("\
Output pieces of FILE to PREFIXaa, PREFIXab, ...;\n\
default size is 1000 lines, and default PREFIX is 'x'.\n\
"), stdout);
        emit_stdin_note();
        emit_mandatory_arg_note();
        oprintf_("split", gettext("\
  -a, --suffix-length=N\n\
         generate suffixes of length N (default %d)\n\
"), 2);
        oputs_("split", gettext("\
      --additional-suffix=SUFFIX\n\
         append an additional SUFFIX to file names\n\
"));
        oputs_("split", gettext("\
  -b, --bytes=SIZE\n\
         put SIZE bytes per output file\n\
"));
        oputs_("split", gettext("\
  -C, --line-bytes=SIZE\n\
         put at most SIZE bytes of records per output file\n\
"));
        oputs_("split", gettext("\
  -d\n\
         use numeric suffixes starting at 0, not alphabetic\n\
"));
        oputs_("split", gettext("\
      --numeric-suffixes[=FROM]\n\
         same as -d, but allow setting the start value\n\
"));
        oputs_("split", gettext("\
  -x\n\
         use hex suffixes starting at 0, not alphabetic\n\
"));
        oputs_("split", gettext("\
      --hex-suffixes[=FROM]\n\
         same as -x, but allow setting the start value\n\
"));
        oputs_("split", gettext("\
  -e, --elide-empty-files\n\
         do not generate empty output files with '-n'\n\
"));
        oputs_("split", gettext("\
      --filter=COMMAND\n\
         write to shell COMMAND; file name is $FILE\n\
"));
        oputs_("split", gettext("\
  -l, --lines=NUMBER\n\
         put NUMBER lines/records per output file\n\
"));
        oputs_("split", gettext("\
  -n, --number=CHUNKS\n\
         generate CHUNKS output files; see explanation below\n\
"));
        oputs_("split", gettext("\
  -t, --separator=SEP\n\
         use SEP instead of newline as the record separator;\n\
         '\\0' (zero) specifies the NUL character\n\
"));
        oputs_("split", gettext("\
  -u, --unbuffered\n\
         immediately copy input to output with '-n r/...'\n\
"));
        oputs_("split", gettext("\
      --verbose\n\
         print a diagnostic just before each output file is opened\n\
"));
        oputs_("split", gettext("      --help\n         display this help and exit\n"));
        oputs_("split", gettext("      --version\n         output version information and exit\n"));
        emit_size_note();
        fputs(gettext("\n\
CHUNKS may be:\n\
  N       split into N files based on size of input\n\
  K/N     output Kth of N to standard output\n\
  l/N     split into N files without splitting lines/records\n\
  l/K/N   output Kth of N to standard output without splitting lines/records\n\
  r/N     like 'l' but use round robin distribution\n\
  r/K/N   likewise but only output Kth of N to standard output\n\
"), stdout);
        fputs(gettext("\n\
-n (except -nr) will buffer to $TMPDIR, defaulting to /tmp,\n\
if the input size cannot easily be determined.\n\
"), stdout);
        emit_ancillary_info("split");
    };
    exit(status);
};

cdecl copy_to_tmpfile(int fd, byte* buf, int bufsize) -> long
{
    _IO_FILE* tmp;
    if (!temp_stream(@tmp, ((void*)0)))
        return -1;
    long copied = 0;
    long r;
    while (0 < (r = read(fd, buf, ?)))
    {
        if (fwrite(buf, 1, r, tmp) != r)
            return -1;
        if (__builtin_add_overflow((copied), (r), (@copied)))
        {
            (?__errno_location()) ? 0;
            return -1;
        };
    };
    if (r < 0)
        return r;
    r = dup2(fileno(tmp), fd);
    if (r < 0)
        return r;
    if (fclose(tmp) < 0)
        return -1;
    return copied;
};

cdecl input_file_size(int fd, stat* st, byte* buf, int bufsize) -> long
{
    long size = 0;
    do
    {
        long n_read = read(fd, buf + size, ? - size);
        if (n_read <= 0)
            return n_read < 0 ? n_read : size;
        size += n_read;
    }
    while (size < ?);
    long cur;
    long end;
    if ((?(st) & st.st_size < size) | (cur = lseek(fd, 0, 0)) < 0 | cur < size /* E.g., /dev/zero on GNU/Linux.  */ (end = lseek(fd, 0, 0)) < 0)
    {
        byte* tmpbuf = xmalloc(?);
        end = ?(fd, tmpbuf, ?);
        free(tmpbuf);
        if (end < 0)
            return end;
        cur = 0;
    };
    if (end == TYPE_MAXIMUM(?) /* E.g., /dev/zero on GNU/Hurd.  */ (cur < end & __builtin_add_overflow((size), (end ? cur), (@size))))
    {
        (?__errno_location()) ? 0;
        return -1;
    };
    if (cur < end)
    {
        long r = lseek(fd, cur, 0);
        if (r < 0)
            return r;
    };
    return size;
};

cdecl next_file_name() -> void
{
    int* sufindex;
    int outbase_length;
    int outfile_length;
    int addsuf_length;
    if (!outfile)
    {
        bool overflow;
        bool widen;
        label new_name:
        widen = ?!?;
        if (!widen)
        {
            outbase_length = strlen(outbase);
            addsuf_length = additional_suffix ? strlen(additional_suffix) : 0;
            overflow = __builtin_add_overflow((? ? ?), (?), (@?));
        }
        else
        {
            overflow = __builtin_add_overflow((?), (2), (@?));
            suffix_length++;
        };
        if (overflow)
            xalloc_die();
        if (!widen)
            memcpy(outfile, outbase, ?);
        else
        {
            outfile[?] = suffix_alphabet[?[0]];
            outbase_length++;
        };
        outfile_mid = outfile + ?;
        memset(outfile_mid, suffix_alphabet[0], ?);
        if (additional_suffix)
            memcpy(outfile_mid + ?, additional_suffix, ?);
        outfile[?] = 0;
        free(?);
        sufindex = xicalloc(?, (sizeof * sufindex / 8));
        if (numeric_suffix_start)
        {
            affirm(!widen);
        };
    }
    else
    {
        while (?)
        {
            if (?)
                goto new_name;
            if (?)
                return void;
        };
        error(0, 0, gettext("output file suffixes exhausted"));
    };
};

cdecl create(byte* name) -> int
{
    if (!filter_command)
    {
        int oflags;
        int fd = open(name, oflags `| 0, (0 ? 0 ? (0 ? 0) ? (0 ? 0) ? ((0 ? 0) ? 0) ? ((0 ? 0) ? 0)));
        if (0 <= fd | (?__errno_location()) ? 0)
            return fd;
        fd = open(name, oflags, (0 ? 0 ? (0 ? 0) ? (0 ? 0) ? ((0 ? 0) ? 0) ? ((0 ? 0) ? 0)));
        if (fd < 0)
            return fd;
        stat out_stat_buf;
        return fd;
    }
    else
    {
        if (setenv("FILE", name, 1) != 0)
            error(0, (?__errno_location()), gettext("failed to set FILE environment variable"));
        int result;
        int[2] fd_pair = 2;
        int child_pid;
        posix_spawnattr_t attr;
        posix_spawn_file_actions_t actions;
        __sigset_t set;
        sigemptyset(@set);
        if (default_SIGPIPE)
            sigaddset(@set, 0);
        if (?)
            error(0, result, gettext("posix_spawn initialization failed"));
        if (pipe(fd_pair) != 0)
            error(0, (?__errno_location()), gettext("failed to create pipe"));
        for (int i = 0; i < n_open_pipes; ++i)
        {};
        if (result | (result = posix_spawn_file_actions_addclose(@actions, fd_pair[1])) | (fd_pair[0] != 0 & ((result = posix_spawn_file_actions_adddup2(@actions, fd_pair[0], 0)) | (result = posix_spawn_file_actions_addclose(@actions, fd_pair[0])))))
            error(0, result, gettext("posix_spawn setup failed"));
        byte* shell_prog = getenv("SHELL");
        if (shell_prog == ((void*)0))
            shell_prog = "/bin/sh";
        byte*[4] argv = {last_component(shell_prog), "-c", filter_command, ((void*)0)};
        if (result != 0)
            error(0, (?__errno_location()), gettext("failed to run command: \"%s -c %s\""), shell_prog, filter_command);
        posix_spawnattr_destroy(@attr);
        posix_spawn_file_actions_destroy(@actions);
        if (close(fd_pair[0]) != 0)
            error(0, (?__errno_location()), gettext("failed to close input pipe"));
        filter_pid = child_pid;
        open_pipes[n_open_pipes++] = fd_pair[1];
        return fd_pair[1];
    };
};

cdecl closeout(_IO_FILE* fp, int fd, int pid, byte* name) -> void
{
    if (fd >= 0)
    {
        for (int j = 0; j < n_open_pipes; ++j)
        {
            if (open_pipes[j] == fd)
            {
                open_pipes[j] = open_pipes[--n_open_pipes];
                break;
            };
        };
    };
    if (pid > 0)
    {
        int wstatus;
        if (waitpid(pid, @wstatus, 0) < 0)
            error(0, (?__errno_location()), gettext("waiting for child process"));
        elif ((((byte)(((wstatus) ? 0) ? 0) ? 0) ? 0))
        {
            int sig = ((wstatus) ? 0);
            if (sig != 0)
            {
                byte signame;
                if (sig2str(sig, ?) != 0)
                    sprintf(?, "%d", sig);
            };
        };
        else
            if ((((wstatus) ? 0) ? 0))
            {
                int ex = (((wstatus) ? 0) ? 0);
            }
            else
            {
                error(0, 0, gettext("unknown status from command (0x%X)"), wstatus + 0u);
            };
    };
};

cdecl cwrite(bool new_file_flag, byte* bp, int bytes) -> bool
{
    if (new_file_flag)
    {
        if (!bp & ? == 0 & elide_empty_files)
            return 0;
        closeout(((void*)0), output_desc, filter_pid, outfile);
        next_file_name();
        output_desc = create(outfile);
    };
    if (full_write(output_desc, bp, ?) == ?)
        return 0;
    else
    {
        return 0;
    };
};

cdecl bytes_split(long n_bytes, long rem_bytes, byte* buf, int bufsize, long initial_read, long max_files) -> void
{
    bool new_file_flag = 0;
    bool filter_ok = 0;
    long opened = 0;
    long to_write = n_bytes + (0 < rem_bytes);
    bool eof = !to_write;
    while (!eof)
    {
        long n_read;
        if (0 <= initial_read)
        {
            n_read = initial_read;
            initial_read = -1;
            eof = n_read < ?;
        }
        else
        {
            if (!filter_ok & 0 <= lseek(0, to_write, 0))
            {
                to_write = n_bytes + (opened + 1 < rem_bytes);
                new_file_flag = 0;
            };
            n_read = read(0, buf, ?);
            eof = n_read == 0;
        };
        byte* bp_out = buf;
        while (0 < to_write & to_write <= n_read)
        {
            if (filter_ok | new_file_flag)
                filter_ok = ?(new_file_flag, bp_out, to_write);
            opened += new_file_flag;
            new_file_flag = !max_files | (opened < max_files);
            if (!filter_ok & !new_file_flag)
            {
                n_read = 0;
                eof = 0;
                break;
            };
            bp_out += to_write;
            n_read -= to_write;
            to_write = n_bytes + (opened < rem_bytes);
        };
        if (0 < n_read)
        {
            if (filter_ok | new_file_flag)
                filter_ok = ?(new_file_flag, bp_out, n_read);
            opened += new_file_flag;
            new_file_flag = 0;
            if (!filter_ok & opened == max_files)
            {
                break;
            };
            to_write -= n_read;
        };
    };
    while (opened++ < max_files)
        cwrite(0, ((void*)0), 0);
};

cdecl lines_split(long n_lines, byte* buf, int bufsize) -> void
{
    long n_read;
    byte* bp;
    byte* bp_out;
    byte* eob;
    bool new_file_flag = 0;
    long n = 0;
    do
    {
        n_read = read(0, buf, ?);
        bp = bp_out = buf;
        eob = bp + n_read;
        *eob = eolchar;
        while (0)
        {
            bp = rawmemchr(bp, eolchar);
            if (bp == eob)
            {
                if (eob != bp_out)
                {
                    new_file_flag = 0;
                };
                break;
            };
            ++bp;
            if (++n >= n_lines)
            {
                cwrite(new_file_flag, bp_out, bp - bp_out);
                bp_out = bp;
                new_file_flag = 0;
                n = 0;
            };
        };
    }
    while (n_read);
};

cdecl line_bytes_split(long n_bytes, byte* buf, int bufsize) -> void
{
    long n_read;
    long n_out = 0;
    byte* hold = ((void*)0);
    bool split_line = 0;
    do
    {
        n_read = read(0, buf, ?);
        byte* sob = buf;
        while (?)
        {
            byte* eoc = ((void*)0);
            byte* eol;
            if (?)
            {
            }
            else
            if (?)
            {
            };
            if (eol)
            {
                split_line = 0;
            };
            if (?)
            {
            };
            if (?)
            {
            };
            if (eoc)
            {
                n_out = 0;
                split_line = 0;
            };
        };
    }
    while (n_read);
    free(hold);
};

cdecl lines_chunk_split(long k, long n, byte* buf, int bufsize, long initial_read, long file_size) -> void
{
    affirm(n & k <= n);
    long rem_bytes = file_size % n;
    long chunk_size = file_size / n;
    long chunk_no = 1;
    long chunk_end = chunk_size + (0 < rem_bytes);
    long n_written = 0;
    bool new_file_flag = 0;
    bool chunk_truncated = 0;
    if (k > 1 & 0 < file_size)
    {
        long start = (k - 1) * chunk_size + MIN(k - 1, rem_bytes) - 1;
        if (start < initial_read)
        {
            memmove(buf, buf + start, initial_read - start);
            initial_read -= start;
        }
        else
        {
            initial_read = -1;
        };
        n_written = start;
        chunk_no = k - 1;
        chunk_end = start + 1;
    };
    while (n_written < file_size)
    {
        byte* bp = buf;
        byte* eob;
        long n_read;
        if (0 <= initial_read)
        {
            n_read = initial_read;
            initial_read = -1;
        }
        else
        {
            n_read = read(0, buf, MIN(?, file_size - n_written));
        };
        if (n_read == 0)
            break;
        chunk_truncated = 0;
        eob = buf + n_read;
        while (bp != eob)
        {
            bool next = 0;
            long skip = MIN(n_read, MAX(0, chunk_end - 1 - n_written));
            byte* bp_out = memchr(bp + skip, eolchar, n_read - skip);
            if (bp_out)
            {
                bp_out++;
                next = 0;
            }
            else
                bp_out = eob;
            if (k == chunk_no)
            {
                if (?)
                    write_error();
            }
            else
            new_file_flag = next;
            while (next | chunk_end <= n_written)
            {
                if (!next & bp == eob)
                {
                    chunk_truncated = 0;
                    break;
                };
                if (k == chunk_no)
                    return void;
                chunk_end += chunk_size + (chunk_no < rem_bytes);
                chunk_no++;
                if (chunk_end <= n_written)
                {
                    if (!k)
                        cwrite(0, ((void*)0), 0);
                }
                else
                    next = 0;
            };
        };
    };
    if (chunk_truncated)
        chunk_no++;
    if (!k)
        while (chunk_no++ <= n)
            cwrite(0, ((void*)0), 0);
};

cdecl bytes_chunk_extract(long k, long n, byte* buf, int bufsize, long initial_read, long file_size) -> void
{
    long start;
    long end;
    affirm(0 < k & k <= n);
    start = (k - 1) * (file_size / n) + MIN(k - 1, file_size % n);
    end = k == n ? file_size : k * (file_size / n) + MIN(k, file_size % n);
    if (start < initial_read)
    {
        memmove(buf, buf + start, initial_read - start);
        initial_read -= start;
    }
    else
    {
        initial_read = -1;
    };
    while (start < end)
    {
        long n_read;
        if (0 <= initial_read)
        {
            n_read = initial_read;
            initial_read = -1;
        }
        else
        {
            n_read = read(0, buf, ?);
        };
        if (n_read == 0)
            break;
        n_read = MIN(n_read, end - start);
        start += n_read;
    };
};

struct of_info
{
    byte* of_name;
    int ofd;
    _IO_FILE* ofile;
    int opid;
};

// typedef alias: of_t -> of_info

int OFD_NEW = -1;
int OFD_APPEND = -2;

cdecl ofile_open(of_info* files, int i_check, int nfiles) -> bool
{
    bool file_limit = 0;
    if (files[?]. <= OFD_NEW)
    {
        int fd;
        while (0)
        {
            if (files[?]. == OFD_NEW)
                fd = create(files[?].);
            else
            {
            };
            if (0 <= fd)
                break;
            file_limit = 0;
            while (?)
            {
            };
        };
        files[?]. = fd;
        _IO_FILE* ofile = fdopen(fd, "a");
        files[?]. = ofile;
        files[?]. = filter_pid;
        filter_pid = 0;
    };
    return file_limit;
};

cdecl lines_rr(long k, long n, byte* buf, int bufsize, of_info** filesp) -> void
{
    bool wrapped = 0;
    bool wrote = 0;
    bool file_limit;
    of_info* files;
    long line_no;
    if (k)
        line_no = 1;
    else
    {
        if (?)
            xalloc_die();
        files = *filesp = xinmalloc(n, (sizeof * files / 8));
        file_limit = 0;
    };
    while (0)
    {
        byte* bp = buf;
        byte* eob;
        long n_read = read(0, buf, ?);
        if (n_read < 0)
        elif (n_read == 0)
            break;
        eob = buf + n_read;
        while (bp != eob)
        {
            bool next = 0;
            byte* bp_out = memchr(bp, eolchar, eob - bp);
            if (bp_out)
            {
                bp_out++;
                next = 0;
            }
            else
                bp_out = eob;
            if (k)
            {
                if (line_no == k & unbuffered)
                {
                    if (?)
                        write_error();
                }
                elif (?)
                {
                    write_error();
                };
                if (next)
                    line_no = (line_no == n) ? 1 : line_no + 1;
            }
            else
            {
                if (unbuffered)
                {
                }
                else
                if (!ignorable((?__errno_location())))
                    wrote = 0;
                if (file_limit)
                {
                };
                if (?)
                {
                    wrapped = 0;
                    if (!wrote)
                        goto no_filters;
                    wrote = 0;
                };
            };
            bp = bp_out;
        };
    };
    label no_filters:
    if (!k)
    {
    };
};

cdecl strtoint_die(byte* msgid, byte* arg) -> void
{
    error(0, (?__errno_location()) ? 0 ? 0 : (?__errno_location()), "%s: %s", gettext(msgid), quote(arg));
};

cdecl parse_n_units(byte* arg, byte* multipliers, byte* msgid) -> long
{
    long n;
    if (?)
        strtoint_die(msgid, arg);
    return n;
};

cdecl parse_chunk(long* k_units, long* n_units, byte* arg) -> void
{
    byte* argend;
    if (?)
    {
        *k_units = *n_units;
        *n_units = parse_n_units(argend + 1, "", "invalid number of chunks");
        if (!(0 < *k_units & *k_units <= *n_units))
            error(0, 0, "%s: %s", gettext("invalid chunk number"), quote_mem(arg, argend - arg));
    }
    elif (?)
        strtoint_die("invalid number of chunks", arg);
};

cdecl main(int argc, byte** argv) -> int
{
    Split_type split_type = type_undef;
    long k_units = 0;
    long n_units = 0;
    byte[15] multipliers = "bEGKkMmPQRTYZ0";
    int c;
    int digits_optind = 0;
    long file_size = TYPE_MAXIMUM(?);
    set_program_name(argv[0]);
    setlocale(0, "");
    while (0)
    {
        int this_optind = optind ? optind : 1;
        c = getopt_long(argc, argv, "0123456789C:a:b:del:n:t:ux", longopts, ((void*)0));
        if (c == -1)
            break;
        switch (c)
        {
            case ('a')
            {
            }
            goto _switch_end_139188829383248;
            case (ADDITIONAL_SUFFIX_OPTION)
            {
                {
                    int suffix_len = strlen(optarg);
                    if (last_component(optarg) != optarg | (suffix_len & ISSLASH(optarg[suffix_len - 1])))
                    {
                        error(0, 0, gettext("invalid suffix %s, contains directory separator"), quote(optarg));
                        usage(0);
                    };
                };
            }
            additional_suffix = optarg;
            goto _switch_end_139188829383248;
            case ('b')
            {
                if (split_type != type_undef)
                    do
                    {
                        error(0, 0, gettext("cannot split in more than one way"));
                        usage(0);
                    }
                    while (0);
            }
            split_type = type_bytes;
            n_units = parse_n_units(optarg, multipliers, "invalid number of bytes");
            goto _switch_end_139188829383248;
            case ('l')
            {
                if (split_type != type_undef)
                    do
                    {
                        error(0, 0, gettext("cannot split in more than one way"));
                        usage(0);
                    }
                    while (0);
            }
            split_type = type_lines;
            n_units = parse_n_units(optarg, "", "invalid number of lines");
            goto _switch_end_139188829383248;
            case ('C')
            {
                if (split_type != type_undef)
                    do
                    {
                        error(0, 0, gettext("cannot split in more than one way"));
                        usage(0);
                    }
                    while (0);
            }
            split_type = type_byteslines;
            n_units = parse_n_units(optarg, multipliers, "invalid number of lines");
            goto _switch_end_139188829383248;
            case ('n')
            {
                if (split_type != type_undef)
                    do
                    {
                        error(0, 0, gettext("cannot split in more than one way"));
                        usage(0);
                    }
                    while (0);
            }
            while (((?__ctype_b_loc())[(int)((to_uchar(*optarg)))] ? (uint)_ISspace))
                optarg++;
            if (strncmp(optarg, "", ( / 8) ? 0) ? 0)
            {
                split_type = type_rr;
                optarg += 2;
            }
            elif (strncmp(optarg, "", ( / 8) ? 0) ? 0)
            {
                split_type = type_chunk_lines;
                optarg += 2;
            };
            else
                split_type = type_chunk_bytes;
            parse_chunk(@k_units, @n_units, optarg);
            goto _switch_end_139188829383248;
            case ('u')
            {
                unbuffered = 0;
            }
            goto _switch_end_139188829383248;
            case ('t')
            {
                {
                    byte neweol = optarg[0];
                    if (!neweol)
                        error(0, 0, gettext("empty record separator"));
                    if (optarg[1])
                    {
                        if (streq(optarg, "\\0"))
                            neweol = '\0';
                        else
                        {
                            error(0, 0, gettext("multi-character separator %s"), quote(optarg));
                        };
                    };
                    if (0 <= eolchar & neweol != eolchar)
                    {
                        error(0, 0, gettext("multiple separator characters specified"));
                    };
                    eolchar = neweol;
                };
            }
            goto _switch_end_139188829383248;
            case ('0')
            {
                case ('1')
                {
                    case ('2')
                    {
                        case ('3')
                        {
                            case ('4')
                            {
                                case ('5')
                                {
                                    case ('6')
                                    {
                                        case ('7')
                                        {
                                            case ('8')
                                            {
                                                case ('9')
                                                {
                                                    if (split_type == type_undef)
                                                    {
                                                        split_type = type_digits;
                                                        n_units = 0;
                                                    };
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            if (split_type != type_undef & split_type != type_digits)
                do
                {
                    error(0, 0, gettext("cannot split in more than one way"));
                    usage(0);
                }
                while (0);
            if (digits_optind != 0 & digits_optind != this_optind)
                n_units = 0;
            digits_optind = this_optind;
            if (__builtin_mul_overflow((n_units), (10), (@n_units)) ? __builtin_add_overflow((n_units), (c ? '0'), (@n_units)))
                n_units = (0);
            goto _switch_end_139188829383248;
            case ('d')
            {
                case ('x')
                {
                    if (c == 'd')
                        suffix_alphabet = "0123456789";
                    else
                        suffix_alphabet = "0123456789abcdef";
                }
            }
            if (optarg)
            {
                if (strlen(optarg) != strspn(optarg, suffix_alphabet))
                {
                    error(0, 0, (c == 'd') ? gettext("%s: invalid start value for numerical suffix") : gettext("%s: invalid start value for hexadecimal suffix"), quote(optarg));
                    usage(0);
                }
                else
                {
                    while (*optarg == '0' & *(optarg + 1) != '\0')
                        optarg++;
                    numeric_suffix_start = optarg;
                };
            };
            goto _switch_end_139188829383248;
            case ('e')
            {
                elide_empty_files = 0;
            }
            goto _switch_end_139188829383248;
            case (FILTER_OPTION)
            {
                filter_command = optarg;
            }
            goto _switch_end_139188829383248;
            case (IO_BLKSIZE_OPTION)
            {
            }
            goto _switch_end_139188829383248;
            case (VERBOSE_OPTION)
            {
                verbose = 0;
            }
            goto _switch_end_139188829383248;
            case (GETOPT_HELP_CHAR)
            {
                usage(0);
            }
            goto _switch_end_139188829383248;
            case (GETOPT_VERSION_CHAR)
            {
            }
            exit(0);
            goto _switch_end_139188829383248;
            default
            {
                usage(0);
            };
        };
        label _switch_end_139188829383248:
    };
    if (k_units != 0 & filter_command)
    {
        error(0, 0, gettext("--filter does not process a chunk extracted to "));
        usage(0);
    };
    if (split_type == type_undef)
    {
        split_type = type_lines;
        n_units = 1000;
    };
    if (n_units == 0)
    {
        error(0, 0, gettext("invalid number of lines: %s"), quote("0"));
        usage(0);
    };
    if (eolchar < 0)
        eolchar = '\n';
    set_suffix_length(n_units, split_type);
    if (optind < argc)
        infile = argv[optind++];
    if (optind < argc)
        outbase = argv[optind++];
    if (optind < argc)
    {
        error(0, 0, gettext("extra operand %s"), quote(argv[optind]));
        usage(0);
    };
    if (numeric_suffix_start & strlen(numeric_suffix_start) > ?)
    {
        error(0, 0, gettext("numerical suffix start value is too large "));
        usage(0);
    };
    if (?)
    {
    };
    byte* buf;
    long initial_read = -1;
    if (split_type == type_chunk_bytes | split_type == type_chunk_lines)
    {
    };
    if (filter_command)
        default_SIGPIPE = signal(0, ((def{}*(int) -> void)0)) == ((def{}*(int) -> void)0);
    switch (split_type)
    {
        case (type_digits)
        {
            case (type_lines)
            {
            }
        }
        goto _switch_end_139188829384016;
        case (type_bytes)
        {
        }
        goto _switch_end_139188829384016;
        case (type_byteslines)
        {
        }
        goto _switch_end_139188829384016;
        case (type_chunk_bytes)
        {
        }
        goto _switch_end_139188829384016;
        case (type_chunk_lines)
        {
        }
        goto _switch_end_139188829384016;
        case (type_rr)
        {
            {
                of_info* files;
            };
        }
        goto _switch_end_139188829384016;
        case (type_undef)
        {
            default
            {
                affirm(0);
            };
        }
    };
    label _switch_end_139188829384016:
    closeout(((void*)0), output_desc, filter_pid, outfile);
    return 0;
};
