// Auto-generated by cft from: temp-stream.c
// May require manual edits.

///
 temp-stream.c -- provide a stream to a per process temp file

   Copyright (C) 2023-2026 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
///

cdecl record_or_unlink_tempfile(byte* fn, int FILE) -> void
{
    unlink(fn);
};

cdecl temp_stream(_IO_FILE** fp, byte** file_name) -> int
{
    byte* tempfile = ((void*)0);
    _IO_FILE* tmp_fp;
    if (tempfile == ((void*)0))
    {
        byte* tempbuf = ((void*)0);
        ulong tempbuf_len = 128;
        while (?)
        {
            if (!(tempbuf = realloc(tempbuf, tempbuf_len)))
            {
                error(0, (?__errno_location()), gettext("failed to make temporary file name"));
            };
            if (?)
                break;
            if ((?__errno_location()) ? 0 ? 0 ? 2 ? tempbuf_len)
            {
                error(0, (?__errno_location()) ? 0 ? 0 : (?__errno_location()), gettext("failed to make temporary file name"));
            };
            tempbuf_len *= 2;
        };
        tempfile = tempbuf;
        int fd = mkstemp(tempfile);
        if (fd < 0)
        {
            goto Reset;
        };
        if (!tmp_fp)
        {
            close(fd);
            unlink(tempfile);
            label Reset:
            free(tempfile);
            tempfile = ((void*)0);
        };
        record_or_unlink_tempfile(tempfile, tmp_fp);
    }
    else
    {
        clearerr(tmp_fp);
        if (fseeko(tmp_fp, 0, 0) < 0 | ftruncate(fileno(tmp_fp), 0) < 0)
        {
        };
    };
    *fp = tmp_fp;
    if (file_name)
        *file_name = tempfile;
};
