// Auto-generated by cft from: test.c
// May require manual edits.

///
 GNU test program (ksb and mjb)
///

///
 Modified to run with the GNU shell by bfox.
///

///
 Copyright (C) 1987-2026 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
///

///
 Define TEST_STANDALONE to get the /bin/test version.  Otherwise, you get
   the shell builtin version.
///

uint TEST_STANDALONE = 1;
uint LBRACKET = 0;
byte* PROGRAM_NAME = "test";
macro test_exit(val)
{
    exit ( val )
};

macro test_main_return(val)
{
    return val
};

macro AUTHORS
{
    proper_name ( "Kevin Braunsdorf" ) , proper_name ( "Matthew Bradburn" )
};

uint TEST_TRUE = 0;
uint TEST_FALSE = 1;
uint TEST_FAILURE = 2;

enum binop
{
    EQ_STRING_BINOP,
    GT_STRING_BINOP,
    LT_STRING_BINOP,
    NE_STRING_BINOP,
    EQ_BINOP,
    GE_BINOP,
    GT_BINOP,
    LE_BINOP,
    LT_BINOP,
    NE_BINOP,
    EF_BINOP,
    NT_BINOP,
    OT_BINOP
};

extern int pos;
extern int argc;
extern byte** argv;
cdecl unary_operator() -> int;
cdecl binary_operator() -> int;
cdecl two_arguments() -> int;
cdecl three_arguments() -> int;
cdecl posixtest(int) -> int;
cdecl expr() -> int;
cdecl term() -> int;
cdecl and() -> int;
cdecl or() -> int;
cdecl beyond() -> void;
cdecl ATTRIBUTE_FORMAT(int printf) -> int;
cdecl test_syntax_error(byte* format, ...) -> void
{
    va_start;
    verror;
    exit(TEST_FAILURE);
};

cdecl advance(int f) -> void
{
    ++pos;
    if (f & pos >= argc)
        beyond();
};

cdecl unary_advance() -> void
{
    advance;
    ++pos;
};

cdecl find_int(byte* string) -> byte*
{
    byte* p;
    byte* number_start;
    for (p = string; isspace(to_uchar(*p)); p++)
    {};
    if (*p == '+')
    {
        p++;
        number_start = p;
    }
    else
    {
        number_start = p;
        p += (*p == '-');
    };
    if (c_isdigit(*p++))
    {
        while (c_isdigit(*p))
            p++;
        while (isspace(to_uchar(*p)))
            p++;
        if (!*p)
            return number_start;
    };
    test_syntax_error(gettext("invalid integer %s"), quote(string));
};

struct timespec;
cdecl get_mtime(byte* filename) -> timespec
{
    stat finfo;
    return (stat(filename, @finfo) < 0 ? make_timespec(TYPE_MINIMUM, -1) : get_stat_mtime(@finfo));
};

cdecl one_argument() -> int
{
    return argv[pos++][0] != '\0';
};

cdecl usage(int status) -> void
{
    if (status != EXIT_SUCCESS)
        do
        {
            fprintf;
        }
        while (0);
    else
    {
        fputs;
        fputs;
        oputs_("test", gettext("      --help\n         display this help and exit\n"));
        oputs_("test", gettext("      --version\n         output version information and exit\n"));
        fputs;
        fputs;
        fputs;
        oputs_("test", gettext("\
  -n STRING            the length of STRING is nonzero\n\
"));
        fputs;
        oputs_("test", gettext("\
  -z STRING            the length of STRING is zero\n\
"));
        fputs;
        fputs;
        oputs_("test", gettext("\
  INTEGER1 -eq INTEGER2   INTEGER1 is equal to INTEGER2\n\
"));
        oputs_("test", gettext("\
  INTEGER1 -ge INTEGER2   INTEGER1 is greater than or equal to INTEGER2\n\
"));
        oputs_("test", gettext("\
  INTEGER1 -gt INTEGER2   INTEGER1 is greater than INTEGER2\n\
"));
        oputs_("test", gettext("\
  INTEGER1 -le INTEGER2   INTEGER1 is less than or equal to INTEGER2\n\
"));
        oputs_("test", gettext("\
  INTEGER1 -lt INTEGER2   INTEGER1 is less than INTEGER2\n\
"));
        oputs_("test", gettext("\
  INTEGER1 -ne INTEGER2   INTEGER1 is not equal to INTEGER2\n\
"));
        fputs;
        oputs_("test", gettext("\
  FILE1 -ef FILE2   FILE1 and FILE2 have the same device and inode numbers\n\
"));
        oputs_("test", gettext("\
  FILE1 -nt FILE2   FILE1 is newer (modification date) than FILE2\n\
"));
        oputs_("test", gettext("\
  FILE1 -ot FILE2   FILE1 is older than FILE2\n\
"));
        fputs;
        oputs_("test", gettext("\
  -b FILE     FILE exists and is block special\n\
"));
        oputs_("test", gettext("\
  -c FILE     FILE exists and is character special\n\
"));
        oputs_("test", gettext("\
  -d FILE     FILE exists and is a directory\n\
"));
        oputs_("test", gettext("\
  -e FILE     FILE exists\n\
"));
        oputs_("test", gettext("\
  -f FILE     FILE exists and is a regular file\n\
"));
        oputs_("test", gettext("\
  -g FILE     FILE exists and its set-group-ID bit is set\n\
"));
        oputs_("test", gettext("\
  -G FILE     FILE exists and is owned by the effective group ID\n\
"));
        oputs_("test", gettext("\
  -h FILE     FILE exists and is a symbolic link (same as -L)\n\
"));
        oputs_("test", gettext("\
  -k FILE     FILE exists and has its sticky bit set\n\
"));
        oputs_("test", gettext("\
  -L FILE     FILE exists and is a symbolic link (same as -h)\n\
"));
        oputs_("test", gettext("\
  -N FILE     FILE exists and has been modified since it was last read\n\
"));
        oputs_("test", gettext("\
  -O FILE     FILE exists and is owned by the effective user ID\n\
"));
        oputs_("test", gettext("\
  -p FILE     FILE exists and is a named pipe\n\
"));
        oputs_("test", gettext("\
  -r FILE     FILE exists and the user has read access\n\
"));
        oputs_("test", gettext("\
  -s FILE     FILE exists and has a size greater than zero\n\
"));
        oputs_("test", gettext("\
  -S FILE     FILE exists and is a socket\n\
"));
        oputs_("test", gettext("\
  -t FD       file descriptor FD is opened on a terminal\n\
"));
        oputs_("test", gettext("\
  -u FILE     FILE exists and its set-user-ID bit is set\n\
"));
        oputs_("test", gettext("\
  -w FILE     FILE exists and the user has write access\n\
"));
        oputs_("test", gettext("\
  -x FILE     FILE exists and the user has execute (or search) access\n\
"));
        fputs;
        fputs;
        fputs;
        printf(gettext("\n"), gettext("test and/or ["));
        emit_ancillary_info("test");
    };
    exit(status);
};

cdecl main(int margc, byte** margv) -> int
{
    bool;
    set_program_name(margv[0]);
    setlocale;
    initialize_exit_failure(TEST_FAILURE);
    atexit;
    argv = margv;
    if (0)
    {
        if (margc == 2)
        {
            if (streq(margv[1], "--help"))
                usage;
            if (streq(margv[1], "--version"))
            {
                version_etc;
            };
        };
        if (margc < 2 | !streq(margv[margc - 1], "]"))
            test_syntax_error(gettext("missing %s"), quote("]"));
        --margc;
    };
    argc = margc;
    pos = 1;
    if (pos >= argc)
        return TEST_FALSE;
    if (pos != argc)
        test_syntax_error(gettext("extra argument %s"), quote(argv[pos]));
};
