// Auto-generated by cft from: tty.c
// May require manual edits.

///
 tty -- print the name of the terminal connected to standard input
   Copyright (C) 1990-2026 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
///

///
 Displays "not a tty" if stdin is not a terminal.
   Displays nothing if -s option is given.
   Exit status 0 if stdin is a tty, 1 if not a tty, 2 if usage error,
   3 if write error.

   Written by David MacKenzie <djm@gnu.ai.mit.edu>.
///

byte* PROGRAM_NAME = "tty";
macro AUTHORS
{
    proper_name ( "David MacKenzie" )
};

uint TTY_STDIN_NOTTY = 1;
uint TTY_USAGE = 2;
uint TTY_WRITE_ERROR = 3;
uint TTY_TTYNAME_FAILURE = 4;

extern int silent;
option[5] longopts = option;
cdecl usage(int status) -> void
{
    if (status != 0)
        do
        {
        }
        while (0);
    else
    {
        fputs(gettext("\
Print the file name of the terminal connected to standard input.\n\
\n\
"), stdout);
        oputs_("tty", gettext("\
  -s, --silent, --quiet\n\
         print nothing, only return an exit status\n\
"));
        oputs_("tty", gettext("      --help\n         display this help and exit\n"));
        oputs_("tty", gettext("      --version\n         output version information and exit\n"));
        emit_ancillary_info("tty");
    };
    exit(status);
};

cdecl main(int argc, byte** argv) -> int
{
    int optc;
    set_program_name(argv[0]);
    setlocale(0, "");
    initialize_exit_failure(TTY_WRITE_ERROR);
    while ((optc = getopt_long(argc, argv, "s", longopts, ((void*)0))) != -1)
    {
        switch (optc)
        {
            case ('s')
            {
            }
            goto _switch_end_139188837837008;
            case (GETOPT_HELP_CHAR)
            {
                usage(0);
            }
            goto _switch_end_139188837837008;
            case (GETOPT_VERSION_CHAR)
            {
            }
            exit(0);
            goto _switch_end_139188837837008;
            default
            {
                usage(TTY_USAGE);
            };
        };
        label _switch_end_139188837837008:
    };
    if (optind < argc)
    {
        error(0, 0, gettext("extra operand %s"), quote(argv[optind]));
        usage(TTY_USAGE);
    };
    if (?)
        return isatty(0) ? 0 : TTY_STDIN_NOTTY;
    int status;
    byte* tty = ttyname(0);
    if (tty)
        status = 0;
    else
    {
        int ttyname_err = (?__errno_location());
        if (isatty(0))
            error(TTY_TTYNAME_FAILURE, ttyname_err, gettext("ttyname error"));
        tty = gettext("not a tty");
        status = TTY_STDIN_NOTTY;
    };
    puts(tty);
    return status;
};
