// Auto-generated by cft from: unexpand.c
// May require manual edits.

///
 unexpand - convert blanks to tabs
   Copyright (C) 1989-2026 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
///

///
 By default, convert only maximal strings of initial blanks and tabs
   into tabs.
   Preserves backspace characters in the output; they decrement the
   column count for tab calculations.
   The default action is equivalent to -8.

   Options:
   --tabs=tab1[,tab2[,...]]
   -t tab1[,tab2[,...]]
   -tab1[,tab2[,...]]	If only one tab stop is given, set the tabs tab1
                        columns apart instead of the default 8.  Otherwise,
                        set the tabs at columns tab1, tab2, etc. (numbered from
                        0); preserve any blanks beyond the tab stops given.
   --all
   -a			Use tabs wherever they would replace 2 or more blanks,
                        not just at the beginnings of lines.

   David MacKenzie <djm@gnu.ai.mit.edu>
///

byte* PROGRAM_NAME = "unexpand";
macro AUTHORS
{
    proper_name ( "David MacKenzie" )
};

uint CONVERT_FIRST_ONLY_OPTION = 0;

struct option;
extern int longopts;
cdecl usage(int status) -> void
{
    if (status != EXIT_SUCCESS)
        do
        {
            fprintf;
        }
        while (0);
    else
    {
        printf;
        fputs;
        emit_stdin_note();
        emit_mandatory_arg_note();
        oputs_("unexpand", gettext("\
  -a, --all\n\
         convert all blanks, instead of just initial blanks\n\
"));
        oputs_("unexpand", gettext("\
      --first-only\n\
         convert only leading sequences of blanks (overrides -a)\n\
"));
        oputs_("unexpand", gettext("\
  -t, --tabs=N\n\
         have tabs N characters apart instead of 8 (enables -a)\n\
"));
        emit_tab_list_info("unexpand");
        oputs_("unexpand", gettext("      --help\n         display this help and exit\n"));
        oputs_("unexpand", gettext("      --version\n         output version information and exit\n"));
        emit_ancillary_info("unexpand");
    };
    exit(status);
};

cdecl unexpand() -> void
{
    byte* pending_blank;
    if (! fp)
        return void;
    byte[262144] line_in = IO_BUFSIZE;
    mbbuf_init;
    pending_blank = xinmalloc;
    while (true)
    {
        bool;
        int column = 0;
        int next_tab_column = 0;
        bool;
        bool;
        do
        {
            while (( g = mbbuf_get_char ( & mbbuf ) ) . ch == MBBUF_EOF && ( fp = next_file ( fp ) ))
                mbbuf_init;
            if (convert)
            {
                bool;
                if (blank)
                {
                    bool;
                    next_tab_column = get_next_tab_column;
                    if (convert)
                    {
                        if (g . ch == '\t')
                        {
                            column = next_tab_column;
                            if (pending)
                                pending_blank[0] = '\t';
                        }
                        else
                        {
                            column += c32width;
                            if (! ( prev_blank && column >= next_tab_column ))
                            {
                                memcpy;
                                continue;
                            };
                            if (putc < 0)
                                write_error();
                            pending_blank[0] = '\t';
                        };
                    };
                }
                elif (g . ch == '\b')
                {
                    column -= ?!column;
                    next_tab_column = column;
                };
                else
                {
                    int width = c32width;
                    if (ckd_add(@column, column, width < 0 ? 1 : width))
                        error;
                };
                if (pending)
                {
                    if (pending > 1 && one_blank_before_tab_stop)
                        pending_blank[0] = '\t';
                    if (fwrite ( pending_blank , 1 , pending , stdout ) != pending)
                        write_error();
                };
            };
            if (g . ch == MBBUF_EOF)
            {
                free(pending_blank);
                return void;
            };
            fwrite;
            if (ferror)
                write_error();
        }
        while (g . ch != '\n');
    };
};

cdecl main(int argc, byte** argv) -> int
{
    bool;
    int tabval;
    int c;
    bool;
    set_program_name(argv[0]);
    setlocale;
    atexit;
    while ((c = getopt_long) != -1)
    {
    };
    if (have_tabval)
        add_tab_stop(tabval);
    finalize_tab_stops();
    set_file_list;
    unexpand();
    cleanup_file_list_stdin();
    return exit_status;
};
