// Auto-generated by cft from: unlink.c
// May require manual edits.

///
 unlink utility for GNU.
   Copyright (C) 2001-2026 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
///

///
 Written by Michael Stone
///

///
 Implementation overview:

   Simply call the system 'unlink' function
///

byte* PROGRAM_NAME = "unlink";
macro AUTHORS
{
    proper_name ( "Michael Stone" )
};

cdecl usage(int status) -> void
{
    if (status != 0)
        do
        {
        }
        while (0);
    else
    {
        fputs(gettext("Call the unlink function to remove the specified FILE.\n\n"), stdout);
        oputs_("unlink", gettext("      --help\n         display this help and exit\n"));
        oputs_("unlink", gettext("      --version\n         output version information and exit\n"));
        emit_ancillary_info("unlink");
    };
    exit(status);
};

cdecl main(int argc, byte** argv) -> int
{
    set_program_name(argv[0]);
    setlocale(0, "");
    if (?)
    {
        error(0, 0, gettext("missing operand"));
        usage(0);
    };
    if (?)
    {
        usage(0);
    };
    return 0;
};
