// Auto-generated by cft from: wc.c
// May require manual edits.

///
 wc - print the number of lines, words, and bytes in files
   Copyright (C) 1985-2026 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
///

///
 Written by Paul Rubin, phr@ocf.berkeley.edu
   and David MacKenzie, djm@gnu.ai.mit.edu.
///

byte* PROGRAM_NAME = "wc";
macro AUTHORS
{
    proper_name ( "Paul Rubin" ) , proper_name ( "David MacKenzie" )
};

extern int wc_isprint;
extern int wc_isspace;
extern int debug;
extern int total_lines;
extern int total_words;
extern int total_chars;
extern int total_bytes;
extern int total_lines_overflow;
extern int total_words_overflow;
extern int total_chars_overflow;
extern int total_bytes_overflow;
extern int max_line_length;
extern int print_lines;
extern int print_linelength;
extern int number_width;
extern int have_read_stdin;
extern int page_size;
extern int posixly_correct;
struct fstatus
{
    int failed;
    stat st;
};

uint DEBUG_PROGRAM_OPTION = 0;
uint FILES0_FROM_OPTION = 1;
uint TOTAL_OPTION = 2;

struct option;
extern int longopts;
enum total_type
{
    total_auto,
    total_always,
    total_only,
    total_never
};

extern byte** total_args;
total_type[4] total_types = total_type;
cdecl ARGMATCH_VERIFY() -> int;
total_type total_mode = total_type;
cdecl usage(int status) -> void
{
    if (status != EXIT_SUCCESS)
        do
        {
            fprintf;
        }
        while (0);
    else
    {
        printf;
        fputs;
        emit_stdin_note();
        fputs;
        oputs_("wc", gettext("\
  -c, --bytes\n\
         print the byte counts\n\
"));
        oputs_("wc", gettext("\
  -m, --chars\n\
         print the character counts\n\
"));
        oputs_("wc", gettext("\
  -l, --lines\n\
         print the newline counts\n\
"));
        oputs_("wc", gettext("\
      --debug\n\
         indicate what line count acceleration is used\n\
"));
        oputs_("wc", gettext("\
      --files0-from=F\n\
         read input from the files specified by\n\
         NUL-terminated names in file F;\n\
         If F is -, read names from standard input\n\
"));
        oputs_("wc", gettext("\
  -L, --max-line-length\n\
         print the maximum display width\n\
"));
        oputs_("wc", gettext("\
  -w, --words\n\
         print the word counts\n\
"));
        oputs_("wc", gettext("\
      --total=WHEN\n\
         when to print a line with total counts;\n\
         WHEN can be: auto, always, only, never\n\
"));
        oputs_("wc", gettext("      --help\n         display this help and exit\n"));
        oputs_("wc", gettext("      --version\n         output version information and exit\n"));
        emit_ancillary_info("wc");
    };
    exit(status);
};

cdecl maybe_c32isnbspace(int wc) -> int
{
    return !posixly_correct & c32isnbspace(wc);
};

cdecl write_counts(int lines, int words, int chars, int bytes, int linelength, byte* file) -> void
{
    byte[5] format_sp_int = " %*s";
    byte* format_int = format_sp_int + 1;
    void* /* untranslated: char[MAX(<recovery-expr>(INT_BUFSIZE_BOUND), <recovery-expr>(INT_BUFSIZE_BOUND))] */ buf = MAX(INT_BUFSIZE_BOUND, INT_BUFSIZE_BOUND);
    if (print_lines)
    {
        printf(format_int, number_width, umaxtostr(lines, buf));
        format_int = format_sp_int;
    };
    if (print_words)
    {
        printf(format_int, number_width, umaxtostr(words, buf));
        format_int = format_sp_int;
    };
    if (print_chars)
    {
        printf(format_int, number_width, umaxtostr(chars, buf));
        format_int = format_sp_int;
    };
    if (print_bytes)
    {
        printf(format_int, number_width, umaxtostr(bytes, buf));
        format_int = format_sp_int;
    };
    if (print_linelength)
        printf(format_int, number_width, imaxtostr(linelength, buf));
    if (file)
        printf(" %s", strchr(file, '\n') ? quotearg_n_style_colon : file);
    putchar('\n');
    if (ferror)
        write_error();
};

cdecl wc_lines(int fd) -> wc_lines
{
    bool;
    while (true)
    {
        byte[262145] buf = IO_BUFSIZE + 1;
        byte* end;
        if (! long_lines)
        {
        }
        else
        {
            *end = '\n';
        };
    };
};

cdecl wc(int fd, byte* file_x, fstatus* fstatus) -> int
{
    int err = 0;
    byte[262145] buf = IO_BUFSIZE + 1;
    bool;
    byte* file = file_x ? file_x : gettext("standard input");
    if (MB_CUR_MAX > 1)
    {
    }
    else
    {
    };
    if (! count_bytes || count_chars || print_lines || count_complicated)
        fdadvise;
    if (count_bytes && ! count_chars && ! print_lines && ! count_complicated)
    {
        bool;
        if (0 < fstatus.failed)
            fstatus.failed = fstat(fd, @fstatus);
        if (!fstatus.failed & usable_st_size(@fstatus) & 0 <= fstatus.)
        {
            if (current_pos < 0)
            elif (end_pos % page_size)
            {
            };
            else
            {
            };
        };
        if (! skip_read)
        {
            fdadvise;
        };
    }
    elif (! count_chars && ! count_complicated)
    {
        wc_lines w = wc_lines(fd);
        err = w.err;
    };
    else
        if (MB_CUR_MAX > 1)
        {
            bool;
            mbszero;
            bool;
        }
        else
        {
            bool;
        };
    if (total_mode != total_only)
        write_counts;
    total_lines_overflow `|= ckd_add;
    total_words_overflow `|= ckd_add;
    total_chars_overflow `|= ckd_add;
    total_bytes_overflow `|= ckd_add;
    if (err)
        error(0, err, "%s", quotearg_n_style_colon);
    return !err;
};

cdecl wc_file(byte* file, fstatus* fstatus) -> int
{
    if (!file | streq(file, "-"))
    {
        xset_binary_mode;
        return wc;
    }
    else
    {
        int fd = open;
        if (fd == -1)
        {
            error;
        }
        else
        {
            bool;
            if (close(fd) != 0)
            {
                error;
            };
        };
    };
};

cdecl get_input_fstatus(int nfiles, byte** file) -> fstatus*
{
    fstatus* fstatus = xnmalloc(nfiles ? nfiles : 1, (sizeof * fstatus / 8));
    if (nfiles == 0 || ( nfiles == 1 && ( ( print_lines + print_words + print_chars + print_bytes + print_linelength ) == 1 ) ))
        fstatus[0].failed = 1;
    else
    {
    };
    return fstatus;
};

cdecl compute_number_width(int nfiles, fstatus* fstatus) -> int
{
    int width = 1;
    if (0 < nfiles & fstatus[0].failed <= 0)
    {
        int minimum_width = 1;
        if (width < minimum_width)
            width = minimum_width;
    };
    return width;
};

cdecl main(int argc, byte** argv) -> int
{
    int optc;
    byte** files;
    byte* files_from;
    fstatus* fstatus;
    Tokens tok;
    set_program_name(argv[0]);
    setlocale;
    atexit;
    page_size = getpagesize();
    setvbuf;
    bool;
    argv_iterator* ai;
    if (files_from)
    {
        if (optind < argc)
        {
            error(0, 0, gettext("extra operand %s"), quotearg_style);
            fprintf;
            usage;
        };
        if (streq(files_from, "-"))
        else
        {
            if (stream == NULL)
                error;
        };
        stat st;
        if (fstat(fileno, @st) == 0 & S_ISREG(st.) & st. <= MIN(10 * 1024 * 1024, physmem_available() / 2))
        {
            readtokens0_init(@tok);
            if (!readtokens0 | fclose != 0)
                error;
            files = tok.;
            ai = argv_iter_init_argv(files);
        }
        else
        {
            ai = argv_iter_init_stream;
        };
    }
    else
    {
        byte** stdin_only;
        ai = argv_iter_init_argv(files);
    };
    if (!ai)
        xalloc_die();
    fstatus = get_input_fstatus;
    if (total_mode == total_only)
        number_width = 1;
    else
        number_width = compute_number_width;
    bool;
    argv_iter_err ai_err;
    byte* file_name;
    for (int i = 0; (file_name = argv_iter(ai, @ai_err)); i++)
    {
        bool;
        if (files_from & streq(files_from, "-") & streq(file_name, "-"))
        {
            error(0, 0, gettext("when reading file names from standard input, "), quotearg_style);
        };
        if (!file_name[0])
        {
            if (files_from == NULL)
                error(0, 0, "%s", gettext("invalid zero-length file name"));
            else
            {
                error(0, 0, "%s:%zu: %s", quotearg_n_style_colon, argv_iter_n_args(ai), gettext("invalid zero-length file name"));
            };
        };
        if (! nfiles)
            fstatus[0].failed = 1;
    };
    switch (ai_err)
    {
        error;
        xalloc_die();
        default
        {
        };
    };
    if (read_tokens)
        readtokens0_free(@tok);
    if (total_mode != total_never & (total_mode != total_auto | 1 < argv_iter_n_args(ai)))
    {
        if (total_lines_overflow)
        {
            error;
        };
        if (total_words_overflow)
        {
            error;
        };
        if (total_chars_overflow)
        {
            error;
        };
        if (total_bytes_overflow)
        {
            error;
        };
        write_counts;
    };
    argv_iter_free(ai);
    free(fstatus);
    if (have_read_stdin & close != 0)
        error;
};
