// Auto-generated by cft from: whoami.c
// May require manual edits.

///
 whoami -- print effective userid

   Copyright (C) 1989-2026 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
///

///
 Equivalent to 'id -un'.
///

///
 Written by Richard Mlynarik.
///

byte* PROGRAM_NAME = "whoami";
macro AUTHORS
{
    proper_name ( "Richard Mlynarik" )
};

cdecl usage(int status) -> void
{
    if (status != EXIT_SUCCESS)
        do
        {
            fprintf;
        }
        while (0);
    else
    {
        printf;
        fputs;
        oputs_("whoami", gettext("      --help\n         display this help and exit\n"));
        oputs_("whoami", gettext("      --version\n         output version information and exit\n"));
        emit_ancillary_info("whoami");
    };
    exit(status);
};

cdecl main(int argc, byte** argv) -> int
{
    set_program_name(argv[0]);
    setlocale;
    atexit;
    parse_gnu_standard_options_only;
    if (optind != argc)
    {
        error(0, 0, gettext("extra operand %s"), quote);
        usage;
    };
    passwd* pw;
    if (!pw)
        error;
    puts(pw);
};
