// Auto-generated by cft from: BitReader.h
// May require manual edits.

///
===-- llvm-c/BitReader.h - BitReader Library C Interface ------*- C++ -*-===*\
|*                                                                            *|
|* Part of the LLVM Project, under the Apache License v2.0 with LLVM          *|
|* Exceptions.                                                                *|
|* See https://llvm.org/LICENSE.txt for license information.                  *|
|* SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception                    *|
|*                                                                            *|
|*===----------------------------------------------------------------------===*|
|*                                                                            *|
|* This header declares the C interface to libLLVMBitReader.a, which          *|
|* implements input of the LLVM bitcode format.                               *|
|*                                                                            *|
|* Many exotic languages can interoperate with C code but have a harder time  *|
|* with C++ due to name mangling. So in addition to C, this interface enables *|
|* tools written in such languages.                                           *|
|*                                                                            *|
\*===----------------------------------------------------------------------===
///

#ifndef LLVM_C_BITREADER_H;
#def LLVM_C_BITREADER_H 1;
#import "llvm-c/Deprecated.fx";
#import "llvm-c/ExternC.fx";
#import "llvm-c/Types.fx";
#import "llvm-c/Visibility.fx";
LLVM_C_EXTERN_C_BEGIN;
///
*
* @defgroup LLVMCBitReader Bit Reader
* @ingroup LLVMC
*
* @{

///

///
Builds a module from the bitcode in the specified memory buffer, returning a
reference to the module via the OutModule parameter. Returns 0 on success.
Optionally returns a human-readable error message via OutMessage.

This is deprecated. Use LLVMParseBitcode2.
///

cdecl LLVMParseBitcode(LLVMOpaqueMemoryBuffer* MemBuf, LLVMOpaqueModule** OutModule, byte** OutMessage) -> int;
///
Builds a module from the bitcode in the specified memory buffer, returning a
reference to the module via the OutModule parameter. Returns 0 on success.
///

cdecl LLVMParseBitcode2(LLVMOpaqueMemoryBuffer* MemBuf, LLVMOpaqueModule** OutModule) -> int;
///
This is deprecated. Use LLVMParseBitcodeInContext2.
///

cdecl LLVMParseBitcodeInContext(LLVMOpaqueContext* ContextRef, LLVMOpaqueMemoryBuffer* MemBuf, LLVMOpaqueModule** OutModule, byte** OutMessage) -> int;
cdecl LLVMParseBitcodeInContext2(LLVMOpaqueContext* ContextRef, LLVMOpaqueMemoryBuffer* MemBuf, LLVMOpaqueModule** OutModule) -> int;
///
* Reads a module from the specified path, returning via the OutMP parameter
 a module provider which performs lazy deserialization. Returns 0 on success.
 Optionally returns a human-readable error message via OutMessage.
 This is deprecated. Use LLVMGetBitcodeModuleInContext2.
///

cdecl LLVMGetBitcodeModuleInContext(LLVMOpaqueContext* ContextRef, LLVMOpaqueMemoryBuffer* MemBuf, LLVMOpaqueModule** OutM, byte** OutMessage) -> int;
///
* Reads a module from the given memory buffer, returning via the OutMP
* parameter a module provider which performs lazy deserialization.
*
* Returns 0 on success.
*
* Takes ownership of \p MemBuf if (and only if) the module was read
* successfully.
///

cdecl LLVMGetBitcodeModuleInContext2(LLVMOpaqueContext* ContextRef, LLVMOpaqueMemoryBuffer* MemBuf, LLVMOpaqueModule** OutM) -> int;
///
This is deprecated. Use LLVMGetBitcodeModule2.
///

cdecl LLVMGetBitcodeModule(LLVMOpaqueMemoryBuffer* MemBuf, LLVMOpaqueModule** OutM, byte** OutMessage) -> int;
cdecl LLVMGetBitcodeModule2(LLVMOpaqueMemoryBuffer* MemBuf, LLVMOpaqueModule** OutM) -> int;
///
*
* @}

///

LLVM_C_EXTERN_C_END;
#endif;