// Auto-generated by cft from: Types.h
// May require manual edits.

///
===-- llvm-c/Support.h - C Interface Types declarations ---------*- C -*-===*\
|*                                                                            *|
|* Part of the LLVM Project, under the Apache License v2.0 with LLVM          *|
|* Exceptions.                                                                *|
|* See https://llvm.org/LICENSE.txt for license information.                  *|
|* SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception                    *|
|*                                                                            *|
|*===----------------------------------------------------------------------===*|
|*                                                                            *|
|* This file defines types used by the C interface to LLVM.                   *|
|*                                                                            *|
\*===----------------------------------------------------------------------===
///

#ifndef LLVM_C_TYPES_H;
#def LLVM_C_TYPES_H 1;
#import "llvm-c/DataTypes.fx";
#import "llvm-c/ExternC.fx";
LLVM_C_EXTERN_C_BEGIN;
///
*
* @defgroup LLVMCSupportTypes Types and Enumerations
*
* @{

///

// typedef: LLVMBool = int
///
Opaque types.
///

///
*
* LLVM uses a polymorphic type hierarchy which C cannot represent, therefore
* parameters must be passed as base types. Despite the declared types, most
* of the functions provided operate only on branches of the type hierarchy.
* The declared parameter names are descriptive and specify which type is
* required. Additionally, each type hierarchy is documented along with the
* functions that operate upon it. For more detail, refer to LLVM's C++ code.
* If in doubt, refer to Core.cpp, which performs parameter downcasts in the
* form unwrap<RequiredType>(Param).

///

///
*
* Used to pass regions of memory through LLVM interfaces.
*
* @see llvm::MemoryBuffer

///

LLVMOpaqueMemoryBuffer* as LLVMMemoryBufferRef;

struct LLVMOpaqueMemoryBuffer;
///
*
* The top-level container for all LLVM global data. See the LLVMContext class.

///

LLVMOpaqueContext* as LLVMContextRef;

struct LLVMOpaqueContext;
///
*
* The top-level container for all other LLVM Intermediate Representation (IR)
* objects.
*
* @see llvm::Module

///

LLVMOpaqueModule* as LLVMModuleRef;

struct LLVMOpaqueModule;
///
*
* Each value in the LLVM IR has a type, an LLVMTypeRef.
*
* @see llvm::Type

///

LLVMOpaqueType* as LLVMTypeRef;

struct LLVMOpaqueType;
///
*
* Represents an individual value in LLVM IR.
*
* This models llvm::Value.

///

LLVMOpaqueValue* as LLVMValueRef;

struct LLVMOpaqueValue;
///
*
* Represents a basic block of instructions in LLVM IR.
*
* This models llvm::BasicBlock.

///

LLVMOpaqueBasicBlock* as LLVMBasicBlockRef;

struct LLVMOpaqueBasicBlock;
///
*
* Represents an LLVM Metadata.
*
* This models llvm::Metadata.

///

LLVMOpaqueMetadata* as LLVMMetadataRef;

struct LLVMOpaqueMetadata;
///
*
* Represents an LLVM Named Metadata Node.
*
* This models llvm::NamedMDNode.

///

LLVMOpaqueNamedMDNode* as LLVMNamedMDNodeRef;

struct LLVMOpaqueNamedMDNode;
///
*
* Represents an entry in a Global Object's metadata attachments.
*
* This models std::pair<unsigned, MDNode *>

///

struct LLVMOpaqueValueMetadataEntry;
// typedef alias: LLVMValueMetadataEntry -> LLVMOpaqueValueMetadataEntry

///
*
* Represents an LLVM basic block builder.
*
* This models llvm::IRBuilder.

///

LLVMOpaqueBuilder* as LLVMBuilderRef;

struct LLVMOpaqueBuilder;
///
*
* Represents an LLVM debug info builder.
*
* This models llvm::DIBuilder.

///

LLVMOpaqueDIBuilder* as LLVMDIBuilderRef;

struct LLVMOpaqueDIBuilder;
///
*
* Interface used to provide a module to JIT or interpreter.
* This is now just a synonym for llvm::Module, but we have to keep using the
* different type to keep binary compatibility.

///

LLVMOpaqueModuleProvider* as LLVMModuleProviderRef;

struct LLVMOpaqueModuleProvider;
///
* @see llvm::PassManagerBase
///

LLVMOpaquePassManager* as LLVMPassManagerRef;

struct LLVMOpaquePassManager;
///
*
* Used to get the users and usees of a Value.
*
* @see llvm::Use
///

LLVMOpaqueUse* as LLVMUseRef;

struct LLVMOpaqueUse;
///
*
* @see llvm::OperandBundleDef

///

LLVMOpaqueOperandBundle* as LLVMOperandBundleRef;

struct LLVMOpaqueOperandBundle;
///
*
* Used to represent an attributes.
*
* @see llvm::Attribute

///

LLVMOpaqueAttributeRef* as LLVMAttributeRef;

struct LLVMOpaqueAttributeRef;
///
*
* @see llvm::DiagnosticInfo

///

LLVMOpaqueDiagnosticInfo* as LLVMDiagnosticInfoRef;

struct LLVMOpaqueDiagnosticInfo;
///
*
* @see llvm::Comdat

///

LLVMComdat* as LLVMComdatRef;

struct LLVMComdat;
///
*
* @see llvm::Module::ModuleFlagEntry

///

struct LLVMOpaqueModuleFlagEntry;
// typedef alias: LLVMModuleFlagEntry -> LLVMOpaqueModuleFlagEntry

///
*
* @see llvm::JITEventListener

///

LLVMOpaqueJITEventListener* as LLVMJITEventListenerRef;

struct LLVMOpaqueJITEventListener;
///
*
* @see llvm::object::Binary

///

LLVMOpaqueBinary* as LLVMBinaryRef;

struct LLVMOpaqueBinary;
///
*
* @see llvm::DbgRecord

///

LLVMOpaqueDbgRecord* as LLVMDbgRecordRef;

struct LLVMOpaqueDbgRecord;
///
*
* @}

///

LLVM_C_EXTERN_C_END;
#endif;